### DISCUSSION TITLE
how can i add HTML in the custom:button-card ?

### DISCUSSION THREAD

**Discussion by ingeniumdesign** [UI-Lovelace-Minimalist/UI#1149] [Q&A] [answered]
**how can i add HTML in the custom:button-card ?**
like this:

```
<button-card style="flex: 0 0 auto; max-width: fit-content; --button-card-light-color:var(--primary-text-color); --button-card-light-color-no-temperature:var(--primary-text-color);">
<hr />
</button-card>
```

add a `<hr />` in the wrap.

**and how can i edit here the inline css?**

```
<button-card style="flex: 0 0 auto; max-width: fit-content; --button-card-light-color:var(--primary-text-color); --button-card-light-color-no-temperature:var(--primary-text-color);"></button-card>
```

**i need the button-card in full with:**
flex: auto;
max-width: none;

For the development, i copy me the "card-title" Element.
```
---
### Card Separator ###
card_ing_separator:
  tap_action:
    action: "none"
  show_icon: false
  show_label: false
  show_name: true
  styles:
    card:
      - box-shadow: "none"
      - height: "auto"
      - width: "100vw"
      - margin-top: "0px"
      - margin-left: "0px"
      - margin-bottom: "0px"
      - padding-top: "22px"
      - padding-bottom: "22px"
      - background-color: "rgba(255,0,0,1)"
      - position: "relative"
```

thanks all

**Comment by ingeniumdesign** [comment, marked as answer]
in the "name" part work the HTML, but i have a better solution:

```
---
### Card Separator ###
card_ing_separator:
  name: "[[[ return variables.name ]]]"
  tap_action:
    action: "none"
  show_icon: false
  show_label: false
  show_name: true
  variables:
    height: "2px"
    width: "100vw"
    bgColor: "rgba(var(--color-theme), 0.1)"
    padding: "8px"
    name: " "
  styles:
    card:
      - box-shadow: "none"
      - border: "none"
      - border-radius: "0"
      - width: "[[[ return variables.width ]]]"
      - margin: "0"
      - padding-top: "[[[ return variables.padding ]]]"
      - padding-bottom: "[[[ return variables.padding ]]]"
      - position: "relative"
      - background: "none"
      - display: "block"
    name:
      - width: "100%"
      - height: "[[[ return variables.height ]]]"
      - background-color: "[[[ return variables.bgColor ]]]"
      - text-overflow: "unset"
      - grid-area: "unset"
    test:
      - width: "100%"
      - height: "10px"
    grid:
      - grid-template-areas: "'n'"
      - grid-template-columns: "1fr"
      - grid-template-rows: "1fr"
  extra_styles: |
    #aspect-ratio {
      display: block !important;
    }
```
