### DISCUSSION TITLE
card_room with popup_thermostat ?

### DISCUSSION THREAD

**Discussion by ingeniumdesign** [UI-Lovelace-Minimalist/UI#1153] [Q&A]
how can i use the card_room with popup_thermostat? 

**First try:**
```
- type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            template:
              - ulm_translation_engine
              - card_room
              - grey_no_state
              - grey_on
              - grey_off
            name: Schlafzimmer
            entity: climate.schlafzimmer_dect301_1
            icon: mdi:bed-king
            hold_action:
              action: none
            tap_action:
              action: "fire-dom-event"
              browser_mod:
                service: "browser_mod.popup"
                data:
                  large: true
                  hide_header: true
                  content:
                    type: "custom:button-card"
                    template: "popup_thermostat_temperature"
                    entity: "[[[ return entity.entity_id ]]]"
```

This card is empty, how can i give him the right "entity: climate.schlafzimmer_dect301_1" ?
