### DISCUSSION TITLE
Is there a way to change the ulm graph color base on value?

### DISCUSSION THREAD

**Discussion by rairulyle** [UI-Lovelace-Minimalist/UI#1167] [Q&A]
I have an Air Quality Graph Card and I wanted to change its color based on the ff values:

![image](https://user-images.githubusercontent.com/12708526/218258254-967ab61b-be83-4924-bb79-11049a91da30.png)

Is this possible?

```
- type: "custom:button-card"
              template: card_graph
              entity: sensor.zhimi_vb4_00ae_pm25_density
              variables:
                ulm_card_graph_color: "var(--google-green)"
                ulm_card_graph_name: Room Air Quality
                ulm_card_graph_entity: sensor.zhimi_vb4_00ae_pm25_density
                ulm_card_graph_type: fill
                ulm_card_graph_hours: 24
                ulm_card_graph_group_by: interval
```

![image](https://user-images.githubusercontent.com/12708526/218258336-adf5a236-d536-4d78-841f-ee510a2d5dda.png)
