### DISCUSSION TITLE
Light Card show Last Changed?

### DISCUSSION THREAD

**Discussion by jarrah31** [UI-Lovelace-Minimalist/UI#1370] [Ideas]
Hello,

I'm looking to migrate to UI-Minimalist but I'm missing the "show_last_changed" feature from button-card in the "light_card" template. I wondered if it might be possible for you to integrate it in a future update please?

For example, my own button-card template looks like this, with last changed as small text below the state:
<img width="251" alt="image" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/3072303/944a6c28-6b0a-4808-a692-6d9f609c7bbf">

I tried enabling "show_last_changed" in the "light_card" template but it just did this:
<img width="249" alt="image" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/3072303/a4e98b00-5ddf-458d-92ad-3f38ae44bebf">
```
          - type: "custom:button-card"
            template: "card_light"
            show_last_changed: true
            entity: switch.plug_zigbee04
            variables:
              ulm_card_light_name: Stairs
              ulm_card_light_icon: mdi:desk-lamp
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_collapse: true
```

I tried to follow the light_card template code but I really don't know where or how I could fit this into the grid without breaking other variables. If possible it would be nice if this could appear just below the "On/Off" state text, and be a ulm option please?

Thank you
