### DISCUSSION TITLE
Font color problems with esh_room_card

### DISCUSSION THREAD

**Discussion by Tobboss** [UI-Lovelace-Minimalist/UI#1403] [Q&A]
Hi! I don't think this is intended because it's somewhat inconsistent.

I have a problem with the text color of the name. 
When I refresh the page then the name of the room is white. It is brighter if dynamic color is true.
When turned off the text turns dark grey. It stays dark when turned on again.

This picture is directly after refreshing. An light entity linked in the room cards as reference.
![RDT_20231103_2014048048091900474171624.jpg](https://github.com/UI-Lovelace-Minimalist/UI/assets/4268049/c8f5e27b-c33f-4092-a7d5-662b6175c4ea)

Here you can see the on state after toggling once. It is the same grey as the turned off ones. 
If you look closely the left one is still a bit brighter. The icon too.

![RDT_20231103_2014107359690844806394586.jpg](https://github.com/UI-Lovelace-Minimalist/UI/assets/4268049/bf788c8b-1332-4b1b-b38e-1d062d79dff5)

This is my code 
```
   - type: "custom:button-card"
              template:
                - card_esh_room
              name: Wohnzimmer
              entity: light.stehlampen
              icon: mdi:sofa
              tap_action:
                action: navigate
                navigation_path: "wohnzimmer"
              variables:
                ulm_custom_card_esh_room_light_entity: light.stehlampen
                ulm_card_dynamic_color: true
              label: >
                [[[
                  return Math.round(states['sensor.mijia_wohnzimmer_temperature'].state).toFixed(1) + " °C" + " | " + Math.round(states['sensor.mijia_wohnzimmer_humidity'].state).toFixed(0) + " %"
                ]]]
```
