### DISCUSSION TITLE
How to display it properly on the tablet

### DISCUSSION THREAD

**Discussion by iliesh** [UI-Lovelace-Minimalist/UI#1430] [General]
How can I make cards bigger on the tablet devices?
At the moment it looks like this:

![2023-12-27_11-48](https://github.com/UI-Lovelace-Minimalist/UI/assets/14953151/1f1d06f7-228b-4f7c-805a-03263ff79ad9)

I want to use the extra space from the sides, so ideally would be to increase the size of the card with all components within it?

**Comment by iliesh** [comment]
btw, this is the configuration block I'm using:
```
title: "Home"
path: "home"
cards:
  - type: vertical-stack
    cards:
      - type: "custom:button-card"
        template: "card_esh_welcome"
        triggers_update: "input_boolean.minimalist_dropdown"
        variables:
          ulm_card_esh_welcome_collapse: input_boolean.minimalist_dropdown
          ulm_weather: "weather.forecast_home"
          entity_1:
            nav: "house"
            icon: "mdi:home"
            name: "House"
            color: "blue"
          entity_2:
            nav: "lights"
            icon: "mdi:lightbulb"
            name: "Lights"
            color: "yellow"
          entity_3:
            nav: "security"
            icon: "mdi:shield"
            name: Secure
            color: "green"
          entity_4:
            nav: "lights"
            icon: "mdi:lightbulb"
            name: "Lights"
            color: "yellow"
          entity_5:
            nav: "security"
            icon: "mdi:shield"
            name: Secure
            color: "green"
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            template: card_person_info
            variables:
          - type: "custom:button-card"
            template: card_person_info
            variables:
      - type: vertical-stack
        cards:
          - type: "custom:button-card"
            template: card_title
            name: Rooms
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template:
                  - card_esh_room
                  - grey_no_state
                  - yellow_on
                name: Living
              - type: "custom:button-card"
                template:
                  - card_esh_room
                  - grey_no_state
                  - yellow_on
                name: Kitchen
                entity: switch.kitchen_lights
                icon: mdi:fridge
              - type: "custom:button-card"
                template:
                  - card_esh_room
                  - grey_no_state
                  - yellow_on
                name: Kids
```
