### DISCUSSION TITLE
Color changing of icon

### DISCUSSION THREAD

**Discussion by mp-se** [UI-Lovelace-Minimalist/UI#175] [Ideas]
One thing I have noticed in the basic template is that most of the base color is blue. From Tbens orginal post on the forum he described that he was using different colors for different type of objects, yellow for electicity etc. 

I have noticed in the code that on some cards there is a default variable called color which is then used if the card is active. 

```
  variables:
    color: "blue"

  state:
    - operator: "template"
      value: "[[[ return entity.state == variables.state ]]]"
      styles:
        icon:
          - color: "[[[ return `rgba(var(--color-${variables.color}), 1)`; ]]]"
        label:
          - color: "[[[ return `rgba(var(--color-${variables.color}-text), 1)`; ]]]"
        name:
          - color: "[[[ return `rgba(var(--color-${variables.color}-text), 1)`; ]]]"
        img_cell:
          - background-color: "[[[ return `rgba(var(--color-${variables.color}), 0.2)`; ]]]"
        card:
          - background-color: "[[[ return `rgba(var(--color-background-${variables.color}), var(--opacity-bg))`; ]]]"
```

For instance a I have a wireless wall switch that I use this code for and the default color would be blue. But since this is powering my christmas tree I want this to be yellow. 

```
- type: 'custom:button-card'
  template: card_input_boolean
  entity: switch.sonoff_julgran
```

so by adding the following lines the card could be changed to another color for highlighting the icon. 

```
- type: 'custom:button-card'
  template: card_input_boolean
  entity: switch.sonoff_julgran
  variables:
    color: yellow
```

So my proposal is to make all the base card accept this parameter so it would be easy to change the base color if needed. The vertical cards already have this feature but would be nice to have on all cards. 

In the base theme the following colors are available, blue, red, yellow, green, pink, purple. There is already templates for blue and blue_no_state that can be copied to handle the other colors.
