### DISCUSSION TITLE
Examples / Walkthrough / Storyline for new users

### DISCUSSION THREAD

**Discussion by SirUli** [UI-Lovelace-Minimalist/UI#411] [Ideas]
Hi there,

today I tried to work with this new idea (I started after the HACS move which apparently was a big change) and had my trouble of understanding what to do where.

I believe it would make sense to have a section in the "Usage" part which simply explains where to copy the custom cards that are explained further down the page then.

Maybe even a walk-through would be awesome for users. Something like:

> Lets assume you have a little house with a ground floor with living room & office as well as an upper floor with master bedroom & bath room (where your washing machine, dryer etc sits). Now lets walk through the dashboard creation.
> Step 1: Create the overview of the floors
> ...

I actually have a hard time even drafting the story since the concepts are still not clear to me. E.g. I actually didn't look into the development part first and had no idea what a "chip" is. After I read [this page](https://ui-lovelace-minimalist.github.io/UI/development/card_style_guide/) it got a little clearer - for me it makes sense to explain these concepts in the usage section to make sure that the creator of a dashboard knows which is which.

Alternatively an example repository would be awesome - i only found repos like [this one](https://github.com/CM000n/homeassistant) which isn't following the same structure as the HACS installation.

Maybe an idea to go into that direction?

**Comment by basbruss** [comment]
Hi @SirUli , thanks for your feedback and ideas. 

Most of documentation about the custom_cards will get a separate page underneath setup with this PR #387. This will be available for everyone with release v0.0.5 😄. Could be released anytime soon.

Edit: The release is just live check the documentation on this page: https://ui-lovelace-minimalist.github.io/UI/setup/custom_cards/ 

I also have a custom repo where I share my config with a HACS-install.
The link is not yet widely spread around our wiki/forum/discord but feel free to take a look. https://github.com/basbruss/Minimalist-Dashboards

**Reply by SirUli** [reply]
Very cool. I guess then only "views" will require an additional explanation. Especially since the default deploys something like that:

```yaml
---
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: "var(--background-image)"
# views: !include_dir_merge_list "views/"
views:
  - title: "Start"
    path: 0
    cards:
      - type: "custom:button-card"
        entity: "sun.sun"
```

But then there is no explanation why the first ``#view`` is commented or what that is about. With your repository it gets a little clearer that this should be a folder structure like this:

```yaml
config
└── ui_lovelace_minimalist
    ├── config
    ├── custom_cards
    └── dashboard
        ├── views
        |   ├── bedroom.yaml
        |   └── bath.yaml
        └── ui-lovelace.yaml
```

Maybe i overlooked it but explaining the idea behind views (to separate "rooms" or "topics" for example) might be useful then.
