### DISCUSSION TITLE
Conditional cards and chips?

### DISCUSSION THREAD

**Discussion by dbdmdbdmdbdm** [UI-Lovelace-Minimalist/UI#559] [Q&A] [answered]
Moving over to this UI - is there a way to do "conditional" cards and chips? As in a generic card that only shows when the door is open, a lock is unlocked, etc.?

**Comment by 13robin37** [comment, marked as answer]
Sure, just did that. Just an example for a vacuum chip only showing when the vacuum is not docked:

```
              - type: "conditional"
                conditions:
                  - entity: "vacuum.vacuum"
                    state_not: "docked"
                card:
                  type: "custom:button-card"
                  template: "chip_navigate"
                  label: "Vacuum"
                  variables:
                    ulm_chip_navigate_path: "/ui-lovelace-minimalist/vacuum"
                    ulm_chip_navigate_icon: "mdi:robot-vacuum"
```
