### DISCUSSION TITLE
Customizability through variables

### DISCUSSION THREAD

**Discussion by basbruss** [UI-Lovelace-Minimalist/UI#821] [General]
The step to `v1.0.*` releases has introduced extra complexity to the template's framework (with more nested layers). This to make things more user-friendly.
Starting this discussion after #820 

As the negative effect is that most cards are not easily customizable anymore without using the power of the accompanying variables.
We have brought a bit of this customizability back with the `v1.0.2` release for mainly setting names and icons.

Now the question is _to what extent should we make customizing available through variables_ without being difficult or very time-consuming to set a dashboard up. As button-card offers a lot of types of customizability. We cannot offer it all as that will defeat the purpose of this project to offer easy useable and minimalist-themed templates. Because at that level of customizability it seems better to use button-card directly.

Generally interested in thoughts on this from you!

**Comment by Neekster** [comment]
I would like to be able to customize the name and icon using variables. If I want to customize other things, I have the knowledge and experience to create my own custom card.

For those who may want extended functionality but do not know how to make their own custom card, there should be a written guide on how to implement their own customizations by making their own custom card.

**Reply by modem158** [reply]
I agree completely with @Neekster .  It wrecked my dashboard when I couldn't pass in the name anymore.  I also like being able to pass in the icon so I can customize it based on a state template.

One example for me was the custom_card_nik_nas card.  I had each entity setup with a custom name like "Temp" and then they all fell back to the "Friendly name" which was something like "rpi_vpn_cpu_temp".  Those longer names didn't fit nicely on the card.  I don't want to have to change all my friendly names just to make them fit on a particular card.

**Comment by JSaterdalen** [comment]
I have a couple of buttons that display the name and label of a sensor, but runs a script when tapped. I haven't been able to get this working since the 1.0 changes, but the original code is as follows:

```
- type: "custom:button-card"
  template: card_generic
  entity: sensor.last_updated
  icon: mdi:car
  styles:
    icon:
      - color: "rgba(var(--color-blue),0.7)"
    img_cell:
      - background-color: "rgba(var(--color-blue), 0.2)"
  tap_action:
    action: call-service
    service: script.turn_on
    service_data:
      entity_id: script.log_car
  hold_action:
    action: more-info
    entity: input_datetime.car_time
```

An easy way to not only update icons, colors, etc., but to set custom actions for the _whole_ card would be great. 

Three components within the card makes it more complicated to simply make the whole button run one action on tap.
