### ISSUE TITLE
Custom Card "Room"

### ISSUE THREAD

**Issue by tamet83** [UI-Lovelace-Minimalist/UI#1020]
**Describe the bug**
Hi, is this behavior normal?
<img width="249" alt="Schermata 2022-09-25 alle 17 23 40" src="https://user-images.githubusercontent.com/7949570/192151929-18e8cd9c-8d87-4a4b-a565-5f3ec7b65459.png">

As you can see on the image, the lights are all off but the card color is still on.
I need to refresh page to get rid of it. This doesn't happen to the white theme.

Following the card code:

``` yaml
- type: "custom:button-card"
    template:
      - card_esh_room
      - yellow_on
    name: Sala e cucina
    entity: sensor.temperatura_sala
    icon: mdi:sofa
    color: auto
    tap_action:
      action: navigate
      navigation_path: "sala"
    variables:
      ulm_custom_card_esh_room_light_entity: light.sala
    label: >
      [[[
        return "🌡️ " + states['sensor.temperatura_sala'].state + " °C" + " 💧 " + states['sensor.umidita_sala'].state + " %"
      ]]]
```
