### ISSUE TITLE
Can't get bottom line of custom entities card to render

### ISSUE THREAD

**Issue by frantathefranta** [UI-Lovelace-Minimalist/UI#1066]
**Describe the bug**
I'm getting this error in the bottom row of entities when using this [custom card](https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_irmajavi_entities/):
`ButtonCardJSTemplateError: TypeError: undefined is not an object (evaluating 'variables.ulm_translation_state_unit') in 'return variables.ulm_translation_state_unit'
`

**To Reproduce**
Installed the custom card through the Devices&Services config menu. Minimalist UI version is the latest hotfix. Using this card config (sensors are real and have readings, I tried changing the names as well but no success):
```
 - type: custom:button-card
    template: custom_card_irmajavi_entities
    variables:
      ulm_custom_card_irmajavi_entities_entity_1: sensor.attic_temp_and_humidity_humidityd
      ulm_custom_card_irmajavi_entities_entity_2: sensor.bedroom_temp_and_humidity_humidity
      ulm_custom_card_irmajavi_entities_entity_3: sensor.cara_office_temp_and_humidity_humidity
      ulm_custom_card_irmajavi_entities_entity_4: sensor.outside_temp_and_humidity_humidity
      ulm_custom_card_irmajavi_entities_name_1: Voltage
      ulm_custom_card_irmajavi_entities_name_2: Temperature
      ulm_custom_card_irmajavi_entities_name_3: AC Power
      ulm_custom_card_irmajavi_entities_name_4: Current
      ulm_custom_card_irmajavi_entities_name: System Status
      ulm_custom_card_irmajavi_entities: sensor.outside_temp_and_humidity_humidity
      ulm_custom_card_irmajavi_entities_icon: mdi:sofa
```

**Expected behavior**
I would like it to look like the screenshot on the linked page.

**Screenshots**
<img width="402" alt="image" src="https://user-images.githubusercontent.com/64412753/198131449-2dc5b906-236a-4b82-a263-213853ef508f.png">

**Additional context**
Nothing comes to mind

**Comment by aherbjornsen** [comment]
Don't know if you've already figured this out by yourself, but there is a missing "template:" in the custom_widget_irmajavi definition in the custom card yaml. It should look like this:

```
custom_widget_irmajavi:
  template:
    - "ulm_translation_engine"
  show_label: true
(...)
```

**Comment by 1liminal1** [comment]
Hey there, 

I'm having the same issue? 

Can you give me a little more context for this? I have this set to true and it still wont display anything?


```
---
custom_card_irmajavi_entities:
  template:
    - "ulm_translation_engine"
  triggers_update: "all"
  show_icon: true
  show_name: true
  show_label: true
```
