### ISSUE TITLE
Custom Cards are not rendering

### ISSUE THREAD

**Issue by towerclimber87** [UI-Lovelace-Minimalist/UI#1070]
Version 1.1.6
Custom cards are not rendering.  Revert back to 1.1.5-hotfix does not solve the issue

My config:

          - type: "custom:button-card" 
            entity: "camera.blueiris_front_door"
            template: "custom_card_camera"
            show_icon: false #True if you set ulm_custom_card_camera_title: true
            variables:
                ulm_custom_card_camera_title: false
                ulm_custom_card_camera_name: "name"
                ulm_custom_card_camera_label: "label"  

              - type: "custom:button-card"
                entity: lock.house
                template: "custom_card_eraycetinay_lock"
                name: "House"
                variables:
                  ulm_custom_card_eraycetinay_lock_tap_control: true
                  ulm_custom_card_eraycetinay_lock_door_open: binary_sensor.front_entry_door
The error:
Button-card template 'custom_card_camera' is missing!
Button-card eraycetinary_lock_language_variables' is missing!

I

Anyone has an idea what I am missing? a couple of days ago this was working correct.

**Comment by V4n1X** [comment]
Can confirm this, not loading this card, my config:
`  - type: "custom:button-card"
    entity: "camera.outdoor"
    template: "custom_card_camera"
    show_icon: true #True if you set ulm_custom_card_camera_title: true
    variables:
      ulm_custom_card_camera_title: true
      ulm_custom_card_camera_name: "name"
      ulm_custom_card_camera_label: "label"`

**Comment by towerclimber87** [comment]
Still no change.
              - type: "custom:button-card"
                entity: "camera.blueiris_back_yard"
                template: "custom_card_camera"
                show_icon: true #True if you set
ulm_custom_card_camera_title: true variables: ulm_custom_card_camera_title:
true
                ulm_custom_card_camera_name: "name"
                ulm_custom_card_camera_label: "label"

**Comment by V4n1X** [comment]
I found out sth, if i load a normal **[picture entity card](type: picture-entity)** first to load the camera stream and then switch where the custom camera card is, it gets shown without problems.

**Comment by KGS501** [comment]
I have the same issue. But the behaviour is all over the place. Sometimes, the card wont load at all, sometimes it works, sometimes it only works on my mobile phone, and sometimes only the picture-entity part of the card is missing (see picture).
![image](https://user-images.githubusercontent.com/83352171/206464881-cc24eeec-100d-44b0-a1a1-13c32f35e474.png)

Maybe the original author of this card can help?
@Eltarius

**Comment by KGS501** [comment]
> I found out sth, if i load a normal **[picture entity card](type: picture-entity)** first to load the camera stream and then switch where the custom camera card is, it gets shown without problems.

I can reproduce this behaviour aswell. Furthermore, the `custom_card_camera` card is working flawlessly, if you load a default `picture-entity` card somewhere in the dashboard where the  `custom_card_camera` card is.

That means you can do a dirty fix by rendering an invisible `picture-entity` card somewhere:

```yaml
         - type: picture-entity
            entity: camera.your_camera
            style: |
              ha-card {
                min-height: 0px !important;
                height: 0px !important;
                opacity: 0;
              }
          - type: "custom:button-card"
            entity: "camera.your_camera"
            template: "custom_card_camera"
            show_icon: true
            variables:
              ulm_custom_card_camera_title: true
              ulm_custom_card_camera_name: "name"
              ulm_custom_card_camera_label: "label"
```
