### ISSUE TITLE
Thermostat popup fails with ButtonCardJSTemplateError

### ISSUE THREAD

**Issue by frantathefranta** [UI-Lovelace-Minimalist/UI#1077]
**Describe the bug**
When I try to see the popup on my custom_card_esh_room card for the thermostat, I get this error:
```
ButtonCardJSTemplateError: TypeError: undefined is not an object (evaluating 'entity.attributes.preset_mode.includes') in 'return entity.attributes.preset_mode.includes('none') ? 'none' : 'None''
```

**To Reproduce**
This is my card setup (it's formatted properly in my YAML, github is just fighting me about it):
```
- type: "custom:button-card"                                                              
   template:                                                                                
    - card_esh_room                                                                        
    - yellow_on                                                                           
    name: Living Room                                                                       
    entity: light.living_room_lamp                                                          
    icon: mdi:sofa                                                                          
    tap_action:                                                                              
      action: navigate                                                                       
      navigation_path: "living-room"                                                        
    variables:                                                                           
      ulm_custom_card_esh_room_light_entity: light.living_room_lamp                       
      ulm_card_light_enable_popup: true                                                      
      ulm_custom_card_esh_room_climate_entity: climate.thermostat                             
      ulm_card_thermostat_enable_popup: true
 
```

**Expected behavior**
The thermostat popup should appear and it has done in the past. However since update 1.1.5 (I think?) it has not worked. Downgrading has also not yielded any results. Weirdly my light popup works just fine still, so the problem only seems to be only about the thermostat part.

**Screenshots**

**Additional context**
I've tried to redownload minimalist-UI, button-card, browser-mod to see if any files were bad. I've updated and downgraded HA, currently on version 2022.11.1, but I think the problem has been persisent on the 2022.10.* I've tried. 

Thanks for any help :)
