### ISSUE TITLE
Doc use custom_card_homeassistant_updates

### ISSUE THREAD

**Issue by boutXIII** [UI-Lovelace-Minimalist/UI#1100]
Hello,
In doc bug 

binary_sensor.updates ==> binary_sensor.updater_core

Old : 
```
- type: "custom:button-card"
  template: card_homeassistant_updates
  variables:
    ulm_card_homeassistant_entity: "binary_sensor.updates"
    ulm_card_homeassistant_core: "sensor.core_updates"
    ulm_card_homeassistant_supervisor: "sensor.supervisor_updates"
    ulm_card_homeassistant_os: "sensor.os_updates"
```
New : 
```
- type: 'custom:button-card'
    template: card_homeassistant_updates
    variables:
      ulm_card_homeassistant_entity: 'binary_sensor.updater_core'
      ulm_card_homeassistant_core: "sensor.core_updates"
      ulm_card_homeassistant_supervisor: "sensor.supervisor_updates"
      ulm_card_homeassistant_os: "sensor.os_updates"
```
