### ISSUE TITLE
Dashboard is stuck on "loading" screen after server restart

### ISSUE THREAD

**Issue by krasnoukhov** [UI-Lovelace-Minimalist/UI#1113]
**Describe the bug**

Dashboard is stuck on "loading" screen after server restart, there are errors in the console, only refresh makes it work again.

**To Reproduce**

1. Have a Minimalist UI dashboard, I tested with a fully empty one

      ```yaml
      ---
      button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"
      
      title: "UI Lovelace Minimalist"
      theme: "minimalist-desktop"
      background: "var(--background-image)"
      views:
        - icon: mdi:home
          path: home
      ```
1. Load this dashboard, press "c", type "restart", select "restart server"
2. Wait for a bit until it stops and then starts again
3. Loading screen appears
4. Console errors appear, loading screen is stuck forever (until refresh)

      ```
      hass-loading-screen.ts:11 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'path')
      ```

**Expected behavior**

Dasbhoard shows loading screen for a while but then renders normally after restart without a need to reload.

**Screenshots**

<img width="1082" alt="Screen Shot 2022-12-06 at 18 51 40" src="https://user-images.githubusercontent.com/944286/205974887-e0603807-eb6f-4ae0-a14a-9ab3597b1cb3.png">
