### ISSUE TITLE
Custom-card-Apexcharts/Custom-card-camera not working when using multiple dashboard

### ISSUE THREAD

**Issue by scadra** [UI-Lovelace-Minimalist/UI#1133]
**Describe the bug**
The cards are working when using them into a dedicated dashboard: ui-lovelace.yaml. When trying to add 2 other dashboards : 
1. ui-lovelace_2.yaml
2. ui-lovelace_3.yaml

They are not working anymore and raise this issue : 

`hui-error-card TypeError: n.setConfig is not a function`

Which create an infinity loop and breaks the UI

1. Create a new Dashboard: ui-lovelace_2.yaml
2. Inside this file :
```
---
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "Server"
theme: "minimalist-desktop"
background: "var(--background-image)"
# views: !include_dir_merge_list "views/"
views:
  - !include views/server/server.yaml
```
3. Create the views into the dedicated folder and add the code : 
```
  - type: "vertical-stack"
    cards:
      - type: "custom:button-card"
        template: "card_title"
        name: "Consommation"
      - type: "custom:button-card"
        template: "custom_card_apexcharts"
        variables:
          chart_type: "radialBar"
          entity_1:
            entity_id: "sensor.processor_use"
            icon: "mdi:brain"
            name: "CPU"
            color: "green"
            max_value: 100
          entity_2:
            entity_id: "sensor.processor_temperature"
            icon: "mdi:thermometer"
            name: "TEMP"
            color: "blue"
            max_value: 100
          entity_3:
            entity_id: "sensor.memory_use_percent"
            icon: "mdi:memory"
            name: "RAM"
            color: "yellow"
            max_value: 100
    view_layout:
      grid-area: consumption
```
4. Register the dashboard like this : 
```
lovelace:
  mode: yaml
  # Add more dashboards
  dashboards:
    lovelace-minimalist-2: # Needs to contain a hyphen (-)
      mode: yaml
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace_2.yaml
      title: Server
      icon: mdi:database
      show_in_sidebar: true
      require_admin: false
```
5. See error by going into the dashboard

**Expected behavior**
I expect to have the card to work as it is for other cards
