### ISSUE TITLE
unit_of_measurement on Icon State Chip and Mdi:icon State Chip

### ISSUE THREAD

**Issue by nick03nick** [UI-Lovelace-Minimalist/UI#1134]
**Describe the bug**
I set 2 chips, Icon State Chip and Mdi:icon State Chip, with the same entity but the results are different on the label.
In case of Mdi:icon State Chip does not display the unit of measure but from the documentation it should show it.

The sensor is a **Shelly EM**.

This is the code I used:
```
- type: "custom:button-card"
  template: chip_mdi_icon_state
  variables:
    ulm_chip_mdi_icon_state_entity: sensor.misuratore_corrente_e_tensione_channel_1_power
    ulm_chip_mdi_icon_state_icon: mdi:flash
- type: "custom:button-card"
  template: chip_icon_state
  variables:
    ulm_chip_icon_state_icon: "⚡"
    ulm_chip_icon_state_entity: sensor.misuratore_corrente_e_tensione_channel_1_power
```

**Expected behavior**
**Icon State Chip** correctly displays the unit of measure
**Mdi:icon State Chip** correctly displays the unit of measure

**Screenshots**
From the code pasted above
- LEFT: Mdi:icon State Chip
- RIGHT: Icon State Chip

![Screenshot 2022-12-31 160754](https://user-images.githubusercontent.com/114882263/210141144-784775fe-0938-444c-997f-3fe2713d90ee.png)
