### ISSUE TITLE
Graph Card - ulm_card_graph_color - var(--color-XXX) dont work

### ISSUE THREAD

**Issue by ingeniumdesign** [UI-Lovelace-Minimalist/UI#1137]
**Describe the bug**
in the plugin [Graph Card](https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_graph/) the `ulm_card_graph_color` dont work with `var(--color-XXX)` => Example: `var(--color-green)`

Only the Google-Color work: `ulm_card_graph_color: "var(--google-blue)"`

**Example**

**Work fine:** 
```
      - type: 'custom:button-card'
        template: card_graph
        entity: sensor.test
        variables:
          ulm_card_graph_name: "Temp"
          ulm_card_graph_color: "var(--google-red)"
          ulm_card_graph_entity: sensor.test
```

**Dont work:**
```
      - type: 'custom:button-card'
        template: card_graph
        entity: sensor.test
        variables:
          ulm_card_graph_name: "Temp"
          ulm_card_graph_color: "var(--color-blue)"
          ulm_card_graph_entity: sensor.test
```

The Color is in the Themes Folder.
