### ISSUE TITLE
Popup in Adaptive mode not working

### ISSUE THREAD

**Issue by kadaan** [UI-Lovelace-Minimalist/UI#1160]
**Describe the bug**
Popups for the light card are not working in adaptive layout.  I want popups, but not the adaptive style

**To Reproduce**
1. Define a card:
```
  - view_layout:
      grid-area: "card2"
    type: horizontal-stack
    cards:
      - type: "custom:button-card"
        template: card_light
        entity: light.living_room
        variables:
          ulm_card_light_enable_slider: true
          ulm_card_light_enable_color: true
          ulm_card_light_force_background_color: true
          ulm_card_light_enable_collapse: true
          ulm_card_light_enable_popup: true
``` 
2. Configure custom actions:
```
---
ulm_custom_actions:
  variables:
    ulm_card_tap_action: "toggle"
    ulm_card_hold_action: "popup"
    ulm_card_double_tap_action: "popup"
    ulm_icon_tap_action: "toggle"
    ulm_icon_hold_action: "popup"
    ulm_icon_double_tap_action: "popup"
    ulm_name_tap_action: "toggle"
    ulm_name_hold_action: "popup"
    ulm_name_double_tap_action: "popup"
```
3. Press and hold on the icon
4. Popup does not open

**Expected behavior**
Popup should open, overlaying the UI, when in adaptive mode and action is popup.

**Additional context**
Version: v1.1.6-hotfix
