### ISSUE TITLE
Weather Radar Card option show_marker should be bool

### ISSUE THREAD

**Issue by Flolant** [UI-Lovelace-Minimalist/UI#1180]
**Describe the bug**
in the weather radar card the show_marker is not working.
there is no marker on the map displayed

**To Reproduce**
```
  - view_layout:
      grid-area: "weather"
    type: "custom:button-card"
    template: card_weather
    entity: weather.home
    variables:
      ulm_card_weather_name: " "
      ulm_card_tap_action: "popup"  
      ulm_custom_popup:
        template: "popup_weather_forecast"
        entity: weather.home
        popup_variables:
            ulm_weather_popup_surpress_first_forecast: false
```

**Expected behavior**
There should be an marker displayed on your location of HA

**Screenshots**
How it actually is:
![image](https://user-images.githubusercontent.com/103022070/219961096-899f97c5-7d28-47db-9126-c491a870d0ba.png)

How it should look:
![image](https://user-images.githubusercontent.com/103022070/219960868-534274a6-29c2-47d6-b2a7-f07ea6c058e4.png)

**How to Solve**
Go to File: custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/popup_templates/popups/popup_weather_forecast.yaml
at line 235 change: 
`show_marker: "true" `
to
`show_marker: true`

**Questions**
Can I override settings like that?
Because I also want to remove the "height: 350px !important;" a little below.
Because it is cutting off the options in the bottom.
This is usually not displayed:
![image](https://user-images.githubusercontent.com/103022070/219961431-2c369d40-c0a8-4d16-a16b-b713c485eaf9.png)

and I also want to change the map style to dark.
