### ISSUE TITLE
IT Language for custom card welcome

### ISSUE THREAD

**Issue by httpedo13** [UI-Lovelace-Minimalist/UI#119]
I would like to add the Italian language to the custom welcome card. 
And I suggest removing the "< br >" after the comma between "Good Morning" and "name".

```
ulm_custom_card_paddy_welcome_language_variables:
  variables:
    ulm_custom_card_paddy_welcome_morning: "Buongiorno"
    ulm_custom_card_paddy_welcome_afternoon: "Buon pomeriggio"
    ulm_custom_card_paddy_welcome_evening: "Buonasera"
    ulm_custom_card_paddy_welcome_hello: "Ciao"
```
