### ISSUE TITLE
Light Card color palette for Yeelight

### ISSUE THREAD

**Issue by fana13** [UI-Lovelace-Minimalist/UI#1202]
Hi,

Can we have a light_color_palette for Yeelight bulb please ?
Found in example this selector :
ulm_card_light_color_palette: select.wled_color_palette
Can we adapt this to yeelight color palette ?
Thanks

**Comment by basbruss** [comment]
Hi @fana13,

I don't own any Yeelights. Do you have some more info on the attributes, services, and entities that are accompanied by a Yeelight? Wled for example stores all palettes in a `select` entity.

**Comment by fana13** [comment]
Thanks for you reply @basbruss 

All attributes are here: 
```
min_color_temp_kelvin: 1700
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 588
effect_list: Strobe color, Police, Christmas, RGB, Random Loop, Fast Random Loop, LSD, Slowdown, Night Mode, Date Night, Movie, Sunrise, Sunset, Romance, Happy Birthday, Disco, Strobe epilepsy!, Alarm, Police2, WhatsApp, Facebook, Twitter, Home, Candle Flicker, Slow Temp, Stop
supported_color_modes: color_temp, hs, rgb
color_mode: color_temp
brightness: 204
color_temp_kelvin: 3205
color_temp: 312
hs_color: 27.518, 51.595
rgb_color: 255, 183, 123
xy_color: 0.478, 0.379
flowing: false
music_mode: false
friendly_name: Light
supported_features: 44
```

All services are here: 
```
yeelight.set_auto_delay_off_scene
yeelight.set_color_flow_scene
yeelight.set_color_scene
yeelight.set_color_temp_scene
yeelight.set_hsv_scene
yeelight.set_mode
yeelight.set_music_mode
yeelight.start_flow
```
Entities are only lights

**Comment by basbruss** [comment]
@fana13 

So you are already able to set the effect through the popup.
I can not see any list of available palettes in the details you have provided.
WLed for example exposes a list like this in the `select` entity:
```yaml
options: * Color 1, * Color Gradient, * Colors 1&2, * Colors Only, * Random Cycle, Analogous, April Night, Aqua Flash, Atlantica, Aurora, Aurora 2, Autumn, Beach, Beech, Blink Red, Breeze, C9, C9 2, C9 New, Candy, Candy2, Cloud, Cyane, Default, Departure, Drywet, Fairy Reaf, Fire, Forest, Grintage, Hult, Hult 64, Icefire, Jul, Landscape, Lava, Light Pink, Lite Light, Magenta, Magred, Ocean, Orange & Teal, Orangery, Party, Pastel, Pink Candy, Rainbow, Rainbow Bands, Red & Blue, Red Flash, Red Reaf, Red Shift, Red Tide, Retro Clown, Rewhi, Rivendell, Sakura, Semi Blue, Sherbet, Splash, Sunset, Sunset 2, Temperature, Tertiary, Tiamat, Toxy Reaf, Vintage, Yelblu, Yelblu Hot, Yellowout, Yelmag)
```

How do you normally set a palette to a Yeelight?
Is there any way to have a list in an entity (`input_select/select`) with color palettes, maybe coupled with an automation that calls a service based on that (input)select?

**Comment by fana13** [comment]
I tried this : 
```
       - type: "custom:button-card"
         template: 
           #- card_light
           #- popup_light
           - card_light_slider_collapse_color
         entity: light.yeelight_color_0x000000000800df30
         variables:
            ulm_card_light_enable_slider: true
            ulm_card_light_enable_color: true
            ulm_card_light_force_background_color: true 
            ulm_card_light_enable_popup: true
            ulm_card_light_color_palette: select.yeelight.set_mode
```

To display the palette, in lovelace classic dashboard : 
[https://i.imgur.com/NfC04xw.jpg](url)
[https://i.imgur.com/2iwbz9b.jpg](url)
[https://i.imgur.com/gyiysfx.jpg](url)
