### ISSUE TITLE
Uncaught RangeError when dealing with Timestamps

### ISSUE THREAD

**Issue by ellisdickinson46** [UI-Lovelace-Minimalist/UI#1217]
**Describe the bug**
When attempting to use a card with a timestamp entity instead of displaying the card it will error out with an uncaught RangeError exception.

**To Reproduce**
Steps to reproduce the behaviour:

* Create a ULM dashboard containing a generic card, in which the entity is a timestamp, e.g. Certificate Expiry:
  ```
  type: "custom:button-card"
  template: card_generic
  entity: sensor.cert_expiry_timestamp_[DOMAIN_HERE]
  variables:
    ulm_card_generic_name: "[DOMAIN NAME]"
  ```
* 

**Expected behaviour**
The card should present the timestamp

**Screenshots**

The error produced:
![CleanShot 2023-03-14 at 19 43 17@2x](https://user-images.githubusercontent.com/67054721/225119168-914743ce-0a82-41be-a87a-b9f8b2f21ea4.png)

**Additional context**
This issues seems to be directly related to a Pull Request for relative timestamps, introduced in 1.2.0 #1176. The issues can be temporarily resolved by manually using a file from before the pull request
