### ISSUE TITLE
Blue background after updating to the newest on darkmode. 

### ISSUE THREAD

**Issue by Unmoist** [UI-Lovelace-Minimalist/UI#1258]
After the update I get blue background on some cards, it's only in darkmode it's there. 
Anychance of this getting fixed?

**Comment by danideruiter** [comment]
Same problem here

**Comment by frank-fernandes** [comment]
Same problem here!
[](https://community-assets.home-assistant.io/optimized/4X/d/3/5/d3595668fa52c940bae117454d66a8cb3babd732_2_230x500.png)

**Comment by Brazier85** [comment]
I have the same issue. But in dark and light mode.

![Screenshot_20230410-091056.png](https://user-images.githubusercontent.com/1213924/230847713-e0dab558-47df-4672-be1f-38b9fe00fe36.png)

**Comment by basbruss** [comment]
> I have the same issue. But in dark and light mode.
> 
> ![Screenshot_20230410-091056.png](https://user-images.githubusercontent.com/1213924/230847713-e0dab558-47df-4672-be1f-38b9fe00fe36.png)

That is a weird one. By the looks of it, it's a custom card that uses a standard card as an inner template.
Is that the `custom_card_paddy_dwd_pollen`?

**Comment by Brazier85** [comment]
I have the same problem also here:

![image](https://user-images.githubusercontent.com/1213924/230923684-a5b63c0d-3bfd-40b1-b85c-753e7d816eb3.png)

```yaml
      - type: "custom:button-card"
        template: card_generic_swap
        entity: input_select.state_waschmaschine
        name: Waschmaschine
        variables:
          ulm_card_generic_swap_name: Waschmaschine
        custom_fields:
          item1:
            card:
              custom_fields:
                item1:
                  card:
                    state:
                      - value: "Fertig"
                        styles:
                          icon:
                            - color: green
                      - operator: default
                        styles:
                          icon:
                            - color: red
      - type: "custom:button-card"
        template: card_generic_swap
        entity: input_select.state_trockner
        name: Trockner
        variables:
          ulm_card_generic_swap_name: Trockner
        custom_fields:
          item1:
            card:
              custom_fields:
                item1:
                  card:
                    state:
                      - value: "Fertig"
                        styles:
                          icon:
                            - color: green
                      - operator: default
                        styles:
                          icon:
                            - color: red
```
