### ISSUE TITLE
ESH Welcome Card Weather Broken

### ISSUE THREAD

**Issue by damusmf** [UI-Lovelace-Minimalist/UI#1267]
**Describe the bug**
on the custom card ESH Welcome Card, the weather on the top does not load.  it is like it is not actually returning the ulm_weather variable so it fails to load.  

**To Reproduce**

1. Go to your screen with the esh welcome card
2. Click on the weather icon at the top
3. See error

**Expected behavior**
to pull up the more-info on the weather

**Screenshots**
![image](https://user-images.githubusercontent.com/31552122/230796736-96ad9f28-bf2c-4c07-9417-8b9638040149.png)
![image](https://user-images.githubusercontent.com/31552122/230796740-08b71332-19b5-421c-94eb-62782945c6a5.png)

**Additional context**
    
```
title: Home
path: home
cards:
  - type: "custom:button-card"
    template: "card_esh_welcome"
    triggers_update: "input_boolean.welcome_toggle"
    variables:
      ulm_card_esh_welcome_collapse: input_boolean.welcome_toggle
      ulm_weather: "weather.pirate_weather"
      entity_1:
        nav: "minimal_house"
        icon: "mdi:home"
        name: "House"
        color: "blue"
      entity_2:
        nav: "minimal_whatson"
        icon: "mdi:help"
        name: "Whats On"
        color: "yellow"
      entity_3:
        nav: "minimal_security"
        icon: "mdi:shield"
        name: Security
        color: "green"
      entity_4:
        nav: "minimal_media"
        icon: "mdi:music"
        name: Media
        color: "purple"
      entity_5:
        nav: "minimal_everything"
        icon: "mdi:cog"
        name: Everything
        color: "red"
```

**Comment by basbruss** [comment]
The error is not related to Minimalist from what I can tell by reading the error message but to the weather entity/integration that doesn't has an unique_id.

**Comment by damusmf** [comment]
> The error is not related to Minimalist from what I can tell by reading the error message but to the weather entity/integration that doesn't has an unique_id.

Well right, but the entity it is referring to in the error that doesnt have the unique ID is `'[[[ return variables.ulm_weather]]]'` 
Which won't have a unique ID as it is not even a real entity.  i believe the problem is that it is not actually passing the stated entity ID through to the template and that is why it is not working.

**Comment by basbruss** [comment]
Okay, what version are you running of both the card and ULM?

As with everything up-to-date I am not able to reproduce the problem..

**Comment by elykrk** [comment]
I'm having the same issue with pirate weather except I am on: 
HomeAssistant 2023.4.6
ULM Version 1.3.4-hotfix
Same card version copied directly from the link above.

**Comment by BobbieERay** [comment]
Same issue
Home Assistant 2023.6.2
ULM Version 1.3.6
Same card version copied directly from the link above.

**Comment by BobbieERay** [comment]
Fixed for me. Opened `custom_card_esh_welcome.yaml` and added the line `entity: "[[[ return variables.ulm_weather]]]"`  to `item 2` in the `card_esh_welcome_topbar` definition. (line 439)

```YAML
    item2:
      card:
        type: "custom:button-card"
        template: "chip_weather_date"
        entity: "[[[ return variables.ulm_weather]]]"
        variables:
          ulm_weather: "[[[ return variables.ulm_weather]]]"
        tap_action:
          action: "more-info"
        styles:
          card:
            - width: "100px"
```

I looked at the [source code in the repository](https://github.com/UI-Lovelace-Minimalist/UI/blob/main/custom_cards/custom_card_esh_welcome/custom_card_esh_welcome.yaml) and it appears to be included now (line 443). So I don't know whether this is a recent change, or whether I picked up an older version somehow.
