### ISSUE TITLE
Documentation format is outdated and confusing

### ISSUE THREAD

**Issue by thomasloven** [UI-Lovelace-Minimalist/UI#1280]
**Is your enhancement request related to a problem? Please describe.**
Several of the pages in the documentation present example configurations for lists of cards rather than cards,
E.g.
https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_wsly_pollen/#usage

**Describe the solution you'd like**
The best way to present this now that dashboard configuration is mainly GUI-based is:

```yaml
type: 'custom:button-card'
template: custom_card_wsly_pollen
variables:
  custom_card_wsly_pollen_tree: sensor.tomorrow_io_home_tree_pollen_index
  custom_card_wsly_pollen_grass: sensor.tomorrow_io_home_grass_pollen_index
  custom_card_wsly_pollen_weed: sensor.tomorrow_io_home_weed_pollen_index
```

I.e the configuration for a single card rather than the configuration of a list of one cards.

**Describe alternatives you've considered**
-

**Additional context**
I have not looked through all cards in the documentation, but I assume this applies to several.
