### ISSUE TITLE
Custom card "Person"-Pop Up not working

### ISSUE THREAD

**Issue by JueK3y-Prv** [UI-Lovelace-Minimalist/UI#1288]
*Affected part*
Custom card "Person" by Imswel

*Bug description*
The Popup function for Imswel's Person Card doesn't seem to work.

The person card is displayed to me, but nothing happens when I click onto it.
Neither long pressing on it nor double pressing does anything. However, the popup does work in principle, for example with the normal person card.

*Configuration*
This is my configuration:
```
  - type: "custom:button-card"
    template: custom_card_imswel_person
    entity: person.julian
    variables:
      ulm_card_imswel_person_entity: person.julian
      ulm_card_imswel_person_wifi_tracker: device_tracker.juice_pixel
      ulm_card_imswel_person_gps_tracker: sensor.juice_pixel_geocoded_location
      ulm_card_imswel_person_findmy_script: script.find_juice_pixel
      ulm_card_imswel_person_use_entity_picture: true
```
