### ISSUE TITLE
Add confirmation 

### ISSUE THREAD

**Issue by Bastiencc** [UI-Lovelace-Minimalist/UI#1289]
Hi

Is it possible to add confirmation dialog box before running the action like it is available in button card ? 
Doc : https://github.com/custom-cards/button-card#confirmation

```
confirmation:
  text: '[[[ return `Are you sure you want to toggle ${entity.attributes.friendly_name}?` ]]]'
  exemptions:
    - user: befc8496799848bda1824f2a8111e30a
```

Thanks !
