### ISSUE TITLE
Wrong variable name

### ISSUE THREAD

**Issue by schumijo** [UI-Lovelace-Minimalist/UI#13]
Hi,

There is a typo with variable names in templates "card_light_slider_collapse" and "card_light_slider_horizontal"

```
card_light_slider_collapse:
  variables:
    ulm_card_light_slider_collapse_name: "[[[ return entity.attributes.friendly_name ]]]"
(...)
  custom_fields:
    item1:
      card:
        type: 'custom:button-card'
        template:
          - icon_info
          - light
        entity: "[[[ return entity.entity_id ]]]"
        name: "[[[ return variables.ulm_card_light_slider_name ]]]"  <==== Should be ulm_card_light_slider_collapse_name
```

```
card_light_slider_horizontal:
  variables:
    ulm_card_light_slider_horizontal_name: "[[[ return entity.attributes.friendly_name ]]]"
(...)
  custom_fields:
    item1:
      card:
        type: 'custom:button-card'
        template:
          - icon_info
          - light
        entity: "[[[ return entity.entity_id ]]]"
        name: "[[[ return variables.ulm_card_light_slider_name ]]]"  <==== Should be ulm_card_light_slider_horizontal_name
```
