### ISSUE TITLE
Zone name not shown correctly in Person Card and Person Info card

### ISSUE THREAD

**Issue by japyjaap** [UI-Lovelace-Minimalist/UI#1307]
I've been using the custom Person Info Card for a while in my dashboard. I'm not exactly sure when it happened but the zone name doesn't show the Friendly name as defined in zones.

Since the standard Mushroom card shows the zone name correctly (Thuis), the problem probably is related to Minimalist-UI. As you can see there even is a difference between the person and person info card within UI Lovelace minimalist.

The image below shows the person card, person info card and the mushroom person card.

![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/6353034/abc543cf-8eab-41f8-adf8-179e6f230911)

```
  - view_layout:
      grid-area: "card11"
    type: vertical-stack
    cards:    
      - type: 'custom:button-card'
        template: card_person
        entity: person.jaaap
        variables:
          ulm_card_person_entity: person.jaap
          ulm_card_person_use_entity_picture: false
          ulm_card_person_battery: sensor.iphone_van_jaap_home_assistant_battery_level
          ulm_card_person_eta: sensor.jaap_iphone_travel_time
      - type: "custom:button-card"
        template: card_person_info
        variables:
          ulm_card_person_entity: person.jaap
          ulm_card_person_use_entity_picture: false
          ulm_multiline: true
          ulm_card_person_driving_entity: input_boolean.jaap_driving_flag
          ulm_card_person_commute_entity: sensor.jaap_iphone_travel_time
          ulm_card_person_commute_icon: mdi:car
          ulm_card_person_battery_entity: sensor.iphone_van_jaap_home_assistant_battery_level
          ulm_card_person_battery_state_entity: sensor.iphone_van_jaap_home_assistant_state
      - type: custom:mushroom-person-card
        entity: person.jaap
        fill_container: false
```
