### ISSUE TITLE
Room Card Issue

### ISSUE THREAD

**Issue by andyblac** [UI-Lovelace-Minimalist/UI#1309]
When not using Entities 1 or 2, the full wid th of the button is not available to the Label unlike the Title.

**Steps to reproduce the behaviour:**
using code:
```
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template:
                  - card_room
                  - green_no_state
                name: Front Garden
                icon: mdi:flower
                label: '[[[ return states["sensor.front_garden_motion_sensor_temperature"].state + "°C | " + states["sensor.front_garden_soil_sensor_humidity"].state + "%" ]]]'
                tap_action:
                  action: navigate
                  navigation_path: "/ui-lovelace-minimalist/front-garden"
                variables:
                  entity_3:
                    entity_id: light.front_garden_light
                    templates:
                      - yellow_on
                    tap_action:
                      action: toggle
              - type: "custom:button-card"
                template:
                  - card_room
                  - green_no_state
                name: Back Garden outside
                icon: mdi:flower-tulip
                label: "This is a test label"
                tap_action:
                  action: navigate
                  navigation_path: "/ui-lovelace-minimalist/back-garden"
                variables:
                  entity_3:
                    entity_id: light.garage_wall_light
                    templates:
                      - yellow_on
                    tap_action:
                      action: toggle
                  entity_4:
                    entity_id: light.back_garden_raised_bed_led
                    templates:
                      - yellow_on
                    tap_action:
                      action: toggle
```

**Expected behaviour**
You see the see the full label "This is a test label

**Screenshots**
this is what you see
<img width="512" alt="Screenshot 2023-05-29 at 15 43 55" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/77936/aae2703c-1990-41f8-adef-f5c9abf9e364">
