### ISSUE TITLE
iOS and `max-width` not working

### ISSUE THREAD

**Issue by TomHart** [UI-Lovelace-Minimalist/UI#1322]
**Describe the bug**
On my wife's iPhone X, the dashboard I created doesn't show the mobile version, it shows the desktop one. Mobile style works fine on my Android, or browser if resizes small enough

**To Reproduce**
The card is:
```
---
type: "custom:layout-card"
layout_type: "custom:grid-layout"
layout:
  # Tablet portrait
  grid-template-columns: "repeat(6, 1fr)"
  mediaquery:
    # Mobile
    "(max-width: 1200px)":
      grid-template-columns: "1fr"
cards:
  // includes other YAML files 
  
```

**Expected behavior**
Columns to be in a vertical line

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/1374434/db05a966-3ffd-4fc5-9b27-d15198419f5f)

**Additional context**
For the title I'm using JS to get the browser width, in case that was the problem, but you can see it should be small enough

Code for reference
```
title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: "var(--background-image)"
views:
  - title: "Overview"
    path: overview
    icon: "mdi:home"
    type: "custom:grid-layout"
    cards:
      - type: "custom:button-card"
        template: "card_title"
        name: |-
          [[[ 
            return "Rooms JS. " + document.body.offsetWidth;
          ]]]
      - !include "views/rooms.yaml" # This is the file from above
```
