### ISSUE TITLE
assist action not working

### ISSUE THREAD

**Issue by albinmedoc** [UI-Lovelace-Minimalist/UI#1329]
**Describe the bug**
Nothing happens when I setup a card with assist as a tap-action. 

**To Reproduce**

1. Configure a card to use the assist action
```
tap_action:
    action: assist
    pipeline_id: 01gzhrn7tecthmye4a80kj3qd1
    start_listening: true 
```
2. Reload UI Minimalst configuration
3. Navigate to dashboard and reload
4. Click the card
5. See nothing

**Expected behavior**
The assist dialog to open when I click the button.
