### ISSUE TITLE
Call-service custom action not working for name action

### ISSUE THREAD

**Issue by tobias-groeger** [UI-Lovelace-Minimalist/UI#1340]
**Describe the bug**
When the custom action for holding the name is set to `call-service` the service data is not set properly.

**To Reproduce**

1. Add a `card_generic` to your dashboard
2. Pick `call-service` as action for `ulm_name_hold_action`
3. Set service and entity for that service
4. When name part of the card is held, an error is produced:
    `Failed to call service timer/start. must contain at least one of entity_id, device_id, area_id.`

```yaml
- type: 'custom:button-card'
  template: card_generic
  entity: <entity>
  variables:
    ulm_name_hold_action: "call-service"
    ulm_name_hold_service: <some-service>
    ulm_name_hold_service_data:
      entity_id: <entity>
```

See [documentation for custom actions](https://ui-lovelace-minimalist.github.io/UI/setup/custom_actions/#call-service-action).

**Expected behavior**
The given entity id is used as data of the service.
