### ISSUE TITLE
Custom_card_camera crashes iOS app

### ISSUE THREAD

**Issue by norimicry** [UI-Lovelace-Minimalist/UI#1371]
**Describe the bug**
When using the custom_card_camera custom card, when navigating to that page on the iOS app, the app stops loading, closes the dashboard, then reloads a blank screen. I tried this on a navigation page as well as the home screen and both cause the same effect. Wonder if this could be related to a "custom entity not found: picture-entity" issue that keeps appearing randomly. As is, this card is unusable for me.

**To Reproduce**

1. Follow instructions to install custom_card_camera through documentation
2. Implement usage on dashboard
3. App refuses to load

**Expected behavior**
To load a feed of my camera.

**Screenshots**
![67B938FE-EE82-4B23-8D57-3990007700B8_1_102_o](https://github.com/UI-Lovelace-Minimalist/UI/assets/46500116/c4b39c94-a8ef-42cb-ac9d-6c2f3f304f34)

<img width="309" alt="image" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/46500116/d2f508ec-7283-48c1-b2dd-a82b77614431">

**Additional context**
custom_card_camera.yaml
```
---
custom_card_camera:
  template:
    - "blue_no_state"
  show_name: false
  show_label: false
  styles:
    card:
      - border-radius: "20px"
      - box-shadow: "var(--box-shadow)"
      - padding: |-
          [[[
            if(variables.ulm_custom_card_camera_title)
              return "12px";
            else
              return "0px";
          ]]]
    img_cell:
      - border-radius: "50%"
      - place-self: "center"
      - width: "42px"
      - height: "42px"
    grid:
      - grid-template-areas: "'i item1' 'i item1' 'item2 item2'"
      - grid-template-columns: "min-content auto"
      - grid-template-rows: "min-content min-content min-content"
      - row-gap: |-
          [[[
            if(variables.ulm_custom_card_camera_title)
              return "12px";
            else
              return "0px";
          ]]]
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        show_name: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        show_label: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        show_icon: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        name: "[[[ return variables.ulm_custom_card_camera_name; ]]]"
        label: "[[[ return variables.ulm_custom_card_camera_label; ]]]"
        tap_action:
          action: "more-info"
          entity: "[[[ return entity.entity_id ]]]"
        styles:
          card:
            - box-shadow: "none"
            - padding: "0"
            - --mdc-ripple-press-opacity: 0
          name:
            - align-self: "end"
            - justify-self: "start"
            - font-weight: "bold"
            - font-size: "14px"
            - margin-left: "12px"
            - filter: "opacity(100%)"
          label:
            - justify-self: "start"
            - align-self: "start"
            - font-weight: "bolder"
            - font-size: "12px"
            - filter: "opacity(40%)"
            - margin-left: "12px"
          grid:
            - grid-template-areas: "'n' 'l'"
            - grid-template-columns: "auto"
            - grid-template-rows: "min-content min-content"
    item2:
      card:
        camera_image: "[[[ return entity.entity_id ]]]"
        camera_view: "live"
        entity: "[[[ return entity.entity_id ]]]"
        type: picture-entity
        show_name: false
        show_state: false
        aspect_ratio: "[[[ return variables.ulm_custom_card_camera_aspect_ratio; ]]]"
  tap_action:
    action: "more-info"
```

Implementation
```
- type: "custom:button-card"
    entity: "camera.doorbell"
    template: "custom_card_camera"
    show_icon: true #True if you set ulm_custom_card_camera_title: true
    variables:
      ulm_custom_card_camera_title: true
      ulm_custom_card_camera_name: "Doorbell"
      ulm_custom_card_camera_aspect_ratio: '16:9'
```
