### ISSUE TITLE
custom_card_esh_room hight broken when mixing english and japanese characters

### ISSUE THREAD

**Issue by BPplays** [UI-Lovelace-Minimalist/UI#1385]
**Describe the bug**
custom_card_esh_room has broken vertical size when you have a card with just english and a card with japanese text side by side they are not the same hight.

they are also differently broken on my phone they are still not the same size but they are closer in hight

**Expected behavior**
i expected the cards to all be the same hight

**Screenshots**
![pic](https://raw.githubusercontent.com/BPplays/images/main/Screenshot_2023-10-12_081053.png)

**To Reproduce**
use this:
```yaml
- title: "test"
  path: "test"
  cards:
    - type: vertical-stack
      cards:
        #
        #
        #
        #
        #
        #
        - type: "custom:button-card"
          template: card_title
          name: Rooms
          # label: "Subtitle"
        #
        #
        # Rooms
        - type: horizontal-stack
          cards:
            ##### test room
            - type: "custom:button-card"
              template:
                - card_esh_room
                - yellow_on
              name: 日本語
              label: '[[[ return "Status: " + "placeholder" ]]]'
              # name: Server Room
              # label: '[[[ return "Status: " + "placeholder" ]]]'
              color: "var(--google-grey-500)"
              # entity: light.bathroom_lights
              icon: mdi:bed
              tap_action:
                action: navigate
                navigation_path: "test-room"
              variables:
                ulm_custom_card_esh_room_light_entity: light.test_lights
                ulm_card_dynamic_color: false
                ulm_card_light_enable_popup: false
                # ulm_custom_card_esh_room_climate_entity: climate.bathroom
              # label: '[[[ return states["sensor.room_temperature"].state + "°C" ]]]'
            #
            #
            #
            #
            #
            #
            #server
            - type: "custom:button-card"
              template:
                - card_esh_room
                - yellow_on
              name: Server Room
              label: '[[[ return "Status: " + "placeholder" ]]]'
              color: "var(--google-grey-500)"
              # entity: light.bathroom_lights
              icon: mdi:server
              tap_action:
                action: navigate
                navigation_path: "server-room"
              variables:
                # ulm_custom_card_esh_room_light_entity: light.test_lights
                ulm_card_dynamic_color: false
                ulm_card_light_enable_popup: false
                # ulm_custom_card_esh_room_climate_entity: climate.bathroom
              # label: '[[[ return states["sensor.room_temperature"].state + "°C" ]]]'

        - type: horizontal-stack
          cards:
            ##### test room
            - type: "custom:button-card"
              template:
                - card_esh_room
                - yellow_on
              name: にほんご
              label: '[[[ return "Status: " + "placeholder" ]]]'
              # name: Server Room
              # label: '[[[ return "Status: " + "placeholder" ]]]'
              color: "var(--google-grey-500)"
              # entity: light.bathroom_lights
              icon: mdi:bed
              tap_action:
                action: navigate
                navigation_path: "test-room"
              variables:
                ulm_custom_card_esh_room_light_entity: light.test_lights
                ulm_card_dynamic_color: false
                ulm_card_light_enable_popup: false
                # ulm_custom_card_esh_room_climate_entity: climate.bathroom
              # label: '[[[ return states["sensor.room_temperature"].state + "°C" ]]]'
            #
            #
            #
            #
            #
            #
            #server
            - type: "custom:button-card"
              template:
                - card_esh_room
                - yellow_on
              name: Server Room
              label: '[[[ return "Status: " + "placeholder" ]]]'
              color: "var(--google-grey-500)"
              # entity: light.bathroom_lights
              icon: mdi:server
              tap_action:
                action: navigate
                navigation_path: "server-room"
              variables:
                # ulm_custom_card_esh_room_light_entity: light.test_lights
                ulm_card_dynamic_color: false
                ulm_card_light_enable_popup: false
                # ulm_custom_card_esh_room_climate_entity: climate.bathroom
              # label: '[[[ return states["sensor.room_temperature"].state + "°C" ]]]'

```
