### ISSUE TITLE
For custom_card_esh_room, I would like to be able to use a group as an entity.

### ISSUE THREAD

**Issue by PatrickHennecke** [UI-Lovelace-Minimalist/UI#1391]
**Is your enhancement request related to a problem? Please describe.**
For custom_card_esh_room, is it possible to use a group as an entity? 

**Describe the solution you'd like**
For example, if I group all the lights in a room together. I would like to be able to add that group as the entity to control.

**Describe alternatives you've considered**
N/A - I've tried doing it, it doesn't work. Although, I am stupid, maybe it should work and I messed it up.

**Additional context**
```
- type: "custom:button-card"
  template:
    - card_esh_room
    - yellow_on
  name: Bathroom
  entity: light.group_of_lights_HERE
  icon: mdi:bathtub
  tap_action:
    action: navigate
    navigation_path: "bathroom"
  variables:
    ulm_custom_card_esh_room_light_entity: light.bathroom_lights
    ulm_custom_card_esh_room_climate_entity: climate.bathroom
  label: '[[[ return states["sensor.room_temperature"].state + "°C" ]]]'
```
