### ISSUE TITLE
Greeting is not hidden when disabled in homeView options

### ISSUE THREAD

**Issue by gottsman** [UI-Lovelace-Minimalist/UI#1401]
**Describe the bug**
I have tried to disable the greeting message at the top of the interface. Adding the hidden option seems to have no affect on visibility

**To Reproduce**
Here is my current config:
```
strategy:
  type: custom:mushroom-strategy
  options:
    homeView:
      hidden:
        - Greeting
    chips:
      climate_count: false
      cover_count: false
views: []
```

**Expected behavior**
Expected to see a simpler interface without the greeting message

**Screenshots**
![minimalist greeting](https://github.com/UI-Lovelace-Minimalist/UI/assets/6173136/23772cd5-e396-457b-b7a0-ca8cb17ed408)

**Additional context**
