### ISSUE TITLE
Scenes Card bug - pressing not working properly

### ISSUE THREAD

**Issue by zuohaot** [UI-Lovelace-Minimalist/UI#1413]
**Describe the bug**
Pressing text and icon gives errors. It works properly only when I press the middle gap between icon and text
When I press icon, it gives "
When I press text, it gives "Failed to call service [[[ if(typeof(entity) !== 'undefined' && entity !== undefined){ if(entity/entity_id. Service not found."

**To Reproduce**

**Expected behavior**
Supposed to work in the same way as Welcome Scene Card

**Additional context**

**Related Logs** (can be found in the browser-console (F12))
Add related logs for the problem

**Related Card Config**
Add the card config from `ui-lovelace.yaml` with the related problem
```yaml
- view_layout:
      grid-area: "scene"
  type: "custom:button-card"
  template: "card_scenes_welcome"
  variables:
    entity_1:
      entity_id: "input_boolean.welcome"
      icon: "mdi:home" #OPTIONAL
      name: "Welcome" #OPTIONAL
      color: "blue"
    entity_2:
      entity_id: "<YOUR_ENTITY>"
      icon: "mdi:YOUR_ICON" #OPTIONAL
      name: "YOUR_NAME" #OPTIONAL
      color: "red"
    entity_3:
      entity_id: "<YOUR_ENTITY>"
      icon: "mdi:YOUR_ICON" #OPTIONAL
      name: "YOUR_NAME" #OPTIONAL
      color: "green"
    entity_4:
      entity_id: "<YOUR_ENTITY>"
      icon: "mdi:YOUR_ICON" #OPTIONAL
      name: "YOUR_NAME" #OPTIONAL
      color: "purple"
    entity_5:
      entity_id: "<YOUR_ENTITY>"
      icon: "mdi:YOUR_ICON" #OPTIONAL
      name: "YOUR_NAME" #OPTIONAL
      color: "yellow"
    entity_6:
      entity_id: "<YOUR_ENTITY>"
      icon: "mdi:YOUR_ICON" #OPTIONAL
      name: "YOUR_NAME" #OPTIONAL
      color: "pink"
    entity_7:
      entity_id: "<YOUR_ENTITY>"
      icon: "mdi:YOUR_ICON" #OPTIONAL
      name: "YOUR_NAME" #OPTIONAL
      color: "yellow"`
```
