### ISSUE TITLE
custom_card_esh_room discolouration when using ulm_custom_card_esh_room_light_entity

### ISSUE THREAD

**Issue by otfrancis1** [UI-Lovelace-Minimalist/UI#1419]
**Describe the bug**
when using this card with no variables set the background colour is a bright white. When you add ulm_custom_card_esh_room_light_entity it changes the colour to a slightly darker white when the light is on and returns to its original colour when the light is off

**To Reproduce**
use this config and turn the light on and off
```
   - type: "custom:button-card"
        template:
          - card_esh_room
          - blue_no_state
        name: Oliver's Office
        icon: mdi:desk
        tap_action:
          action: navigate
          navigation_path: "oliversoffice"
        variables:
          ulm_custom_card_esh_room_light_entity: light.shelly_light_olivers_office
        label: >
          [[[
            return "🌡️ " + states['sensor.oliver_s_office_temperature'].state + " °C" + " 💧 " + states['sensor.oliver_s_office_humidity'].state + " %"
          ]]]
      - type: "custom:button-card"
        template:
          - card_esh_room
          - blue_no_state
        name: Heathers's Office
        icon: mdi:desk
        tap_action:
          action: navigate
          navigation_path: "heathersoffice"
        variables:
        label: >
          [[[
            return "🌡️ " + states['sensor.heather_s_office_temperature'].state + " °C" + " 💧 " + states['sensor.heather_s_office_humidity'].state + " %"
          ]]]
```

**Expected behavior**
both cards should be the same colour at all times

**Screenshots**
Light on:
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/106662176/ad861ef6-b588-49df-b409-36dd96753cb8)
Light off:
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/106662176/c35e5a0b-250e-4b0e-bd83-aadd68f4d5ee)
