### ISSUE TITLE
custom_card_bar_card is aligned wrong

### ISSUE THREAD

**Issue by Switchbot-Nova** [UI-Lovelace-Minimalist/UI#1440]
**Describe the bug**
After adding the custom bar card this is what I see
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/76595469/18007bc5-a27f-4ac6-966f-889499334deb)

**To Reproduce**

1. Go to your room.yaml
2. Add the config I noted below in the issue
3. Go to dashboard, refresh

**Expected behavior**
![screenshot_bar_card](https://github.com/UI-Lovelace-Minimalist/UI/assets/76595469/84808237-bddf-459c-82bf-2c5eec2e4822)

**Related Card Config**
```yaml
- type: horizontal-stack
    cards:
      - type: "custom:button-card"
        template: custom_card_bar_card
        variables:
          ulm_custom_card_bar_card_entity: sensor.system_monitor_processor_use
          ulm_custom_card_bar_card_name: CPU Usage
      - type: "custom:button-card"
        template: custom_card_bar_card
        variables:
          ulm_custom_card_bar_card_entity: sensor.system_monitor_memory_use
          ulm_custom_card_bar_card_name: Memory Usage
```
