### ISSUE TITLE
Room card not displaying icons  HA Core 2024.2.0

### ISSUE THREAD

**Issue by milouzzzz** [UI-Lovelace-Minimalist/UI#1454]
**Describe the bug**
After updating to HA core 2024.2.0 all entity icons in the custom fileds doesn't display anymore.

**To Reproduce**

1. Add room card to a view
2. add entities in "item1" "item2" etc..
3. See error

**Expected behavior**
Icon should be displayed

**Screenshots**
![Capture](https://github.com/UI-Lovelace-Minimalist/UI/assets/63913196/1679fe8f-59a3-4edd-9cd9-b56cb01efa10)

```yaml
                - type: 'custom:button-card'
                  template:
                    - card_room
                    - yellow_on
                    - grey_off
                  name: Entrée
                  label: '[[[ return states["sensor.fibaro_door_window_sensor_2_air_temperature"].state +"°C"]]]'
                  entity: light.interrupteur_entree
                  icon: mdi:door  
                  tap_action:
                    action: navigate
                    navigation_path: '/ui-lovelace-minimalist/entree'
                  variables:
                    label_use_temperature: false
                    label_use_brightness: true
                    entity_1:
                      entity_id: light.interrupteur_entree
                      templates:
                        - yellow_on                      
                      tap_action:
                        action: toggle
                    entity_2:
                      entity_id: light.interrupteur_peron
                      templates:
                        - yellow_on
                      tap_action:
                        action: toggle
                    entity_3:
                      entity_id: binary_sensor.fibaro_door_window_sensor_2_window_door_is_open
                      templates:
                        - green_on
                        - red_off
                      tap_action:
                        action: more-info              
                    entity_4:
                      entity_id: camera.sonnette
                      templates:
                        - green_on
                        - red_off
                      tap_action:
                        action: more-info
```
