### ISSUE TITLE
After updating to newest version basic cards stopped working

### ISSUE THREAD

**Issue by Ky0sHiR00** [UI-Lovelace-Minimalist/UI#1456]
**Describe the bug**
After update from 1.3.6 do 1.3.9 version basic cards like card_light, card_cover, card_power_outlet stopped working (showing).
After going to backup everything is working as expected. 

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/96185637/a8ab2fb6-6d6d-49f7-98b9-0dd212ec6a53)
For example - graph is working but it's not displaying title

After update:
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/96185637/45be6a63-85a5-402b-b8ef-07dbaff49da2)

Before update:
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/96185637/45a955d5-7282-427d-bc48-c5ba7b989295)

**Related Card Config**
Add the card config from `ui-lovelace.yaml` with the related problem

```yaml
- type: horizontal-stack
  cards:
    - type: "custom:button-card"
      template: card_light
      variables:
        ulm_card_light_slider_collapse_name: Lampa
      entity: light.salon
- type: horizontal-stack
  cards:
    - type: "custom:button-card"
      template: card_power_outlet
      variables:
        ulm_card_power_outlet_consumption_sensor: sensor.0x4cf8cdf3c8a239f_power
      entity: switch.0x4cf8cdf3c8a239f_switch
      name: Xbox & TV
    - type: "custom:button-card"
      template: card_power_outlet
      variables:
        ulm_card_power_outlet_consumption_sensor: sensor.wentylator_power
      entity: switch.wentylator
      name: Wentylator
- type: horizontal-stack
  cards:
    - type: custom:button-card
      template: custom_card_mpse_thermostat
      entity: climate.midea_ac
      variables:
        power: sensor.0x04cf8cdf3c7c3238_power
```
