### ISSUE TITLE
Etrim is not a function

### ISSUE THREAD

**Issue by seanm581** [UI-Lovelace-Minimalist/UI#1460]
Binary Sensor Cards are still not working. 

re: this issue bug 
https://github.com/UI-Lovelace-Minimalist/UI/issues/1394

**Comment by tieskuh** [comment]
I have the same issue with a binary_sensor card. 

This is the yaml:

```
- type: 'custom:button-card'
    template: card_binary_sensor
    triggers_update: all
    variables:
      ulm_card_binary_sensor_alert: true
      ulm_show_last_changed: true
      ulm_card_binary_sensor_name: 'Laatste keer aangebeld'
      ulm_card_binary_sensor_icon: mdi:bell
    entity: binary_sensor.deurbel_input
```

It shows up like this:
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/115901851/803f0adc-95c4-4e05-a19d-518ad8ff3f24)

I was thinking: It might also be a button_card bug as show_last_changed is a button_card function and not a minimalist function as far as I know.
