### ISSUE TITLE
The card_media_player's volume slider color is always black.

### ISSUE THREAD

**Issue by Ssiswent** [UI-Lovelace-Minimalist/UI#1465]
**Describe the bug**
The card_media_player's volume slider color is always black.
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/37449310/a87fa4d1-14d0-40ce-a218-2b3c312a2328)

**Expected behavior**
Volume slider color should be transparent like controllers and this Demo.
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/37449310/73c46ad2-4cd9-49f5-9293-9ea84788c06d)

**Additional context**
Maybe these two have some conflicts:
```yaml
ulm_card_media_player_enable_art: true
ulm_card_media_player_enable_volume_slider: true
```

**Related Card Config**

```yaml
- type: "custom:button-card"
        template:
          - card_media_player
        entity: media_player.bedroom
        variables:
          ulm_card_media_player_enable_popup: true
          ulm_card_media_player_name: HomePod mini
          ulm_card_media_player_enable_art: true
          ulm_card_media_player_enable_controls: true
          ulm_card_media_player_enable_volume_slider: true
          ulm_card_media_player_enable_volume_buttons: true
          ulm_card_media_player_more_info: true
```
