### ISSUE TITLE
Weather Popup doesn't work with Germany DWD Weather Integration

### ISSUE THREAD

**Issue by idominiki** [UI-Lovelace-Minimalist/UI#1466]
H guys!

The Weather Popup doesn't work with weather data for Germany via DWD Integration (https://github.com/FL550/dwd_weather) as well as (https://github.com/hg1337/homeassistant-dwd).

Error:
![Bildschirmfoto 2024-02-27 um 14 10 26](https://github.com/UI-Lovelace-Minimalist/UI/assets/62521486/93e5cbdf-f4ac-48a1-9187-f7bed86b4575)

Code for the card:
```
# Weather Chip
          - type: "custom:button-card"
            template: custom_chip_temperature
            variables:
              ulm_chip_temperature_inside: sensor.wetterstation_luftfeuchtigkeit
              ulm_chip_temperature_outside: sensor.wetterstation_temperatur
              ulm_chip_temperature_weather: weather.soest
              ulm_custom_popup:
                template: "popup_weather_forecast"
                entity: weather.soest
                popup_variables:
                  ulm_weather_popup_surpress_first_forecast: false
            tap_action:
              action: navigate
              navigation_path: /adaptive-dash/wetter
            triggers_update: all
            # Bugs: https://github.com/bramkragten/swipe-card/issues/51
            card_mod:
              style: |
                ha-card {
                  margin-bottom:2px;
                }
``` 

Has anyone a tipp for me how to get this working again?

Thanks
Dominik
