### ISSUE TITLE
custom_card_paddy_waste_collection entity name based on sensor attribute on Dashboard?

### ISSUE THREAD

**Issue by Herri17** [UI-Lovelace-Minimalist/UI#1467]
**Is your enhancement request related to a problem? Please describe.**

Is it possible to set the entity name on the dashboard of a custom_card_paddy_waste_collection based on an attribute of a sensor?

Currently you define a name for the entity which is shown in the dashboard.

<img width="572" alt="Bildschirmfoto 2024-02-27 um 19 03 29" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/95345587/a644a2ab-d89c-418d-b21a-3f1f3dbbbcaf">

But instead I would like to have the option, that the Name shows an attribute of a sensor (in this case the "message" attribute of the calendar entity of the waste collection framework)

<img width="1024" alt="Bildschirmfoto 2024-02-27 um 19 00 58" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/95345587/4f6530f7-7135-4e37-b671-66cb020ada75">

This would be because it would be minimalistic ;-) and will only show the next waste type and the days until it will be collected.

**Describe the solution you'd like**

Is it possible to get a variable which will set the shown name on the dashboard based on the mentioned value?

**Describe alternatives you've considered**

I tried to set the custom name with a template, but it seams that the input will be converted in a string

In my case it is the template
`{{states.calendar.awigo_abfallwirtschaft_landkreis_osnabruck_gmbh_2.attributes.message}}`

<img width="1288" alt="Bildschirmfoto 2024-02-27 um 19 19 55" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/95345587/a653bfe2-7ba6-4b0a-aeef-01dec1f5829b">

<img width="563" alt="Bildschirmfoto 2024-02-27 um 19 22 00" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/95345587/8b76449d-39cd-4acc-94af-f3be8a103757">

My dashboard code:
```
- type: custom:button-card
      template:
        - custom_card_paddy_waste_collection
      entity: sensor.awigo
      variables:
        ulm_card_generic_swap_name: >-
          {{states.calendar.awigo_abfallwirtschaft_landkreis_osnabruck_gmbh_2.attributes.message}}
        ulm_card_generic_swap_icon: mdi:delete
```

Big thanks in advance. :)

**Comment by beWAYNE** [comment]
```
- type: custom:button-card
  template:
    - custom_card_paddy_waste_collection
  entity: sensor.awigo
  variables:
    ulm_card_generic_swap_name: >
      [[[ 
        return states['calendar.awigo_abfallwirtschaft_landkreis_osnabruck_gmbh_2'].attributes.message
      ]]]
    ulm_card_generic_swap_icon: mdi:delete
``` 
With this code change, it should work.
But if you have two garbage pickups in one day, it will only show the first collection.
