### ISSUE TITLE
Thermostat Card has missing "°C / °F"

### ISSUE THREAD

**Issue by idominiki** [UI-Lovelace-Minimalist/UI#1469]
**Describe the bug**
For me, the Thermostat doesn't show "°C / °F". Has anyone else this behavior?
<img width="805" alt="image" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/62521486/7d5898e5-b707-43f5-83c5-db5a5359aae2">

Example code:
```
- type: "custom:button-card"
    template: card_thermostat
    entity: climate.badezimmer
    variables:
      ulm_card_thermostat_name: Raumthermostat
      ulm_card_thermostat_enable_collapse: true
      ulm_card_thermostat_enable_controls: true
      ulm_card_thermostat_enable_hvac_modes: true
      ulm_card_thermostat_enable_background_color: true
      ulm_card_thermostat_enable_popup: true
```
