### ISSUE TITLE
Person Card is not showing user's profile photo nor icon

### ISSUE THREAD

**Issue by LightMoon** [UI-Lovelace-Minimalist/UI#1475]
**Describe the bug**

I am not sure if this functionality is broken or it is due to my bad configuration but I read the documentation and implemented as is.

**Expected behaviour**
To see the user's photo on the card

**Screenshots**
 However, what I see is this instead.

<img width="228" alt="Screenshot 2024-03-11 at 5 23 36 pm" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/1636991/0262b300-fbaa-4558-82f2-fe7780414289">

**Additional context**
Hass.io version
```
Core
2024.3.0
Supervisor
2024.02.1
Operating System
12.0
Frontend
20240306.0
```
**Related Card Config**

```
  - type: horizontal-stack
    cards:
      - type: 'custom:button-card'
        template: card_person
        entity: person.saeed
        variables:
        ulm_card_person_entity: person.saeed
        ulm_card_person_use_entity_picture: true
        ulm_card_person_icon: mdi:face-man
        ulm_card_person_battery: sensor.battery_iphone
        ulm_card_person_eta: sensor.waze_travel_time_person
        ulm_address: sensor.s10_mike_gegeocodeerde_locatie
 ```

**Comment by Obs3ssive** [comment]
This also stopped working for me on my badge cards

**Comment by wilbiev** [comment]
The defined variables are not recognized due to a wrong indentation. This is the correct syntax:
```
variables:
  ulm_card_person_entity: person.saeed
  ulm_card_person_use_entity_picture: true
  ulm_card_person_icon: mdi:face-man
  ulm_card_person_battery: sensor.battery_iphone
  ulm_card_person_eta: sensor.waze_travel_time_person
  ulm_address: sensor.s10_mike_gegeocodeerde_locatie
```
