### ISSUE TITLE
custom card radial not aligned on safari - custom_card_speedtest_shogun160

### ISSUE THREAD

**Issue by warmfire540** [UI-Lovelace-Minimalist/UI#1478]
**Describe the bug**
The radial bars are not aligned on Safari - both MacOS & iOS.

**To Reproduce**

1. Setup the speedtest card per instructions: https://github.com/UI-Lovelace-Minimalist/UI/tree/main/custom_cards/custom_card_speedtest_shogun160

**Expected behavior**
On Chrome and Safari it should be centered per the pictures.

**Screenshots**
The top is chrome the bottom safari
<img width="612" alt="image" src="https://github.com/UI-Lovelace-Minimalist/UI/assets/19420884/9e386274-5c32-41b2-a6e7-86fed7b8f27d">

**Additional context**

**Related Logs** (can be found in the browser-console (F12))
Add related logs for the problem

**Related Card Config**
Add the card config from `ui-lovelace.yaml` with the related problem

```yaml
type: custom:button-card
template: custom_card_speedtest_shogun160
variables:
  ulm_custom_card_speedtest_download_speed_entity: sensor.speedtest_download
  ulm_custom_card_speedtest_upload_speed_entity: sensor.speedtest_upload
  ulm_custom_card_speedtest_ping_entity: sensor.speedtest_ping
  ulm_custom_card_speedtest_round: true
```
