### ISSUE TITLE
Binary Sensor Alert Card not changing color when ulm_active_state is true

### ISSUE THREAD

**Issue by longhtran91** [UI-Lovelace-Minimalist/UI#1480]
**Describe the bug**
Here is my yaml
```
    - type: "custom:button-card"
      template: card_binary_sensor_alert
      entity: binary_sensor.top_left_gas_contact
      variables:
          ulm_card_binary_sensor_alert_name: Top Left
          ulm_card_binary_sensor_alert_color: green
          ulm_card_binary_sensor_alert_force_background_color: false
          ulm_card_binary_sensor_alert_icon: mdi:gas-burner
```

Here is the screenshot:
![2024-04-01_11-15](https://github.com/UI-Lovelace-Minimalist/UI/assets/1468210/a61a1608-afc8-4475-87b9-cebd47069d98)

**Expected behavior**
The gas-burner is blue instead of green (ulm_card_binary_sensor_alert_color)
