### ISSUE TITLE
Inconsistency of naming main interface colours in the theme files

### ISSUE THREAD

**Issue by jkobusinski** [UI-Lovelace-Minimalist/UI#1482]
**Describe the bug**
Naming of main interface colors in theme files is not consistent. This applies to all 4 files and both the light and dark schemes.

Assuming that the output color set is '--color-*', the definition of '--google-pink', '--google-purple' is missing.
Instead, there is only '--google-violet', which has no equivalent by name, but corresponds to the colour '--color-purple'

As some cards (ApexChart) do not accepts RGB color represenation (only HEX one) it's important to have both definition in sync.

**To Reproduce**
n/a

**Expected behavior**
* define '--google-pink' and '--google-purple', 
* remove '--google-violet'.

**Screenshots**
n/a

```yaml
  modes:
    light:
      # main interface colors
      google-violet: "#661FFF"
      color-purple: "102, 31, 255"
      color-pink: "233, 30, 99"
  
```
