### ISSUE TITLE
HELP! Popup Windows dont work! What to do?

### ISSUE THREAD

**Issue by ItsCharged** [UI-Lovelace-Minimalist/UI#1483]
**Describe the bug**
The Popup windows load, but empty.

**To Reproduce**

1.Choose any popup
2. Code it
3. It wont work

**Expected behavior**
Seeing a working popup windows

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/90069597/72c91f6b-123f-4526-9b7e-8055be45b876)

**Additional context**
Idk what happend, installed all required assets such as browser mod but it doesent work

**Related Logs** (can be found in the browser-console (F12))
no logs found :(

**Related Card Config**
```
- type: "custom:button-card"
  template:
    - card_media_player
  entity: media_player.antons_raum_nest_mini
  variables:
    ulm_card_media_player_enable_popup: true

```

EDIT: I did try other pop ups, all i can use (weather, light, media-player)
