### ISSUE TITLE
Custom-card imswel person in wrong language

### ISSUE THREAD

**Issue by ChrissHF** [UI-Lovelace-Minimalist/UI#1491]
**Describe the bug**
Person Location and button to find Phone in Custom Card imswel person are in the wrong language.

**Expected behavior**
Text on card and button in pop-up should display in german

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/98695812/9edf49c9-6bff-4e42-b476-da9f569acf50)
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/98695812/db49fd66-fe92-4eeb-9255-516c41bdefc2)

**Additional context**
I have HA and all devices set up in german, but the card apparently chooses a different language.
I can't find proper documentation how to fix this.
Can anybody help?

**Related Logs** (can be found in the browser-console (F12))
Add related logs for the problem

**Related Card Config**
```yaml
- type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template: custom_card_imswel_person
                entity: person.chriss
                variables:
                  ulm_card_imswel_person_entity: person.chriss
                  ulm_card_imswel_person_wifi_tracker: device_tracker.pixel_8_3
                  ulm_card_imswel_person_gps_tracker: device_tracker.pixel_8_2
                  ulm_card_imswel_person_findmy_script: script.find_chriss
                  ulm_card_imswel_person_use_entity_picture: true
                  ulm_custom_card_imswel_person_language_variables
```
