### ISSUE TITLE
Update weather entity usage due to removal of forecast property.

### ISSUE THREAD

**Issue by Canario0** [UI-Lovelace-Minimalist/UI#1492]
**Describe the bug**
According to the version 2024.4 the property "forecast" has been remove in favor of the service "weather.get_forecasts" see: [release](https://www.home-assistant.io/blog/2024/04/03/release-20244/).

**To Reproduce**

1. Use the popup "popup_weather_forecast"

**Expected behavior**
Been able to open the popup and display the data.

**Screenshots**
![image](https://github.com/UI-Lovelace-Minimalist/UI/assets/18551747/9da1f13d-2ea8-4986-b219-81c7c11a489f)

**Comment by Canario0** [comment]
*Solution*: create a sensor to update the data.
```
template:
  - trigger:
      - platform: time_pattern
        hours: /6
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.aemet
        response_variable: forecast_daily
    sensor:
      - name: Weather Forecast Daily
        unique_id: weather_forecast_aemet_daily
        state: "{{ states('sensor.aemet_condition') }}"
        attributes:
          forecast: "{{ forecast_daily['weather.aemet'].forecast }}"
```

This code created the sensor "sensor.aemet" which I did set in the ui component as `ulm_weather: "sensor.aemet"` and did work without needing any update on the code side.
