### ISSUE TITLE
Button confirmation not working on whole button

### ISSUE THREAD

**Issue by velisiska** [UI-Lovelace-Minimalist/UI#1498]
Hello, i am trying to add confirmation on a button according to the underlying button-card component https://github.com/custom-cards/button-card?tab=readme-ov-file#confirmation, but this works only on the most outer part of the button, not for the icon or name.

```yaml
- type: "custom:button-card"
  template: card_power_outlet
  variables:
    ulm_card_power_outlet_name: NAS
    ulm_card_power_outlet_icon: "mdi:nas"
  entity: switch.nas
  confirmation:
    text: Are you sure you want to press this button?
```
i've also tried it with`tap_action`, but its still the same.

```yaml
- type: "custom:button-card"
  template: card_power_outlet
  variables:
    ulm_card_power_outlet_name: NAS
    ulm_card_power_outlet_icon: "mdi:nas"
  entity: switch.nas
  tap_action:
    action: call-service
    service: switch.toggle
    service_data:
      entity_id: switch.nas
    confirmation:
      text: Are you sure you want to press this button?
```

![actions](https://github.com/UI-Lovelace-Minimalist/UI/assets/9591958/51480980-9e5f-4c59-a0b5-db78fec28643)
