### ISSUE TITLE
popup not working in adaptive dashboard

### ISSUE THREAD

**Issue by athiosh** [UI-Lovelace-Minimalist/UI#1524]
**Describe the bug**
I am trying to setup adaptive dashboard and the popup does not show if it is set in grid-template-areas in the adaptive-ui.yaml file.

**To Reproduce**

remove popup under grid-template-areas in adaptive-ui.yaml

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/4dbd8cf0-a94a-4dfe-b148-20451cfa24b6)

**Additional context**

**Related Logs** (can be found in the browser-console (F12))
Add related logs for the problem

**Related Card Config**
Add the card config from `ui-lovelace.yaml` with the related problem

remove popup under gird-template-areas
```yaml
title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: "var(--background-image)"
views:
  - type: "custom:grid-layout"
    title: "home"
    icon: "mdi:home"
    path: "0"
    layout:
      grid-template-columns: "1fr 1fr"
      grid-template-rows: "min-content"
      grid-template-areas: |
        "main" # original "main popup"
      mediaquery:
        "(max-width: 1100px), (orientation: portrait)":
          grid-template-columns: "100%"
          grid-template-areas: "main"
    cards:
      - !include "views/main.yaml"
      - !include "popup/popup.yaml"
```
