### ISSUE TITLE
Cannot change icon in custom_esh_room card

### ISSUE THREAD

**Issue by AlexanderStavrop** [UI-Lovelace-Minimalist/UI#1526]
**Describe the bug**
I am trying to use the custom esh room card, and according to the documentations by using ulm_card_esh_room_light_icon_on and ulm_card_esh_room_light_icon_off, to change the icon that appears on the card for each state, but this is not working.

**To Reproduce**
Add the esh room card to your dashboard, following the documentation https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_esh_room/#template-code

**Expected behavior**
The icon should be a door but it is a bulb

**Screenshots**
![image](https://github.com/user-attachments/assets/6e66e6c6-da4a-4529-9f55-4e726d9a963d)

**Additional context**

**Related Card Config**
```
---
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "Minimalist dashboard"
background: "var(--background-image)"
# views: !include_dir_merge_list "views/"
views:
  - !include views/home.yaml
  - !include views/entrance.yaml
  - !include views/bathroom.yaml
  - !include views/office.yaml
  - !include views/livingroom.yaml
```

```yaml
     - type: "custom:button-card"
       template:
           - card_esh_room
           - yellow_on
       name: Bathroom
       entity: light.tradfri_1
       icon: mdi:bathtub
       tap_action:
           action: navigate
       navigation_path: "bathroom"
       variables:
           ulm_card_esh_room_light_icon_off: mdi:door
           ulm_card_esh_room_light_icon_on: mdi:door
       label: '[[[ return states["sensor.temperature_humidity_1_temperature"].state + "°C" ]]]'

```
