### ISSUE TITLE
card_thermostat gives error when stepping temp up or down manually

### ISSUE THREAD

**Issue by kohlerryan** [UI-Lovelace-Minimalist/UI#1530]
**Describe the bug**
card_thermostat gives error when stepping temp up or down manually.  First noticed after upgrade to HA 2024.8.1.  Error message appears a bottom of screen.  See screenshot for error message.

**To Reproduce**

1. Add card_thermostat with these variables set:
  ```
    type: custom:button-card
    template: card_thermostat
    entity: climate.living_room_thermostat
    variables:
      ulm_card_thermostat_name: 'Living Room Thermostat'
      ulm_card_thermostat_enable_collapse: true
      ulm_card_thermostat_enable_controls: true
      ulm_card_thermostat_enable_hvac_modes: true
      ulm_card_thermostat_enable_background_color: true
      ulm_card_thermostat_temp_step: 1.0
```
2. Click to increase or decrease temp.
3. See error

**Expected behavior**
Temp should increase by defined step - or default of 1.

**Screenshots**

![image](https://github.com/user-attachments/assets/beaf1fc6-ceed-4d99-b922-f881b01fe9e6)

**Additional context**
I attempted to remove variable `ulm_card_thermostat_temp_step:`, as well as set it as 1 vs 1.0.  Same result.
