### ISSUE TITLE
custom_card_apexcharts not working

### ISSUE THREAD

**Issue by base2006** [UI-Lovelace-Minimalist/UI#1538]
After I installed the custom_card_apexcharts I'm getting this error (see screenshot) and I don't know how to fix it. Am I missing something?

RomRider/apexcharts-card has been installed.

![Screenshot_7](https://github.com/user-attachments/assets/7a4d6585-a07b-4a59-8522-5e9b65102cc7)

Config below
```yaml
  - type: "custom:button-card"
    template: "custom_card_apexcharts"
    variables:
      chart_type: "line"
      graph_span: "1h"
      entity_1:
        entity_id: "sensor.p1_meter_total_power_export"
        name: "Export"
        color: "blue"
        max_value: 4
```
