### ISSUE TITLE
custom weather popup only shows a blank popup

### ISSUE THREAD

**Issue by Jklein03** [UI-Lovelace-Minimalist/UI#1544]
For a while the custom weather popup worked fine. Now when I open the weather popup, only a blank strip appears at the top of the screen (see screenschots).
I haven't change anything in my yaml. The popup just stopped working. Other custom popups still work and the issue is the same on all my devices/browsers. 

Does anyone know what the issue could be?

Thanks!

**Screenshots**
default view:
![Screenshot 2024-10-16 172157](https://github.com/user-attachments/assets/32de72ab-fc35-4e68-aa97-3c32525b9d93)

when I try to open the popup:
![image](https://github.com/user-attachments/assets/42d4ef47-18c6-460f-a1f6-c9e21ebc4548)

```yaml
- type: "custom:button-card"
        template: card_weather
        entity: weather.forecast_home_2
        variables:
          ulm_card_weather_name: " "
          ulm_card_weather_primary_info:
            - precipitation_probability
          ulm_card_weather_secondary_info:
            - wind_speed
          ulm_custom_popup:
            template: "popup_weather_forecast"
            entity: weather.forecast_home_2
            popup_variables:
              ulm_weather_popup_surpress_first_forecast: false
```

**Comment by Baymax2909** [comment]
I can confirm this as well and add a little bit of additional information.

Open it on a Webbrowser I receive the following message:

`ButtonCardJSTemplateError: TypeError: undefined is not an object (evaluating 'entity.attributes.forecast[0]') in 'return 'Max. ' + entity.attributes.forecast[0].temperature + '° Min. ' + entity.attributes.forecas...'`

I did a little bit of research and found out, that the weather entity and espacilly the forecast-data was changed in 2024. Now we need to call a service (`weather.get_forecasts`) to get the data.

Maybe someone with more coding skills then me could do some rework on the `popup_weather_forecast.yaml`?

**Comment by wilbiev** [comment]
It took me some time but I found a solution:

Create a templates.yaml file in the same (config) folder as configuration.yaml
Copy/paste the following to templates.yaml:

```
- trigger:
    - platform: time_pattern
      hours: /1
    - platform: homeassistant
      event: start
  action:
    - service: weather.get_forecasts
      data:
        type: daily
      target:
        entity_id: weather.forecast_home
      response_variable: daily
  sensor:
    - name: Weather Daily
      unique_id: 7f8aca37-be26-436d-9459-d82b6f9b96e1
      state: "{{ states('weather.forecast_home') }}"
      attributes:
        temperature: "{{ state_attr('weather.forecast_home', 'temperature') }}"
        dew_point: "{{ state_attr('weather.forecast_home', 'dew_point') }}"
        temperature_unit: "{{ state_attr('weather.forecast_home', 'temperature_unit') }}"
        humidity: "{{ state_attr('weather.forecast_home', 'humidity') }}"
        cloud_coverage: "{{ state_attr('weather.forecast_home', 'cloud_coverage') }}"
        pressure: "{{ state_attr('weather.forecast_home', 'pressure') }}"
        pressure_unit: "{{ state_attr('weather.forecast_home', 'pressure_unit') }}"
        wind_bearing: "{{ state_attr('weather.forecast_home', 'wind_bearing') }}"
        wind_speed: "{{ state_attr('weather.forecast_home', 'wind_speed') }}"
        wind_speed_unit: "{{ state_attr('weather.forecast_home', 'wind_speed_unit') }}"
        visibility_unit: "{{ state_attr('weather.forecast_home', 'visibility_unit') }}"
        precipitation_unit: "{{ state_attr('weather.forecast_home', 'precipitation_unit') }}"
        forecast: "{{ daily['weather.forecast_home'].forecast }}"

```

Add the following line to configuration.yaml:
`template: !include templates.yaml
`

Use sensor.weather_daily as your popup entity:
```
          ulm_custom_popup:
            template: "popup_weather_forecast"
            entity: sensor.weather_daily
            popup_variables:
              ulm_weather_popup_surpress_first_forecast: false
```
