### ISSUE TITLE
After upgrading to the latest version, the card_scenes_welcome no longer works and shows the error: “input_select/select_option”. Extra keys not allowed @ data[‘target’][‘option’]. Got ‘XX’.

### ISSUE THREAD

**Issue by hsguyue** [UI-Lovelace-Minimalist/UI#1566]
After upgrading to the latest version, the card_scenes_welcome no longer works and shows the error: “input_select/select_option”. Extra keys not allowed @ data[‘target’][‘option’]. Got ‘XX’.

Downgrading to version 1.3.10 fixed the issue.

**Comment by jdc0730** [comment]
I am not an expert at HA or coding, but I managed to get this to work. The issue is that the option has to be moved to a data block with the move from call-service to perform-action. 

custom_components/ui_lovelace_minimalist/lovelace/ulm_templates/card_templates/cards/card_welcome_scenes.yaml starting at line 306 to 319 with the following. 

`          target: |
            [[[
              var obj;
              if(typeof(entity) !== 'undefined' && entity !== undefined){
                if( entity?.entity_id.startsWith("input_select.") )
                  obj = { entity_id: entity?.entity_id };
                return obj;
              }
            ]]]
          data: |
            [[[
              if (variables.service_data){
                return variables.service_data
              }
              var obj;
              if(typeof(entity) !== 'undefined' && entity !== undefined){
                if( entity?.entity_id.startsWith("input_select.") )
                  obj = { option: variables.state };
                return obj;
              }
            ]]]`

You can do this with the item 2 block below just below this bit, but it wasn't necessary for my setup.

**Comment by polcape** [comment]
Hi, same issue on entity as script and script data, with this error

Extra keys not allowed @ data[‘target’][‘browser_id’]. Got ‘XX’.

Downgrading to version 1.3.10 fixed the issue.

**Comment by wilbiev** [comment]
Issue fixed in new published release v.1.3.13

**Comment by fear** [comment]
i am having the same error with the "Vertical Button Card". Seems to be some kind of the same bug?

```
      - type: "horizontal-stack"
        cards:
          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.scene_wohnzimmer
            name: TV
            icon: mdi:television
            show_last_changed: false
            variables:
              ulm_card_vertical_button_state: TV
              ulm_card_vertical_button_color: red
          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.scene_wohnzimmer
            name: Essen
            icon: mdi:silverware
            show_last_changed: false
            variables:
              ulm_card_vertical_button_state: essen_tv
              ulm_card_vertical_button_color: yellow
```

![image](https://github.com/user-attachments/assets/5f0ff485-e0de-449d-9921-4a18dc70d12d)
