### ISSUE TITLE
Still getting "Failed to perform the action automation/trigger... " when using call-service (v1.3.16)

### ISSUE THREAD

**Issue by mark1foley** [UI-Lovelace-Minimalist/UI#1608]
**Describe the bug**
After upgrading to v1.3.16 I get the error "Failed to perform the action automation/trigger. not a valid value for dictionary value @ data['target']['entity_id']. Got ''" when trying to execute an automation or script using the generic card.  The same config works fine with v1.3.14

**To Reproduce**

I have a view with the following configuration.

````
  - type: horizontal-stack
    cards:
      - type: "custom:button-card"
        template:
          - card_generic
        entity: "automation.nighttime"
        variables:
          ulm_icon_tap_action: "call-service"
          ulm_icon_tap_service: "automation.trigger"
          ulm_icon_tap_service_data:
            entity_id: automation.nighttime
````
After upgrading to v1.3.16 and clicking the button I get the error "Failed to perform the action automation/trigger. not a valid value for dictionary value @ data['target']['entity_id']. Got ''"  

After reverting to v1.3.14 it works fine.

Have I missed something that needs to be done as part of the upgrade?

**Expected behavior**
For the configuration to work with v1.3.16 as it did with v1.3.14
