### ISSUE TITLE
I try to set-up UI lovelace Minimalist and get stucked with "No Card type configured", what to do?

### ISSUE THREAD

**Issue by Fosvang** [UI-Lovelace-Minimalist/UI#1611]
title: main
path: main
cards:
  - type: custom:button-card
    template: custom_card_esh_welcome
    triggers_update: input_boolean.minimalist_dropdown
    variables:
      ulm_card_esh_welcome_collapse: input_boolean.minimalist_dropdown
      ulm_weather: weather.openweathermap
      entity_1:
        nav: house
        icon: mdi:home
        name: House
        color: blue
      entity_2:
        nav: lights
        icon: mdi:lightbulb
        name: Lights
        color: yellow
      entity_3:
        nav: security
        icon: mdi:shield
        name: Secure
        color: green
      entity_4:
        nav: network
        icon: mdi:nas
        name: Lab
        color: purple
      entity_5:
        nav: network
        icon: mdi:flask
        name: Lab
        color: red

**Comment by wilbiev** [comment]
Try the following:

```
---
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: "var(--background-image)"
# views: !include_dir_merge_list "views/"
views:
  - title: "Example View"
    path: 0
    icon: "mdi:flower"
    cards:
      - type: "vertical-stack"
        cards:
          - type: "custom:button-card"
            template: custom_card_esh_welcome
            triggers_update: input_boolean.minimalist_dropdown
            variables:
              ulm_card_esh_welcome_collapse: input_boolean.minimalist_dropdown
              ulm_weather: weather.openweathermap
              entity_1:
                nav: house
                icon: mdi:home
                name: House
                color: blue
              entity_2:
                nav: lights
                icon: mdi:lightbulb
                name: Lights
                color: yellow
              entity_3:
                nav: security
                icon: mdi:shield
                name: Secure
                color: green
              entity_4:
                nav: network
                icon: mdi:nas
                name: Lab
                color: purple
              entity_5:
                nav: network
                icon: mdi:flask
                name: Lab
                color: red
```
