### ISSUE TITLE
Thermostat Card Bug

### ISSUE THREAD

**Issue by KruseLuds** [UI-Lovelace-Minimalist/UI#1613]
I just switched from the Google Nest Learning Thermostat to the Ecobee Smart Thermostat Enhanced. This does not happen with Nest (which sucks because of the convoluted cloud-based integration which is slow as molasses). This one is completely local and responds instantly (it has to be through the homekit integration, but no matter). Anybody see this kind of error on the Ecobee Smart Thermostat Enhanced?

The error message appears whenever I click the “+” or “-” button on a dashboard for this widget, but the popup works perfectly. This same exact error message takes place regadless of whether or not I press ANY “+” or minuts “-” button - and even the same EXACT error message - any of the "+" or "_" buttons shown in any of the modes (Heat, Cool, or Heat/Cool):

![Image](https://github.com/user-attachments/assets/8b41ce02-3c42-4b5a-8029-8e3808ceeba7)

Yaml card config with the related problem:

```yaml
cards:
  - type: horizontal-stack
    cards:
      - type: "custom:button-card"
        template: card_thermostat
        entity: climate.dining_room_ecobee_thermostat
        variables:
          ulm_card_thermostat_enable_collapse: true
          ulm_card_thermostat_enable_controls: true
          ulm_card_thermostat_enable_hvac_modes: true
          ulm_card_thermostat_enable_popup: true
          ulm_card_thermostat_preset_mode: true
```
