### ISSUE TITLE
popup_light can only change color temp but not rgb color

### ISSUE THREAD

**Issue by brvn0** [UI-Lovelace-Minimalist/UI#1620]
**Describe the bug**
When using popup_light with card_light, I can (on multiple devices: win + android) only change the color temperature and not the rgb color. When trying to tap anywhere on the color circle it will just reset to the previous location. The color is correctly displayed in the circle when changing the color via the homeassistant settings menu.

**To Reproduce**
create a card_light card and hold it, then try setting the rgb color
i installed browser_mod as well and put the corresponding entry in my config (`browser_mod:`)

**Screenshots**

![Image](https://github.com/user-attachments/assets/3b4ee6eb-7697-4a6a-a6d0-46bbae47f0d7)

**Related Logs** (can be found in the browser-console (F12))
this is a card_mod warning i receive when opening the popup but it only seems to talk about a deprecation notice and nothing concerning the actual problem

```
You are using a custom card which relies on card-mod, and uses an outdated signature for applyToElement.
The outdated signature will be removed at some point in the future. Hopefully the developer of your card will have updated their card by then.
The card used card-mod to apply styles here: <browser-mod-popup card="true">
```

**Related Card Config**
Add the card config from `ui-lovelace.yaml` with the related problem

```yaml
- type: "custom:button-card"
  template:
    - card_light
    - popup_light
  entity: light.stuttgart_wandlampen
  variables:
    ulm_card_light_name: Wandlampen
    ulm_card_light_enable_slider: true
    ulm_card_light_enable_color: true
    ulm_card_light_enable_popup: true
    #ulm_card_light_enable_popup_tap: true
    #ulm_card_light_enable_buttons: true
    #ulm_card_light_enable_slider_minSet: 7
    #ulm_card_light_enable_slider_maxSet: 80
    #ulm_card_light_brightness_low: 10
    #ulm_card_light_brightness_medium: 40
    #ulm_card_light_brightness_high: 70
```
