### ISSUE TITLE
Enhancement: Conditional Confirmation

### ISSUE THREAD

**Issue by mwolter805** [UI-Lovelace-Minimalist/UI#19]
Recommend adding the following to every card. No reason not to and adds simple protection for critical devices.

If the variable is included in the card, the confirmation text is displayed. If the variable is not included, the card operates normally. 

Card
```yaml
variables:
  custom_card_mwolter_power_outlet_confirm_text: Toggle the eGPU power?
```
Template
```yaml
tap_action:
  action: toggle
  confirmation: '[[[ return variables.custom_card_mwolter_power_outlet_confirm_text == null ? false : {"text": variables.custom_card_mwolter_power_outlet_confirm_text} ]]]'
hold_action:
  action: more-info
```

**Comment by Paddy0174** [comment]
I think it's a good idea, but I'm not happy with the way of implementing it. It is additional code where we don't know how many people are really using it. 

I'd suggest, we think of a better way to use that, something where the user can enable or disable it easily. But to be honest, how we should do that, I have no idea (yet). :) 

If we can't find a better way, we should do it the mentioned way. :) 

Thoughts? 

EDIT: while thinking about it, should we just do a seperate card for that? We could just inherit the template from the card without confirmation and add a suffix for every card...

I'll write down some kind of code example as a POC (proof of concept) and put it in here.

**Comment by Paddy0174** [comment]
Here we go, does that sound like a solid idea to go on with?

(Almost) every card gets a new template added, naming with a suffix like "_confirm". The new template would look something like this:

```yaml
# button_card_templates.yaml
card_xy:
  the code

card_xy_confirm:
  templates:
    - card_xy
  variables:
    ulm_card_xy_confirm_message: 'Really? Turning the light off in the middle of the evening?'
  only new confirmation code added here
```
