### ISSUE TITLE
Icon Only Light/Switch

### ISSUE THREAD

**Issue by damianeickhoff** [UI-Lovelace-Minimalist/UI#198]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I Would like a button-only light switch. I made a simple one which can turn on and off the light ór switch and also gives it the yellow color when on. But, it doens't show a warning if a light is unavailable. When I add that template, the padding gets messed up.

Also the padding itself doenst fit the whole theme. I hope maybe someone can make this better then me :)

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/12126826/147946920-056f7391-0cc9-4fca-a20b-6e98560b6933.png)

Code:
```
icon_only_custom:
  color: "var(--google-grey)"
  show_icon: true
  show_label: false
  show_name: false
  template:
    - "yellow"
  tap_action:
    action: "toggle"
  hold_action:
    action: "more-info"
  styles:
    icon:
      - color: "rgba(var(--color-theme),0.2)"
    label:
      - justify-self: "start"
      - align-self: "start"
      - font-weight: "bold"
      - font-size: "12px"
      - filter: "opacity(40%)"
      - margin-left: "12px"
    img_cell:
      - background-color: "rgba(var(--color-theme),0.05)"
      - border-radius: "50%"
      - place-self: "center"
      - width: "42px"
      - height: "42px"
    card:
      - border-radius: "var(--border-radius)"
      - box-shadow: "var(--box-shadow)"
      - padding: "12px"
      - width: "84px"
  size: "20px"
```

**Comment by sildehoop** [comment]
I will pick this up after the split merge

**Comment by saxel** [comment]
Maybe this should be handled by #211 if it is also extended to support other entities than input_select and input_boolean. You get the desired look by specifying show_name: false

Example:
```yaml
              - type: 'custom:button-card'
                template: card_vertical_button
                entity: fan.fan
                show_name: false
                variables:
                  ulm_card_vertical_button_color: blue
```

![image](https://user-images.githubusercontent.com/12456858/148715772-288dfcd2-67d6-4653-90e1-f01f2f662998.png)
