### ISSUE TITLE
Custom custom_card_light_color width of slider

### ISSUE THREAD

**Issue by Ralf-J** [UI-Lovelace-Minimalist/UI#208]
I am using the template card_light_horizontal_color of this custom card together with the non-custom (for lights that can't change the color) template card_light_slider_horizontal. Thereby I noticed that the width of the brightness slider of the former named template is wider than of the latter one. This looks inconsistent and also the lesser width of the "standard template" card_light_slider_horizontal gives more space for the name of the light which is better in my opinion (therefore I do not want to use use the template with the color option for all lights).

I like the template a lot. Please change the style so that it looks consistent with the "standard template". I tried to look up the issue myself in the .yaml file but was not able to identify what to change.

See screenshot attached where entity "Essbereich" is using the template card_light_slider_horizontal and entity "Kommode" is using template card_light_horizontal_color.
<img width="510" alt="slider_width" src="https://user-images.githubusercontent.com/97187438/148316322-27711cce-8c16-4bb9-9306-3925e7209137.png">

**Comment by CM000n** [comment]
Thanks for the hint Ralf.
There is already an discussion ongoing if we should combine all the different light cards https://github.com/UI-Lovelace-Minimalist/UI/discussions/193
Mayen we can fix this visual bug with that 

FYI @schumijo and @bassbruss

**Comment by basbruss** [comment]
This was done intentionally in my custom_card. Because it should allow better accessibility when used on mobile devices as the slider has more width and there is less unused empty space.
In the draft code from discussion #193 the slider is aligned on the 'old' way for now.
For now you can change the the grid styles parameters in `card_light_horizontal_color` if you do prefer the first one from:
```
card_light_horizontal_color:
  template:
    - "list_items_light"
    - "ulm_language_variables"
    - "background_color"
  variables:
    ulm_card_light_name: "[[[ return entity.attributes.friendly_name ]]]"
    ulm_card_light_icon:
    ulm_card_light_mode:
  show_icon: false
  show_name: false
  show_label: false
  styles:
    grid:
      - grid-template-columns: "auto auto"
      - column-gap: "0px"
      - grid-template-columns: "1fr 2fr"
```
to:
```
card_light_horizontal_color:
  template:
    - "list_items_light"
    - "ulm_language_variables"
    - "background_color"
  variables:
    ulm_card_light_name: "[[[ return entity.attributes.friendly_name ]]]"
    ulm_card_light_icon:
    ulm_card_light_mode:
  show_icon: false
  show_name: false
  show_label: false
  styles:
    grid:
      - column-gap: "0px"
      - grid-template-columns: "1fr 1fr"
```
