### ISSUE TITLE
Chip navigation template

### ISSUE THREAD

**Issue by rphlwnk** [UI-Lovelace-Minimalist/UI#24]
I'm using chips for view navigation too, maybe add a second template for tap action?

```
- type: 'custom:button-card' 
  template:
    - chip_icon_only
    - chip_navigation
  variables:
    ulm_chip_icon_only: 'mdi:car'
    ulm_chip_navigation_path: car
```
Template
```
chip_navigation:
  tap_action:
    action: navigate
    navigation_path: "[[[ return variables.ulm_chip_navigation_path; ]]]"
```
