### ISSUE TITLE
No Colors on the theme

### ISSUE THREAD

**Issue by Zwordi** [UI-Lovelace-Minimalist/UI#270]
**Describe the bug**
The theme is working but no colors on it. I’m running under the latest tag/release available v1-0-0-beta11.
**To Reproduce**

I just followed the install path, nothing fancy, resources are loaded from configuration.yaml.
I’m using yaml mode.

```yaml
lovelace:
  mode: yaml
  resources:
  - url: /hacsfiles/cover-element/cover-element-bundle.js
    type: module
  - url: /hacsfiles/upcoming-media-card/upcoming-media-card.js
    type: module
  - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js
    type: module
  - url: /hacsfiles/entity-attributes-card/entity-attributes-card.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.10.0
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.13.0
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/my-cards/my-cards.js
    type: module
  dashboards:
    lovelace-minimalist:
      mode: yaml
      title: Minimalist
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace-minimalist.yaml
```

```yaml
button_card_templates: !include_dir_merge_named minimalist-templates/
views:
  - title: Minimalist
    cards:
      - type: 'custom:button-card'
        template: custom_card_paddy_welcome_with_weather
        variables:
          ulm_custom_card_paddy_welcome_time: sensor.time
          ulm_custom_card_paddy_welcome_weather_provider: weather.home
      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            template: 
              - card_cover_with_buttons
            variables:
              ulm_card_cover_with_buttons_name: "Kitchen"
              ulm_card_cover_with_buttons_entity: "cover.kitchen_cover_2"
          - type: 'custom:button-card'
            template: 
              - card_cover_with_buttons
            variables:
              ulm_card_cover_with_buttons_name: "SAM"
              ulm_card_cover_with_buttons_entity: "cover.terrasse_shutter"
          - type: 'custom:button-card'
            template: 
              - card_cover_with_buttons
            variables:
              ulm_card_cover_with_buttons_name: "Terrasse"
              ulm_card_cover_with_buttons_entity: "cover.terrasse_solar_tent"
      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            template: card_light
            entity: light.kitchen
          - type: 'custom:button-card'
            template: card_light
            entity: light.sink
          - type: 'custom:button-card'
            template: card_light
            entity: light.workstation
      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            template: card_light_slider
            variables:
              ulm_card_light_slider_name: Livingroom Light
            entity: light.dimmer_living_light_0
      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            template: card_title
            name: People at Home
            label: 'Where is Charlie ?'  
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.o
              ulm_card_person_use_entity_picture: true
              ulm_card_person_zone1: work
              ulm_card_person_zone2: school
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.a
              ulm_card_person_use_entity_picture: true
              ulm_card_person_zone1: work
              ulm_card_person_zone2: school
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.m
              ulm_card_person_use_entity_picture: true
              ulm_card_person_zone1: work
              ulm_card_person_zone2: school
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.g
              ulm_card_person_use_entity_picture: true
              ulm_card_person_zone1: work
              ulm_card_person_zone2: school
      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            template: card_battery
            variables:
              ulm_card_battery_attribute: battery
            entity: sensor.aquara_motion_sensor_1_battery
          - type: 'custom:button-card'
            template: card_battery
            variables:
              ulm_card_battery_attribute: battery
            entity: sensor.aquara_contact_sensor_1_battery
          - type: 'custom:button-card'
            template: card_battery
            variables:
              ulm_card_battery_attribute: battery
            entity: sensor.aquara_flood_battery
          - type: 'custom:button-card'
            template: card_battery
            variables:
              ulm_card_battery_attribute: battery
            entity: sensor.valve_battery
      - type: horizontal-stack
        cards:
          - type: 'custom:button-card'
            template: custom_card_mpse_thermostat
            entity: climate.bureau_valve
          - type: 'custom:button-card'
            template: custom_card_mpse_thermostat
            entity: climate.s
          - type: 'custom:button-card'
            template: card_graph
            variables:
              ulm_card_graph_color: "var(--google-blue)"
              ulm_card_graph_name: Temperature Livingroom
              ulm_card_graph_entity: sensor.a_temperature
```

**Expected behavior**

To have nice color :).

**Screenshots**

![image](https://user-images.githubusercontent.com/8830303/149987841-923b540f-b06d-4d3f-9b2d-2089dda6d8b3.png)

**Additional context**

Installation of the custom_card required done through hacs. Even added :
```yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
```
As I saw on the "web console" that it could help.
