### ISSUE TITLE
HACS integration forces default dashboard on iOS app

### ISSUE THREAD

**Issue by filikun** [UI-Lovelace-Minimalist/UI#291]
**Describe the bug**
For some reason the iOS app defaults to that new dashboard the integration created and does not respect my choice of another one.

**To Reproduce**

1. Install Minimalist UI with HACS
2. Set default dashboard to whatever you like
3. Close the iOS App
4. Open the iOS App
5. Your default dashboard is not respected and the dashboard that HACS integration creates will show.

**Expected behavior**
Whatever dashboard you choose as default for the device should be the one loading in when opening HA.

**Screenshots**
https://user-images.githubusercontent.com/9947929/150675118-c95be309-2ee6-4a75-824f-43fb5ba59cdc.mov
Here you can see. ”Start” is my own dashboard that is set to default on my device. ”Hem” is the dashboard the integration created.

**Additional context**
My config.yaml setup to my own Lovelace structure.
```
lovelace:
  mode: storage
  dashboards:
    lovelace-main:
      mode: yaml
      title: Start
      icon: mdi:home
      show_in_sidebar: false
      filename: lovelace-main.yaml
```
My lovelace-main.yaml file
```
# For future use!
ui_lovelace_minimalist: !include "custom_components/ui_lovelace_minimalist/lovelace/plugins/ui_lovelace_minimalist.yaml"

# Button cards location
button_card_templates: !include_dir_merge_named "custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: 'Start'
views: !include_dir_merge_list lovelace/views/
```
