### ISSUE TITLE
[Documentation] Including custom card card_scenes wrong documentation

### ISSUE THREAD

**Issue by Keyruu** [UI-Lovelace-Minimalist/UI#293]
**Describe the bug**
The documentation states that you should include the custom card card_scenes like this:
`template:
    - card_scenes`
But this doesn't work.
If you instead do it like this:
`template: card_scenes`
It works just fine.

This could be the case for other custom cards but I only tested this one.

https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_scenes/

**Comment by sildehoop** [comment]
What do you meen in the documentation it is like this:
```yaml
template:
  - card_scenes
```
```yaml
- type: "custom:button-card"
  template:
    - card_scenes
  variables:
    entity_1: "scene.YOUR_SCENE"
    entity_2: "scene.YOUR_SCENE"
    entity_3: "scene.YOUR_SCENE"
    entity_4: "scene.YOUR_SCENE"
    entity_5: "scene.YOUR_SCENE"
    name_1: "YOUR_NAME"
    name_2: "YOUR_NAME"
    name_3: "YOUR_NAME"
    name_4: "YOUR_NAME"
    name_5: "YOUR_NAME"
    icon_1: "mdi:YOUR_ICON"
    icon_2: "mdi:YOUR_ICON"
    icon_3: "mdi:YOUR_ICON"
    icon_4: "mdi:YOUR_ICON"
    icon_5: "mdi:YOUR_ICON"
    color_icon_1: "yellow"
    color_icon_2: "blue"
    color_icon_3: "purple"
    color_icon_4: "green"
    color_icon_5: "red"
    color_bg_1: "yellow"
    color_bg_2: "blue"
    color_bg_3: "purple"
    color_bg_4: "green"
    color_bg_5: "red"
```
