### ISSUE TITLE
Option to use MDI icons in chips

### ISSUE THREAD

**Issue by basbruss** [UI-Lovelace-Minimalist/UI#33]
The chips don't show the MDI icons when using the variables.
Only when using emoji's
```
- type: 'custom:button-card'
  template: chip_icon_state
  entity: group.denon
  variables: 
    ulm_chip_icon_state_icon: 'mdi:speaker-wireless'
    ulm_chip_icon_state_entity: sensor.denon_count
```
<img width="509" alt="Screen Shot 2021-11-09 at 11 32 40" src="https://user-images.githubusercontent.com/68892092/140908605-8d09cc83-c537-4266-b8cd-d08d39b48c38.png">
.

**Comment by Paddy0174** [comment]
That is intentional. :) The chips are, theoretically, only used in combination with emojis. But if there's a need for mdi-icons instead of emojis, I can take a look and see what we can come up with. Noted and on the to-do-list, but not on highest priority. 

I'll change the explanation in the wiki to reflect this issue and point out the differences. ;) 

On another task, where did you get these pictures for the person card? Is that kind of a generator or did you do these with Photoshop or something alike? Are you using this with dutch language? Would you mind sharing your language file, so we can include it in the main repo? Thanks!

**Comment by Paddy0174** [comment]
I just took a quick look, this should be doable, but it needs some "bigger" changes on the code. 

For the time being, this would be a quick and dirty solution for **your** layout. Not tested, just from the top of my head.
This is what you should have now:
```yaml
type: 'custom:button-card'
template: chip_icon_only
variables:
  ulm_chip_icon_only: '❤️'"
```
Try it with this for every `chip_icon_only` you want an mdi-icon to appear:
```yaml
type: 'custom:button-card'
template: chip_icon_only
variables:
  ulm_chip_icon_only: null
icon: 'mdi:face-man'
label: null
```
As I said, not a very clean way, but it should do the trick for now. :) Hope this helps a bit!
