### ISSUE TITLE
[Custom Card] Input Number breaks inside of Auto Entites

### ISSUE THREAD

**Issue by boardwarp** [UI-Lovelace-Minimalist/UI#350]
**Is your enhancement request related to a problem? Please describe.**
[Auto Entities](https://github.com/thomasloven/lovelace-auto-entities) allows most Minimalist UI cards to be configured in `include` > `options`. The `custom_card_input_number` card does not display correctly - it cannot be rendered through auto-entites when no entity is configured. Configuring an entity causes an additional row and column to appear with the entity appearing very condensed within the final cell. This issue does not occur when using the input number card outside of auto-entities, since it doesn't usually require the base entity configuration.

**Describe the solution you'd like**
Change `custom_card_input_number` to work with auto entities. I believe the simplest option is to modify the CSS in the input number template to hide the name, icon and label like so:

````
---
card_input_number:
  variables:
    ulm_card_input_number_name: "n/a"
  triggers_update: "all"
  styles:
    [...]
    name:
      - display: none
    icon:
      - display: none
    label:
      - display: none
````

**Describe alternatives you've considered**
Rebuilding the card to use the standard  image/name/label content fields (or the icon_info.yaml template which is where the functional MUI cards I've tested are templated from) should also work. I haven't tested this.

**Additional context**
Edited template on the left, unedited on the right:
![image](https://user-images.githubusercontent.com/10472218/151654481-72a249da-e940-4571-90fc-bb9d9b4e7e42.png)

Card template used in screenshots:
````
toms_light_group_stack:
  custom_fields:
    card:
      card:
        type: custom:auto-entities
        card:
          type: 'custom:fold-entity-row'
          show_header_toggle: false
          head:
            type: 'custom:button-card'
            template: toms_light_group_2
            variables:
              ulm_toms_light_group_room: "[[[ return variables.ulm_toms_light_stack_room ]]]"
        filter:
          include:
            - group: "[[[ return 'light.' + variables.ulm_toms_light_stack_room + '_lights' ]]]"
              options:
                type: "custom:button-card"
                template: card_light
                variables:
                  ulm_card_light_enable_slider: true
                  ulm_card_light_enable_collapse: true
                  ulm_card_light_enable_color: true
                  ulm_card_light_enable_popup: true
                  ulm_card_light_force_background_color: false
                  ulm_card_light_enable_horizontal: true
            - entity_id: "[[[ return 'input_number.' + variables.ulm_toms_light_stack_room + '_lights_timeout' ]]]"
              options:
                name: Timeout
                type: "custom:button-card"
                template:
                  - card_input_number
                variables:
                  ulm_card_input_number_name: "Timeout"
                  ulm_card_input_number_entity: "[[[ return 'input_number.' + variables.ulm_toms_light_stack_room + '_lights_timeout' ]]]"
````
