### ISSUE TITLE
Embedded energy distribution card no longer display after HACS migration

### ISSUE THREAD

**Issue by alelucc** [UI-Lovelace-Minimalist/UI#370]
Hi,
I am really enjoing this theme and the recent HACS integration is GREAT!! Great work!!

After the migration from the previous installation method to the HACS mode i am no longer able to display a "custom" card where i was displaying the new Home Assistant energy card.

```
- type: custom:button-card
              styles:
                grid:
                  - grid-template-areas: '"item1" "item2"'
                  - grid-template-columns: 1fr
                  - grid-template-rows: 25%  71%
                card:
                  - border-radius: var(--border-radius)
                  - box-shadow: var(--box-shadow)
                  - padding: 0px
                  - height: 105%
                custom_fields:
                  item1:
                    - padding-right: 50px
              custom_fields:
                item1:
                  card:
                    type: energy-date-selection
                item2:
                  card:
                    type: energy-distribution
                    link_dashboard: true
```

With the same code before the migration was working perfectly but now it is displaying this:

![image](https://user-images.githubusercontent.com/44071939/151873319-7d728fde-4647-4cd0-87cd-cedab60ab64a.png)

`Custom element doesn't exist: energy-date-selection`
`Custom element doesn't exist: energy-distribution`

These cards are normal Home Assistant cards that could be found [here](https://www.home-assistant.io/lovelace/energy/)
