### ISSUE TITLE
"Button-card template is missing" error

### ISSUE THREAD

**Issue by RakhmatovR** [UI-Lovelace-Minimalist/UI#384]
Hi there! Just installed the integration via HACS and currently trying to add some controls. Faced with such error while using custom cards:
```
Button-card template 'custom_card_tpx01_aircondition_with_buttons' is missing!

type: custom:button-card
template: custom_card_tpx01_aircondition_with_buttons
variables:
  entity: fan.bedroom_humidifier
  name: Humidifier
```

Shouldn't them be included already into integration?
