### ISSUE TITLE
card_binary_sensor_alert does not show state

### ISSUE THREAD

**Issue by filikun** [UI-Lovelace-Minimalist/UI#413]
**Describe the bug**
The main issue is that if you set `show_last_changed: false ` the card does not show any state in the label field. Also The documentation is wrong as if you are on the [card_binary_sensor_alert page](https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_binary_sensor_alert/) page it shows you the config for `card_binary_sensor` and vice versa.

**EDIT: It seems card_binary_sensor has the same problem.**

**Tested config**
```
    - type: 'custom:button-card'
      template: card_binary_sensor_alert
      name: Yterdörr
      variables:
        - ulm_card_binary_sensor_alert: true
      entity: binary_sensor.door_outdoor_magnet_contact
      show_last_changed: false
```

**How it looks**
![image](https://user-images.githubusercontent.com/9947929/153945916-248d82ef-bef8-465e-83fc-4e4ac1886ade.png)

**Expected look**
![image](https://user-images.githubusercontent.com/9947929/153945956-8a5baafc-2c49-4da5-bd16-50be855c9026.png)
