### ISSUE TITLE
SOLVED THEME Incorrect color on input_datetime when using darkmode

### ISSUE THREAD

**Issue by filikun** [UI-Lovelace-Minimalist/UI#45]
Hey so I figured out that if I use dark mode on my phone but chooses the light mode in HA UI input_datetime does not change. 

![signal-2021-11-23-114653_001](https://user-images.githubusercontent.com/9947929/143010981-ab333516-18fa-4223-b72d-e1b21e6d81af.jpeg)

**Comment by CM000n** [comment]
The question is which variable input_datetime uses for the color. Are you using the Home Assistant app or a browser? Does it not work with both?
Maybe this is a general Home Assistant / Home Assistant App problem?
Also, can you please share the code of the card you are using?
Unfortunately, I don't use input_datetime myself and need to build a test for that first. Does anyone else possibly also use the input_datetime and could support here?

**Comment by filikun** [comment]
Hey sorry for the slow answer. So what I can tell this only happens on mobile but is not tied to the mobile theme as even if I on desktop chooses the mobile theme it's still correctly displayed. 

Here's the code:
````
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      type: section
      label: Väckning
    open: true
    entities:
      - entity: input_datetime.morning_alarm
        name: När?
        icon: mdi:calendar
      - entity: input_boolean.wake_up
        name: Status
        icon: mdi:alarm
        title: Väckning
````
