### ISSUE TITLE
custom_card_afvalophaling not showing as it should be

### ISSUE THREAD

**Issue by cgilis** [UI-Lovelace-Minimalist/UI#475]
**Describe the bug**
If I add this card, I get this (see screenshot)
Did I do something wrong?

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="511" alt="CleanShot 2022-02-26 at 17 55 58@2x" src="https://user-images.githubusercontent.com/62599539/155851911-600ebba9-7cd7-4d18-b043-6158b511a9ae.png">

**Additional context**
```
- type: "custom:button-card"
  template:
    - card_afvalophaling
  variables:
    ulm_card_ophaling_vandaag: "sensor.recycleapp_recycle_vandaag"
    ulm_card_ophaling_morgen: "sensor.recycleapp_recycle_morgen"
    ulm_card_datum_gft: "sensor.recycleapp_recycle_gft"
    ulm_card_datum_pmd: "sensor.recycleapp_recycle_pmd"
    ulm_card_datum_rest: "sensor.recycleapp_recycle_restafval"
    ulm_card_datum_papier: "sensor.recycleapp_recycle_papier"
```

**Comment by AndyVRD** [comment]
Hi,

Have you seen/read the README.md? I mentioned that "This card can only be used if the integration "Home-Assistant-Sensor-Afvalbeheer" from pippyn is installed". :)

You can use this with other trash collection integrations but the output from these sensors can be different and will have another view in the card. You still can template your sensors to get the same output, example below.

```
sensor:
  - platform: template
    sensors:
      time_formatted_short:
        friendly_name: "sensor_date_short_recycle_today"
        value_template: "{{ as_timestamp(states('sensor.recycleapp_recycle_vandaag')) | timestamp_custom('%d-%m') }}"
```
