### ISSUE TITLE
Graph card does not use entity name by default

### ISSUE THREAD

**Issue by TheZoker** [UI-Lovelace-Minimalist/UI#478]
**Describe the bug**
The graph card does not use the entity name by default. It just shows `n/a` if nothing is specified.

**To Reproduce**
1. Create a graph card:
2. Don't set `ulm_card_graph_name`

**Expected behavior**
Take the entity name by default.

**Screenshots**
![image](https://user-images.githubusercontent.com/1368405/155863016-c769283f-d2b6-47e2-9338-6f7701abc3df.png)

**Additional context**
```yaml
- type: 'custom:button-card'
  template: card_graph
  variables:
    ulm_card_graph_entity: sensor.temperature_inside
    ulm_card_graph_type: fill
    ulm_card_graph_hours: 24
```
