### ISSUE TITLE
Cannot add carts to dashboard.

### ISSUE THREAD

**Issue by PrzemekSkw** [UI-Lovelace-Minimalist/UI#49]
Hello, I configure minimalist like in instructions and choose minimalist in theme. I see 2 tabs with `Welcome to UI-lovelace-minimalist` but cannot add any card. I don't see anything in logs.

Regards.

**Comment by CM000n** [comment]
Did you follow this tutorial and did you also install all necessary dependencies via HACS?
https://ui-lovelace-minimalist.netlify.app/installation/ui-mode

Can you share some screenshots and/or the code used in the configuration? Without this it is quite difficult to help you.

Maybe you can also try the .yaml mode. This is recommended anyway. It may seem a bit more complicated at the beginning, but it is definitely easier in the long run.

**Comment by PrzemekSkw** [comment]
Hi @CM000n I follow yaml-mode because it's reccomended. My configuration.yaml is like example:
```
#====================
#   Themes
#====================
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  # Add yaml dashboards
  dashboards:
    lovelace-minimalist:
      mode: yaml
      title: Minimalist
      icon: mdi:script
      show_in_sidebar: true
      filename: lovelace-minimalist.yaml
```
I add file `lovelace-minimalist.yaml` in my `/homeassistant/` folder and paste content from tutorial.
I see now I don't have ha-slider-card. I have slider-button-card because only that is in HACS.
Regards.

**Comment by bavo** [comment]
@PrzemekSkw 
Can you close this issue if you problem was resolved? 
Otherwise can you post the new errors after adding both cards to HACS?

Thx 🙂

**Comment by PrzemekSkw** [comment]
Hi, my minimalist theme still don't work
![Zrzut ekranu z 2021-12-01 13-38-19](https://user-images.githubusercontent.com/25219988/144236394-53a1e46b-1f45-43e4-a72e-188b1b73c535.png)
![Zrzut ekranu z 2021-12-01 13-38-25](https://user-images.githubusercontent.com/25219988/144236397-93cde407-158a-499b-90a0-848192be394b.png)
![Zrzut ekranu z 2021-12-01 13-39-04](https://user-images.githubusercontent.com/25219988/144236400-dc272b8a-1268-46e3-8358-320a9dc95cb3.png)
as You see on the last screenshoot I have some notification but no error. I see notification also from HA on the left down corner that saved successful after I click OK on that top notification.
Regards.

**Comment by CM000n** [comment]
Sorry, but that looks like Polish or a similar language to me? Unfortunately, I don't understand this language and can't do much with the screenshots.

But as far as I can tell, it's showing you a connection problem with your "`*.ddns.net`" address? That should have nothing to do with the theme itself.

Can you still share the code for your lovelace-minimalist.yaml? Currently it just looks to me like there are no cards defined in it yet.

**Comment by PrzemekSkw** [comment]
Hi, there's only `Notification from site *.ddns.net` I can choose minimalist-desktop for my dashboard but it looks like default. My `lovelace-minimalist.yaml` is the same as example:
```
button_card_templates: !include_dir_merge_named minimalist-templates/
views:
  - title: Minimalist
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Welcome to UI-Lovelace-Minimalist
          - type: custom:button-card
            template: edge
  - title: Minimalist page 2
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: UI-Lovelace-Minimalist second page
          - type: custom:button-card
            template: edge
```
Regards.

**Comment by PrzemekSkw** [comment]
I have change that file now:
```
button_card_templates: !include_dir_merge_named minimalist-templates/
views:
  - title: Minimalist
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: chip_temperature
            variables:
              ulm_chip_temperature_inside: sensor.pokoj_emilki_temperature_humidity_sensor_temperature
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Welcome to UI-Lovelace-Minimalist
          - type: custom:button-card
            template: edge
```
and after reboot and clear chache I have that error on Minimalist tab:

![Zrzut ekranu z 2021-12-02 10-10-23](https://user-images.githubusercontent.com/25219988/144392484-c280a3a5-bb34-4971-bcbb-d86a6a210bfb.png)

**Comment by CM000n** [comment]
I'm not surprised. 😋 The `chip_temperature` template needs all three specifications. 
```
  variables:
    ulm_chip_temperature_inside: sensor.my_temperature_sensor_inside
    ulm_chip_temperature_outside: sensor.my_temperature_sensor_outside
    ulm_chip_temperature_weather: weather.my_weather_provider"
```

However, you have specified only one sensor for the indoor temperature. That's why in your screenshot you get the error message that it doesn't find an entity for the weather.

**Comment by PrzemekSkw** [comment]
I add that as You put here and I still have that error. I restart, clear browser cache.
My file looks that:
```button_card_templates: !include_dir_merge_named minimalist-templates/
views:
  - title: Minimalist
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: chip_temperature
            variables:
              ulm_chip_temperature_inside: sensor.my_temperature_sensor_inside
              ulm_chip_temperature_outside: sensor.my_temperature_sensor_outside
              ulm_chip_temperature_weather: weather.my_weather_provider" 
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Welcome to UI-Lovelace-Minimalist
          - type: custom:button-card
            template: edge
```
Regards.

**Comment by CM000n** [comment]
What are you doing 😀 Please look at your config again. 
What I posted was just the example from the documentation. You have to put your sensors and your weather entity in the code, of course, that actually exist 😉.

**Comment by PrzemekSkw** [comment]
I add my sensor first time. 
`ulm_chip_temperature_inside: sensor.pokoj_emilki_temperature_humidity_sensor_temperature`
I'm not programmer and I really don't know what to do with that.
Regards.

**Comment by CM000n** [comment]
You need 3 sensors for this chip template:

1 for your inside temperature.
1 for your outside temperature.
1 weather entity for your local weather.

**Comment by PrzemekSkw** [comment]
What if I don't need this sensors and want to add my own?

**Comment by CM000n** [comment]
Then you can't use the `chip_temperature` template, because you have to specify the three sensors mentioned above.
If you want a template for a temperature chip that needs less sensors, then you have to either go a bit deeper into coding to make your own custom template. Or you open a new issue, so that the developers make the required sensors for the `chip_temperature` template optional in the future.

But all in all, this has nothing to do with the issue you opened here. As far as I can tell, you could easily add cards to the dashboard.
So far, you have simply added cards with incorrect or insufficient data.


Let's try something simple and use this code for your dashboard:
```
button_card_templates: !include_dir_merge_named minimalist-templates/
views:
  - title: Minimalist
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Welcome to Przemek's Home Dashboard
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: card_generic
            entity: sensor.pokoj_emilki_temperature_humidity_sensor_temperature
          - type: custom:button-card
            template: edge
```
Notice: I simply replaced the `chip_temperature` template with a template for `card_generic`, which only needs one sensor as a specification.
