### ISSUE TITLE
Vertical Button for Navigation

### ISSUE THREAD

**Issue by sjoshua270** [UI-Lovelace-Minimalist/UI#520]
**Is your enhancement request related to a problem? Please describe.**
I would like to use vertical buttons for navigation, but there is only the option to use a vertical button for input_boolean and input_select. Any other config doesn't appear in the UI
I've tried:

    - type: custom:button-card
      template: card_vertical_button
      name: Home
      tap_action:
        action: navigate
        navigation_url: /ui-lovelace-minimalist/home
      variables:
        ulm_card_vertical_button_state:
        ulm_card_vertical_button_color: blue

With no luck

**Describe the solution you'd like**
A really simple template which actually follows the guidelines outlined in the vertical cards section of the Development section of the [Wiki](https://ui-lovelace-minimalist.github.io/UI/development/card_style_guide/#vertical-buttons).

**Comment by sjoshua270** [comment]
Wow... It really looks like the only missing part was the entity. Thank you! What a weird thing to crash on, when it shouldn't even need an entity

**Comment by sjoshua270** [comment]
> It's possible. First of all you need to add an entity to a card. This allows to render all parts like the icon of the card. Second your tap_action should have a `navigation_path:`. 😉
> 
> ```yaml
> - type: custom:button-card
>   template: card_vertical_button
>   name: Home
>   entity: climate.home   ## could be anything
>   tap_action:
>     action: navigate
>     navigation_path: home
>   variables:
>     ulm_card_vertical_button_state:
>     ulm_card_vertical_button_color: blue
> ```

Could you help me with one other thing? It looks like the color doesn't apply. I'm assuming that is because the entity I'm using (`weather.openweathermap` is just the random entity I chose) is not "on" or "true". Is there some yaml I can apply to the card to "enable" it to show my chosen color, or do I need to pick an entity with an "always true" condition?

**Comment by basbruss** [comment]
> > It's possible. First of all you need to add an entity to a card. This allows to render all parts like the icon of the card. Second your tap_action should have a `navigation_path:`. 😉
> > ```yaml
> > - type: custom:button-card
> >   template: card_vertical_button
> >   name: Home
> >   entity: climate.home   ## could be anything
> >   tap_action:
> >     action: navigate
> >     navigation_path: home
> >   variables:
> >     ulm_card_vertical_button_state:
> >     ulm_card_vertical_button_color: blue
> > ```
> 
> Could you help me with one other thing? It looks like the color doesn't apply. I'm assuming that is because the entity I'm using (`weather.openweathermap` is just the random entity I chose) is not "on" or "true". Is there some yaml I can apply to the card to "enable" it to show my chosen color, or do I need to pick an entity with an "always true" condition?

Your weather entity is a hard one to use. It's on of the types of entities that can have the most different states.
If you want always the same color just add a style to your card which is not state dependent.
```yaml
- type: custom:button-card
  template: card_vertical_button
  name: Home
  entity: climate.home   ## could be anything
  tap_action:
    action: navigate
    navigation_path: home
  variables:
    ulm_card_vertical_button_state:
    ulm_card_vertical_button_color: blue
  style:
    icon:
      - color: "[[[ return `rgba(var(--color-${variables.ulm_card_vertical_button_color}), 1)`; ]]]"
    label:
      - color: "[[[ return `rgba(var(--color-${variables.ulm_card_vertical_button_color}-text), 1)`; ]]]"
    name:
      - color: "[[[ return `rgba(var(--color-${variables.ulm_card_vertical_button_color}-text), 1)`; ]]]"
    img_cell:
      - background-color: "[[[ return `rgba(var(--color-${variables.ulm_card_vertical_button_color}), 0.2)`; ]]]"
    card:
      - background-color: "[[[ return `rgba(var(--color-background-${variables.ulm_card_vertical_button_color}), var(--opacity-bg))`; ]]]"
```
And when you want a certain state to have a color fill in the first variable.
