### ISSUE TITLE
Empty space/placeholder for uneven rows

### ISSUE THREAD

**Issue by orestesgaolin** [UI-Lovelace-Minimalist/UI#55]
Is there a way to put some kind of placeholder into the horizontal stack, so that cards fill 50% of the available space?

Please have a look at the dashboard on the left, and the expected layout on the right. I'd like the "Biuro" slider to occupy only half of the row.

| Before | After |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/16854239/144299208-67fa6f5e-35b8-4584-b3ec-60c12f2a7f37.png) | ![CleanShot 2021-12-01 at 20 18 35](https://user-images.githubusercontent.com/16854239/144299381-acecfbd7-974d-4627-b70f-735b8bdf4510.png) |
 

```yaml
button_card_templates: !include_dir_merge_named minimalist-templates/
views:
  - title: Home
    cards:
      - type: vertical-stack
        cards:
          - type: custom:button-card
            template: title
            name: Music
          - type: entities
            entities:
              - type: custom:mini-media-player
                group: true
                name: " "
                hide:
                  icon: true
                  source: true
                  progress: true
                  controls: true
                  volume: true
                speaker_group:
                  platform: media_player
                  show_group_count: false
                  expanded: false
                  entities:
                    - entity_id: media_player.kuchnia
                      name: Kitchen
                    - entity_id: media_player.lazienka
                      name: Bathroom
                    - entity_id: media_player.pokoj_dzienny
                      name: Living room
                artwork: none
                tts: false
                info: scroll
                volume_stateless: false
                entity: media_player.kuchnia
            show_header_toggle: false

      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_slider_generic
            entity: media_player.kuchnia
            variables:
              ulm_card_slider_name: Kuchnia
          - type: custom:button-card
            template: card_slider_generic
            entity: media_player.lazienka
            variables:
              ulm_card_slider_name: Łazienka
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: card_slider_generic
            entity: media_player.pokoj_dzienny
            variables:
              ulm_card_slider_name: Biuro

      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            template: card_script
            variables:
              ulm_card_script_title: Nowy Świat
              ulm_card_script_icon: "mdi:radio"
            tap_action:
              action: call-service
              service: script.play_radio
              service_data:
                selected_preset: 1
          - type: "custom:button-card"
            template: card_script
            variables:
              ulm_card_script_title: Radio 357
              ulm_card_script_icon: "mdi:radio"
            tap_action:
              action: call-service
              service: script.play_radio
              service_data:
                selected_preset: 2
          - type: "custom:button-card"
            template: card_script
            variables:
              ulm_card_script_title: Spotify
              ulm_card_script_icon: "mdi:spotify"
            tap_action:
              action: call-service
              service: media_player.select_source
              service_data:
                entity_id: media_player.kuchnia
                source: spotify

```

And `card_slider_generic` is just the modified light slider card:

```yaml
card_slider_generic:
  template:
    - ulm_language_variables
  variables:
    ulm_card_slider_name: "[[[ return entity.attributes.friendly_name ]]]"
    icon: "[[[ return entity.attributes.icon ]]]"
  show_icon: false
  show_name: false
  show_label: false
  state:
    - operator: template
      value: "[[[ return entity.state == 'on' ]]]"
      styles:
        card:
          - background-color: "rgba(var(--color-background-yellow),var(--opacity-bg))"
  styles:
    grid:
      - grid-template-areas: '"item1" "item2"'
      - grid-template-columns: 1fr
      - grid-template-rows: min-content min-content
      - row-gap: 12px
    card:
      - border-radius: var(--border-radius)
      - box-shadow: var(--box-shadow)
      - padding: 12px
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        template:
          - icon_info
          - yellow_slider
        entity: "[[[ return entity.entity_id ]]]"
        tap_action:
          action: toggle
        label: >-
          [[[
            if (entity.state !='unavailable'){
              if (entity.state =='off'){
                return variables.ulm_off;
              } else if (entity.state == 'on'){
                if (entity.attributes.brightness != null){
                  var bri = Math.round(entity.attributes.brightness / 2.55);
                  return (bri ? bri : '0') + '%';
                } else {
                  return variables.ulm_on
                }
              }
            } else {
              return variables.ulm_unavailable;
            }
          ]]]
        name: "[[[ return variables.ulm_card_slider_name ]]]"
        styles:
          card:
            - box-shadow: none
            - border-radius: var(--border-radius) var(--border-radius) var(--border-radius) var(--border-radius)
            - padding: 0px
    item2:
      card:
        type: "custom:my-slider"
        entity: "[[[ return entity.entity_id ]]]"
        radius: 14px
        height: 42px
        mainSliderColor: rgba(var(--color-yellow),1)
        secondarySliderColor: rgba(var(--color-yellow),0.2)
        mainSliderColorOff: rgba(var(--color-theme),0.05)
        secondarySliderColorOff: rgba(var(--color-theme),0.05)
        thumbHorizontalPadding: "0px"
        thumbVerticalPadding: "0px"
        thumbWidth: 0px
        card_mod:
        style: |
          ha-card {
            border-radius: 14px;
            box-shadow: none;
          }
```
