### ISSUE TITLE
Cards can't be aligned to left or right

### ISSUE THREAD

**Issue by drfinn15** [UI-Lovelace-Minimalist/UI#557]
**Describe the bug**
For every card I add, it is not possible to align it to the left or right side on my dashboard (Screenshot 2). As an example, I used the code from the [website](https://ui-lovelace-minimalist.github.io/UI/usage/layout/). As you can see on the screenshot 1 below, it renders always a block on the left and right side, which does only allow to arrange the cards between them. Tested on my PC and Samsung Galaxy Tab A.

**To Reproduce**

1. Look at the attached code snippet
2. Paste it into /config/ui_lovelace_minimalist/dashboard/ui-lovelace.yaml
3. Reload UI Lovelace Minimalist
4. Have a look on the dashboard.

**Expected behavior**
Chip card is aligned to the right.

**Screenshots**
(1)
![image](https://user-images.githubusercontent.com/81082169/160395398-85a364df-c076-4aa0-811c-6914412d13ff.png)
(2)
![image](https://user-images.githubusercontent.com/81082169/160396003-b52279de-dd06-4cbd-b9ba-6d26cc15d4c5.png)

**Additional context (Config)**
```
---
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: "var(--background-image)"   
views: 
  - title: "Startseite"
    path: 0
    icon: "mdi:home"
    cards:
      - type: "horizontal-stack"
        cards:
          - type: "custom:button-card"
            color_type: blank-card
          - type: custom:button-card 
            template: chip_icon_label
            label: Your right card here
```
