### ISSUE TITLE
How to hide custom item on a card based on condition?

### ISSUE THREAD

**Issue by orestesgaolin** [UI-Lovelace-Minimalist/UI#56]
I have a custom slider card based on the light slider. Is there a way to hide the slider item when the given entity state is `off`?

<img width="250" alt="CleanShot 2021-12-01 at 21 43 25@2x" src="https://user-images.githubusercontent.com/16854239/144310964-bfc88e3f-0ce8-4dac-8e2d-fec62cacd515.png">

<img width="505" alt="CleanShot 2021-12-01 at 21 43 32@2x" src="https://user-images.githubusercontent.com/16854239/144310980-0150bbec-42aa-408a-bfb6-6ce71a832d9f.png">

```yaml
card_slider_generic:
  template:
    - ulm_language_variables
  variables:
    ulm_card_slider_name: "[[[ return entity.attributes.friendly_name ]]]"
    icon: "[[[ return entity.attributes.icon ]]]"
  show_icon: false
  show_name: false
  show_label: false
  state:
    - operator: template
      value: "[[[ return entity.state == 'on' ]]]"
      styles:
        card:
          - background-color: "rgba(var(--color-background-yellow),var(--opacity-bg))"
  styles:
    grid:
      - grid-template-areas: '"item1" "item2"'
      - grid-template-columns: 1fr
      - grid-template-rows: min-content min-content
      - row-gap: 12px
    card:
      - border-radius: var(--border-radius)
      - box-shadow: var(--box-shadow)
      - padding: 12px
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        template:
          - icon_info
          - yellow_slider
        entity: "[[[ return entity.entity_id ]]]"
        tap_action:
          action: toggle
        label: >-
          [[[
            if (entity.state !='unavailable'){
              if (entity.state =='off'){
                return variables.ulm_off;
              } else if (entity.state == 'on'){
                if (entity.attributes.brightness != null){
                  var bri = Math.round(entity.attributes.brightness / 2.55);
                  return (bri ? bri : '0') + '%';
                } else {
                  return variables.ulm_on
                }
              }
            } else {
              return variables.ulm_unavailable;
            }
          ]]]
        name: "[[[ return variables.ulm_card_slider_name ]]]"
        styles:
          card:
            - box-shadow: none
            - border-radius: var(--border-radius) var(--border-radius) var(--border-radius) var(--border-radius)
            - padding: 0px
    item2:
      card:
        type: "custom:my-slider"
        entity: "[[[ return entity.entity_id ]]]"
        radius: 14px
        height: 42px
        mainSliderColor: rgba(var(--color-yellow),1)
        secondarySliderColor: rgba(var(--color-yellow),0.2)
        mainSliderColorOff: rgba(var(--color-theme),0.05)
        secondarySliderColorOff: rgba(var(--color-theme),0.05)
        thumbHorizontalPadding: "0px"
        thumbVerticalPadding: "0px"
        thumbWidth: 0px
        card_mod:
        style: |
          ha-card {
            border-radius: 14px;
            box-shadow: none;
          }
```

**Comment by damianeickhoff** [comment]
Maybe the given entity has no 'on' or 'off' state? Not sure if that could be the problem? Just think along with you :)

**Comment by rphlwnk** [comment]
You have to use the `card_light_slider_collapse` template - this will collapse the slider when the light is turned off.

**Comment by damianeickhoff** [comment]
@rphlwnk is right, I thought the code was a exact copy of the `card_light_slider_collapse` but its from the `card_light_slider`.

Maybe its enough to add this underneath card in item2.

```
        type: conditional
        conditions:
          - entity: "[[[ return entity.entity_id ]]]"
            state: 'on'
```
