### ISSUE TITLE
custom_card_imswel_person card not showing popup

### ISSUE THREAD

**Issue by vandenbogerd** [UI-Lovelace-Minimalist/UI#561]
browser_mod is working fine in my installation, but for "custom_card_imswel_person" it doesn't show the popup as intended

Edit: the same goes for the "Thermostat popup"...

**Comment by JoshSald** [comment]
Having the same issue

**Comment by FlyingPersian** [comment]
I have the same issue. The fix mentioned above worked, but then I had to manually re-install all the custom cards needed. I did so and now the popup isn't working again. Also, the language is in polish now. It just shows my name, picture and "W domu" (= home in polish).

I have the following Frontend components installed:

- button-card
- simple weather card
- auto-entities
- mini-graph-card
- mini media player
- light entity card
- card-mod (lovelace-card-mod)
- my cards bundle (my-slider)

I have the following integrations installed:

- browser_mod
- UI Lovelace Minimalist
- HACS

Here my ui-lovelace.yaml:
```
---
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "UI Lovelace Minimalist"
theme: "minimalist-desktop"
background: "var(--background-image)"
# views: !include_dir_merge_list "views/"
views:
  - title: "Example View"
    path: 0
    icon: "mdi:flower"
    cards:
      - type: "vertical-stack"
        cards:
        - type: "custom:button-card"
          template: custom_card_imswel_person
          variables:
            ulm_card_imswel_person_entity: person.test
            ulm_card_imswel_person_wifi_tracker: device_tracker.oneplus8 #WiFi tracking via my router
            ulm_card_imswel_person_gps_tracker: device_tracker.oneplus_8_app #HA companion app
            ulm_card_imswel_person_findmy_script: script.find_my_oneplus_6t #a script that sends a message via telegram
            ulm_card_imswel_person_use_entity_picture: true
            ulm_card_imswel_person_zones: 
              - zone.home
```
