### ISSUE TITLE
Light Popup Card doesnt work properly

### ISSUE THREAD

**Issue by Markobu98** [UI-Lovelace-Minimalist/UI#564]
Hey today I installed and setup lovelace minimalist ui. So far it works almost perfect. However I tried to create a light popup card. The card does show up but the hold action doesnt bring up the menu. What did I do wrong?

**To Reproduce**

1. I added the template code
2. Changed the entity to my light entity
3. Card shows up but hold action downst work

![image](https://user-images.githubusercontent.com/72013479/160895972-36343079-62f3-4da6-aef8-84e2588f3026.png)

The code I added:

```
- type: "custom:button-card"
   template:
       - card_light
         entity: light.light_bars
         variables:
         ulm_card_light_enable_popup: true
```

**Comment by basbruss** [comment]
Hi,

Is your code exactly like you posted it here?
If so the indentation is wrong. It should be like:
```yaml
 - type: "custom:button-card"
   template:
     - card_light
   entity: light.light_bars
   variables:
     ulm_card_light_enable_popup: true
```
