### ISSUE TITLE
Custom element doesn't exist: my-slider

### ISSUE THREAD

**Issue by paulius2k** [UI-Lovelace-Minimalist/UI#568]
**Describe the bug**
I just installed this theme and am using the default dashboard `ui-lovelace.yaml`.
This part part of the configuration:
```
          - type: "custom:auto-entities"
            card:
              type: "grid"
              columns: 2
              square: false
            card_param: "cards"
            sort:
              count: 4
            filter:
              include:
                - domain: "light"
                  options:
                    type: "custom:button-card"
                    template: "card_light"
                    variables:
                      ulm_card_light_enable_slider: true
                      ulm_card_light_enable_color: true
                      ulm_card_light_enable_popup: true
```
gives an error for me:
<img src="https://user-images.githubusercontent.com/24705262/161081130-4db20c4e-a2b3-443b-aac8-4869467cbdc5.png" width=30%>

when I change to `false`:
```
                    variables:
                      ulm_card_light_enable_slider: false
```
the error is not there anymore:
<img src="https://user-images.githubusercontent.com/24705262/161081606-62ceed07-7705-4de9-a80a-91511c5c3041.png" width=30%>

Q:
How can I install the missing element?

**To Reproduce**

1. Open the default dashboard `ui-lovelace.yaml`

**Expected behavior**
No Error should be thrown.
