### ISSUE TITLE
Light Card does not work with group

### ISSUE THREAD

**Issue by schoenwaldnils** [UI-Lovelace-Minimalist/UI#579]
When using a **light group** with `template: card_light` I get an infinite error (see screenshot)

**To Reproduce**

1. Create a group with light entities
2. Use the group in card_light

**Expected behavior**
To be able to use the light card for the group

**Screenshots**
Error: 
![Screen-Shot-2022-04-04-10-07-22 81](https://user-images.githubusercontent.com/2837064/161501770-b96a72ac-4f7b-4fbf-a31e-97e29ee7de59.png)

Working entity in lovelace:
![192 168 178 11_8123_ui-lovelace-minimalist_0 (1)](https://user-images.githubusercontent.com/2837064/161502566-571b83b6-ae36-4af4-9468-141681f17380.png)
![192 168 178 11_8123_ui-lovelace-minimalist_0](https://user-images.githubusercontent.com/2837064/161502587-1454a2c3-4393-4fb8-8b74-da057c9e63df.png)

**Comment by basbruss** [comment]
Hi,

Does your group entity looks like: `group.lights` or `light.group`?

**Comment by basbruss** [comment]
So as I mentioned `group.lights_nils` is not fully supported. To get full support for light groups take a look on this page https://www.home-assistant.io/integrations/light.group/ This will create an entity `light.lights_nils`.
Light groups do work differently than other groups in HA.
If you put this in your configuration.yaml or convert it to work with packages will solve the issue:
```yaml
# Example configuration.yaml entry
light:
  - platform: group
    name: Lights Nils
    entities:
      - light.hue_play_1
      - light.hue_play_2
      - light.bulb02_color
      - light.bulb03_color
 ```
