### ISSUE TITLE
Popup cards not working

### ISSUE THREAD

**Issue by bbcorp** [UI-Lovelace-Minimalist/UI#581]
## Describe the bug
Any of the popup cards won't work 
## To Reproduce

1. Install UI Minimalist via HACS
2. Install UI Minimalist integration with all options checked
3. Set themes in configuration.yaml :
```
frontend:
  themes: !include_dir_merge_named themes
```
4. Select theme "minimalist-desktop" in user configuration
5. Install browsermod via HACS
6. Activate browsermod by adding this to configuration.yaml
`browser_mod:`
7. Installed My Cards Bundle aka slider-card and Light Entity Card via HACS

![Peek 05-04-2022 16-09](https://user-images.githubusercontent.com/11371274/161775442-b3465ad0-6f2a-4a52-b276-859865c980f7.gif)

## Expected behavior
Show pop up card, light or climate for example
## Additional context
Browsermod seems to be activated as I have it on my browser console :
![HA_ui_minimalist](https://user-images.githubusercontent.com/11371274/161775908-a2ccb5fc-2c51-4d61-9a5c-1f92804aa2e6.png)
## Code
```
        cards:
          - type: "custom:button-card"
            template:
              - card_power_outlet
              - popup_power_outlet
            entity: switch.prise_chargeur
            name: Prise téléphone
          - type: "custom:button-card"
            template: 
              - card_light
            entity: light.bureau
            variables:
              ulm_card_light_enable_slider: true
              ulm_card_light_enable_collapse: true
              ulm_card_light_enable_popup: true
          - type: "custom:button-card"
            template:
              - card_media_player
            entity: media_player.freebox_player_pop
            variables:
              ulm_card_media_player_enable_popup: true
          - type: "custom:button-card"
            template: card_thermostat
            entity: climate.thermostat
            variables:
              ulm_card_thermostat_enable_popup: true
```
