### ISSUE TITLE
incorrect template

### ISSUE THREAD

**Issue by saethone** [UI-Lovelace-Minimalist/UI#59]
on the graph card, you call the template "icon_info" which doesn't exist. I believe it should be "icon_info_bg" but i didn't spend a lot of time figuring out which icon_info_* template it's meant to use

**Comment by rphlwnk** [comment]
The template `icon_info` does exist (https://github.com/UI-Lovelace-Minimalist/UI/blob/main/config/minimalist-templates/button_card_templates.yaml#L1280) and graph card works as expected on my site:

```                
- type: 'custom:button-card'
  template: card_graph
  variables:
    ulm_card_graph_color: "var(--google-green)"
    ulm_card_graph_name: Bedroom
    ulm_card_graph_entity: `sensor.weather_bedroom_temperature
```


![image](https://user-images.githubusercontent.com/34039879/144497666-0ad45327-40ee-4c9c-9aaf-247140088b09.png)

Maybe re-download the **button_card_templates.yaml** file
