### ISSUE TITLE
card_welcome and card_navigate review needed

### ISSUE THREAD

**Issue by Paddy0174** [UI-Lovelace-Minimalist/UI#6]
Could someone please check these two cards? 

Are both cards ok design wise? I'm a design-dislexic and I could use some input, if these are ok to publish.

Thanks!

**Comment by KaherdinTristan** [comment]
In my setup, the garbage info also shows when the sensor last was updated. That's not necessary...

**Comment by Paddy0174** [comment]
@KaherdinTristan 
Hard to say without the code or a screen shot, but I'd bet on these settings:
```yaml
ulm_custom_card_paddy_welcome_news_entities:
  - entity: sensor.waste_collection_paper
    content_template: "{{display_name}}{{state}}"
  - entity: sensor.waste_collection_waste
    content_template: "{{display_name}}{{state}}"
```
The content template defines how things show, and with these entries there shouldn't be any time settings like an updated timestamp.
