### ISSUE TITLE
Chip Navigation Emoji

### ISSUE THREAD

**Issue by damianeickhoff** [UI-Lovelace-Minimalist/UI#60]
Is it possible to give a emoji to a Navigation Chip? For now, only a MDI will work.

When giving a card the Navigation Template and the Icon Only template, it shows the Emoji, but the margin is off.

```
          - type: 'custom:button-card'
            template:
              - chip_icon_only
              - chip_navigate
            variables:
              ulm_chip_navigate_path: verlichting
              ulm_chip_icon_only: '💡'  
```
This is what it looks like.

![afbeelding](https://user-images.githubusercontent.com/12126826/144389761-dc5586f4-b112-446c-ba6d-17b8968e3239.png)

**Comment by damianeickhoff** [comment]
Looks like I already fixed it with a edited template:

```
chip_icon_state_navigate:
  template: chips
  triggers_update:
    - "[[[ variables.ulm_chip_icon_state_entity ]]]"
  tap_action:
    action: navigate
    navigation_path: "[[[ return variables.ulm_chip_navigate_path; ]]]"    
  label: |
    [[[
      var icon = '❔';
      if (variables.ulm_chip_icon_state_icon){
        var icon = variables.ulm_chip_icon_state_icon;
      } 
      var state = '';
      if (states[variables.ulm_chip_icon_state_entity].state){
        var state = states[variables.ulm_chip_icon_state_entity].state;
      } 
      return icon + ' ' + state;
    ]]]
```

Card:
```
          - type: 'custom:button-card'
            template:
              - chip_icon_state_navigate
            variables:
              ulm_chip_navigate_path: verlichting
              ulm_chip_icon_state_icon: '💡'
              ulm_chip_icon_state_entity: sensor.current_lights_on
```

![afbeelding](https://user-images.githubusercontent.com/12126826/144390579-952c914a-6d41-4952-894a-86aa4a469cf9.png)

But also, as mentioned in #35 the state doenst update unless a page reload.
