### ISSUE TITLE
plz add chinese translation

### ISSUE THREAD

**Issue by yangtfu** [UI-Lovelace-Minimalist/UI#627]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

```yaml
---
ulm_language_variables:
  variables:
    ulm_on: "开"
    ulm_off: "关"
    ulm_open: "打开"
    ulm_closed: "关闭"
    ulm_unavailable: "不可用"
    ulm_standby: "待机"
    ulm_idle: "空闲"
    ulm_currency: "￥"
    ulm_auto: "自动"
    ulm_heat: "加热"
    ulm_cool: "制冷"
    ulm_dry: "抽湿"
    ulm_fan_only: "排风"
    ulm_heat_cool: "加热/制冷"
    ulm_heating: "加热中"
    ulm_cooling: "制冷中"
    ulm_person_state_home: "在家"
    ulm_person_state_away: "离开"
    ulm_person_state_not_home: "离家"
    ulm_device_state_home: "在家"
    ulm_device_state_not_home: "离家"
    ulm_popups_back: "返回"
    ulm_popups_toggle: "切换"
    ulm_popups_statistics: "统计"
    ulm_popups_history: "历史"
    ulm_popups_brightness: "亮度"
    ulm_popups_color_temp: "色温"
    ulm_popups_color: "颜色"
    ulm_unknown: "未知"
    ulm_alarm_armed_home: "在家警戒"
    ulm_alarm_armed_away: "离家警戒"
    ulm_alarm_armed_night: "夜间警戒"
    ulm_alarm_disarmed: "解除警戒"
    ulm_alarm_arming: "正在开启警戒"
    ulm_alarm_triggered: "已激活"
    ulm_playing: "播放中"
    ulm_paused: "已暂停"
    ulm_updates_available: "有更新!"
    ulm_no_updates_available: "无更新"
    ulm_morning: "早上好"
    ulm_afternoon: "下午好"
    ulm_evening: "晚上好"
    ulm_hello: "你好"
    ulm_cleaning: "清洁中"
    ulm_returning: "返回中"
    ulm_docked: "充电中"
    ulm_mopping: "擦地中"
```
