### ISSUE TITLE
Nas card doesnt work

### ISSUE THREAD

**Issue by NWalledge** [UI-Lovelace-Minimalist/UI#640]
**Describe the bug**
The nas card for me just shows a state saying off in a box. whatever i do it wont change

**To Reproduce**

install nas custom card and use

**Expected behavior**

**Screenshots**
[]
![Screenshot_20220504-234112_Home_Assistant](https://user-images.githubusercontent.com/46450157/167018413-e42c1da6-74b2-417a-8ef8-4dc5e5555504.jpg)

**Additional context**

**Comment by Eltarius** [comment]
Hi,

Try this, edit \config\ui_lovelace_minimalist\custom_cards\custom_card_nas\custom_card_nas.yaml with this code:
```
---
custom_card_nas:
  template:
    - "blue_no_state"
  tap_action:
    action: "more-info"
  show_label: true
  show_name: true
  show_icon: true
  label: |-
    [[[
        return variables.ulm_custom_card_nas_text + " " + states[variables.ulm_custom_card_nas_sensor].state + variables.ulm_custom_card_nas_unit;
    ]]]
  icon: |-
      [[[
          return "mdi:nas";
      ]]]
  name: |-
      [[[ 
          return "Nas";
      ]]]
  size: "20px"
  styles:
    card:
      - border-radius: "20px"
      - box-shadow: "var(--box-shadow)"
      - padding: "12px"
    img_cell:
      - border-radius: "50%"
      - place-self: "center"
      - width: "42px"
      - height: "42px"
    name:
      - align-self: "end"
      - justify-self: "start"
      - font-weight: "bold"
      - font-size: "14px"
      - margin-left: "12px"
      - filter: "opacity(100%)"
    label:
      - justify-self: "start"
      - align-self: "start"
      - font-weight: "bolder"
      - font-size: "12px"
      - filter: "opacity(40%)"
      - margin-left: "12px"
    grid:
      - grid-template-areas: "'i n' 'i l'"
      - grid-template-columns: "min-content auto min-content"
      - grid-template-rows: "min-content min-content"
```

I clean this code, and I push a commit soon. ;)
