### ISSUE TITLE
Slider buttons gone in light mode for tapbar themes

### ISSUE THREAD

**Issue by adabelleleiram** [UI-Lovelace-Minimalist/UI#647]
I've noticed this in more info for lights. Both the brightness and temperature slider buttons are missing when the tapbar themes (both ios and mobile) are in light mode. See this comparison between dark and light:
![Screenshot_20220506-201028](https://user-images.githubusercontent.com/28298971/167195184-19654d76-a579-4324-a886-a2e515e5ef6d.png)
![Screenshot_20220506-201044](https://user-images.githubusercontent.com/28298971/167195194-826785c0-990f-4907-8274-ef98fd27ab89.png)

The functionality still works though so it just seems to be a graphical bug.

**Comment by MichaelBrunn3r** [comment]
I encoutered the same problem. Everyhthing works with the similar theme "minimalist-mobile", only "minimalist-mobile-tapbar" has issues. The problem lies in the different color variables used in the themes:

themes/minimalist-mobile/minimalist-mobile.yaml
```yaml
minimalist-mobile-tapbar:
modes:
    light:
        slider-color: "rgb(var(--color-blue))"
        slider-bar-color: "rgba(var(--color-blue),0.38)"
    dark:
        slider-color: "rgb(var(--color-blue))"
        slider-bar-color: "rgba(var(--color-blue),0.38)"
```
Always uses `--color-blue`.

themes/minimalist-mobile-tapbar/minimalist-mobile-tapbar.yaml
```yaml
minimalist-mobile-tapbar:
modes:
    light:
        slider-color: "rgb(var(--google-blue))"
        slider-bar-color: "rgba(var(--google-blue),0.38)"
    dark:
        slider-color: "rgb(var(--color-blue))"
        slider-bar-color: "rgba(var(--color-blue),0.38)"
```
Uses `--google-blue` in light mode.

Replacing `--google-blue` with `--color-blue` in `themes/minimalist-mobile/minimalist-mobile.yaml` and rebooting HA and the App fixed the issue for me.
