### ISSUE TITLE
custom_card_esh_welcome not showing as it should

### ISSUE THREAD

**Issue by CrunkFX** [UI-Lovelace-Minimalist/UI#651]
**Describe the bug**
It seems like that some of the elements are too high!

**To Reproduce**
Can´t say for sure. Happened after restart with cache cleared

**Screenshots**
![image](https://user-images.githubusercontent.com/62955389/167585990-08a47b0f-3764-4583-9d8d-acbea06a8369.png)
![image](https://user-images.githubusercontent.com/62955389/167586798-536d5000-2e50-4fba-9f42-3e3c2aa5f2b7.png)

**Additional context**
Happens with all Themes, currently using minimalist-desktop. HACS says no Updates on all custom-cards, so for now everything up-to-date same with Homeassistant OS and and Supervisor

```
title: "Home"
path: "home"
cards:
  - type: "custom:button-card"
    template: "card_esh_welcome"
    triggers_update: "input_boolean.minimalist_dropdown"
    variables:
      ulm_card_esh_welcome_collapse: input_boolean.minimalist_dropdown
      ulm_weather: "weather.openweathermap"
      entity_1:
        nav: "Licht"
        icon: "mdi:lightbulb"
        name: "House"
        color: "blue"
      entity_2:
        nav: "Kameras"
        icon: "mdi:webcam"
        name: "Lights"
        color: "yellow"
      entity_3:
        nav: "Server"
        icon: "mdi:server"
        name: Secure
        color: "green"
      entity_4:
        nav: "network"
        icon: "mdi:nas"
        name: Lab
        color: "purple"
      entity_5:
        nav: "network"
        icon: "mdi:flask"
        name: Lab
        color: "red"
```
Maybe you could give me some hint where to start searching. I just reinstalled all frontend modules via HACS, that didn´t help.
