### ISSUE TITLE
Custom Card Elapsed Time Error

### ISSUE THREAD

**Issue by JSaterdalen** [UI-Lovelace-Minimalist/UI#655]
**Describe the bug**
Custom Elapsed Time card cannot find template. 

`Button-card template 'ulm_custom_card_eraycetinay_elapsed_time_language_variables' is missing!`

**To Reproduce**
1. create folder named **custom_card_eraycetinay_elapsed_time** under **custom_cards**
2. create **custom_card_eraycetinay_elapsed_time.yaml** with the code from [this page](https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_eraycetinay_elapsed_time/)
3. add card to layout
    ```yaml
      - type: "custom:button-card"
        template: "custom_card_eraycetinay_elapsed_time"
        entity: input_datetime.wall_e_time_pee
        name: "Last Peed"
    ```

**Screenshots**
<img width="374" alt="image" src="https://user-images.githubusercontent.com/6761188/167883908-77963e23-0772-4684-8ac4-559970b0ade7.png">

**Troubleshooting**
- reloaded UI Minimalist
- restarted HASS
