### ISSUE TITLE
Add a default or custom camera card

### ISSUE THREAD

**Issue by 1337Reaper** [UI-Lovelace-Minimalist/UI#658]
**Is your enhancement request related to a problem? Please describe.**
It looks like the project doesn't have an integrated camera card for live viewing

**Describe the solution you'd like**
I found the following code someone put on the forums that works but am unable to figure out the implementation myself as they gave no instructions where to put the button card template code. I have translated what I could:

```
type: custom:button-card
entity: camera.demo_camera #entity_id of the camera to display
template:
  - camera_live
  - tuile_neutre
```

And then:

```
button_card_templates:
  camera_live:  #Display the camera in a picture-entity
    show_label: false
    show_icon: false
    show_name: false
    styles:
      grid:
        - grid-template-areas: '"item1"'
    custom_fields:
      item1:
        card:
          camera_image: '[[[ return entity.entity_id ]]]'
          camera_view: live
          entity: '[[[ return entity.entity_id ]]]'
          show_name: false
          show_state: false
          type: picture-entity
  tuile_neutre:
    tap_action:
      action: more-info
    show-name: false
    styles:
      card:
        - border-radius: 20px
        - box-shadow: var(--box-shadow)
        - padding: 12px
```

I could not get this working unless I removed the tuile_neutre parts and even then it doesn't work when accessing the UI via iOS HomeAssistant app.

**Comment by Eltarius** [comment]
You prefer this style:
![cam_1](https://user-images.githubusercontent.com/15571859/168859105-facfe0a8-c743-4734-8034-d3892a1a6e20.png)

Or this style:
![cam_2](https://user-images.githubusercontent.com/15571859/168859118-0b2277b2-62a3-41c8-b056-d5915646d55c.png)

**Comment by 1337Reaper** [comment]
@Eltarius Personally I think that the top option that lists the camera name and icon to be the best option, but I'm sure some may not want it.

**Comment by Eltarius** [comment]
I have problem with show_icon variable which is not functional... So it will only work with ulm_custom_card_camera_title: true
The script will still work just like on my 1st screenshot.

Create this file config/ui_lovelace_minimalist/custom_cards/custom_card_camera/custom_card_camera.yaml
```
---
camera_live:  #Display the camera in a picture-entity
  template:
    - "blue_no_state"
  show_name: false
  show_label: false
  show_icon: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
  styles:
    card:
      - border-radius: "20px"
      - box-shadow: "var(--box-shadow)"
      - padding: "12px"
    img_cell:
      - border-radius: "50%"
      - place-self: "center"
      - width: "42px"
      - height: "42px"
    grid:
      - grid-template-areas: "'i item1' 'i item1' 'item2 item2'"
      - grid-template-columns: "min-content auto"
      - grid-template-rows: "min-content min-content min-content"
      - row-gap: |-
          [[[
            if(variables.ulm_custom_card_camera_title)
            {
              return "12px";
            }
            else
            {
              return "0px";
            }
          ]]]
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        show_name: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        show_label: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        show_icon: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        name: "[[[ return variables.ulm_custom_card_camera_name; ]]]"
        label: "[[[ return variables.ulm_custom_card_camera_label; ]]]"
        styles:
          card:
            - box-shadow: "none"
            - padding: "0"
          name:
            - align-self: "end"
            - justify-self: "start"
            - font-weight: "bold"
            - font-size: "14px"
            - margin-left: "12px"
            - filter: "opacity(100%)"
          label:
            - justify-self: "start"
            - align-self: "start"
            - font-weight: "bolder"
            - font-size: "12px"
            - filter: "opacity(40%)"
            - margin-left: "12px"
          grid:
            - grid-template-areas: "'n' 'l'"
            - grid-template-columns: "auto"
            - grid-template-rows: "min-content min-content" 
    item2:
      card:
        camera_image: '[[[ return entity.entity_id ]]]'
        camera_view: live
        entity: '[[[ return entity.entity_id ]]]'
        show_name: false
        show_state: false
        type: picture-entity
  tap_action:
    action: more-info
```
And the template card (Edit with your data)
```
- type: custom:button-card
  entity: camera.sensor
  template: "camera_live"
  variables:
    ulm_custom_card_camera_title: true
    ulm_custom_card_camera_name: "name"
    ulm_custom_card_camera_label: "label"
```

**Comment by NWalledge** [comment]
That template doesnt work says it cant find the card

**Comment by Eltarius** [comment]
> That template doesnt work says it cant find the card

Have you create custom_card_camera.yaml and reload Ui-Minimalist?

**Comment by NWalledge** [comment]
Yes

**Comment by Eltarius** [comment]
> @Eltarius This is the link:
> 
> https://forum.hacf.fr/t/dashboard-minimalist/5507/183?u=clemalex
> 
> The user is a moderator called clemalex
Thx, I have send him a message.

@NWalledge
Strange, I use the same code and it's work.

@1337Reaper can you try this card?

**Comment by NWalledge** [comment]
Still don't work :(  says "camera live" is missing.

**Comment by Eltarius** [comment]
@NWalledge try this https://github.com/Eltarius/UI/tree/custom_card_camera/custom_cards/custom_card_camera

**Comment by 1337Reaper** [comment]
> @NWalledge try this https://github.com/Eltarius/UI/tree/custom_card_camera/custom_cards/custom_card_camera

I gave it a try and I always have a few problems before I can get things running:

Button-card template 'custom_card camera' is missing!
`type: custom:button-card
entity: camera.livingroom1
template: custom_card_camera
show_icon: false
variables:
  ulm_custom_card_camera_title: true
  ulm_custom_card_camera_name: Living Room 1
  ulm_custom_card_camera_label: Living Room 2`

**Comment by Eltarius** [comment]
@1337Reaper you use this card https://github.com/Eltarius/UI/blob/custom_card_camera/custom_cards/custom_card_camera/custom_card_camera.yaml ?
This Custom card was on my HA installation and I haven't this error. It's like your custom card wasn't installed

The only time I got this error was during card installation before reloading the theme like this:
![image](https://user-images.githubusercontent.com/15571859/169123238-bcad4d16-1ca2-42c9-9d13-245080346340.png)

After I use this:
![image](https://user-images.githubusercontent.com/15571859/169123710-0c6d6bff-256c-41e9-8e4f-dd2b95c7c58b.png)

And error disappears.

**Comment by clemalex824** [comment]
Hello 
Another beautiful card if you missed it :

https://forum.hacf.fr/t/integration-de-limage-dune-camera-dans-un-custom-button-card/11178/2?u=clemalex

We can imagine displaying the name of the camera at the bottom (Motion detection too)

**Comment by NWalledge** [comment]
> @1337Reaper you use this card https://github.com/Eltarius/UI/blob/custom_card_camera/custom_cards/custom_card_camera/custom_card_camera.yaml ? This Custom card was on my HA installation and I haven't this error. It's like your custom card wasn't installed
> 
> The only time I got this error was during card installation before reloading the theme like this: ![image](https://user-images.githubusercontent.com/15571859/169123238-bcad4d16-1ca2-42c9-9d13-245080346340.png)
> 
> After I use this: ![image](https://user-images.githubusercontent.com/15571859/169123710-0c6d6bff-256c-41e9-8e4f-dd2b95c7c58b.png)
> 
> And error disappears.

Still is saying the  custom camera card is missing?

**Comment by Eltarius** [comment]
> Hello Another beautiful card if you missed it :
> 
> https://forum.hacf.fr/t/integration-de-limage-dune-camera-dans-un-custom-button-card/11178/2?u=clemalex
> 
> We can imagine displaying the name of the camera at the bottom (Motion detection too)

@clemalex824 thx buddy for this share. I will work on this new base

@NWalledge & @1337Reaper can you confirm you have custom card like this (with this tree structure):
![image](https://user-images.githubusercontent.com/15571859/169157580-daef1ade-ee7c-4d2a-a820-d41ad351e51e.png)
& this **custom_card_camera.yaml** begin like this:
![image](https://user-images.githubusercontent.com/15571859/169157678-3059cfa3-4938-4300-8fd8-bc0f0fe8f7fa.png)
if everything is ok, check if in this tree you have a custom_card_camera.yaml file:
![image](https://user-images.githubusercontent.com/15571859/169158115-8b90b0fc-8d74-4926-aec6-4cca52d5d61a.png)

**Comment by 1337Reaper** [comment]
@Eltarius That fixed it, thanks. Card is working and it looks great!

**Comment by 1337Reaper** [comment]
@clemalex824 Thank you for your template! Much appreciated.

**Comment by dennis071nl** [comment]
Thanks for this, i tried to install, but sticking to this error; 
where should the template go??

![image](https://user-images.githubusercontent.com/19318433/169684945-a2ace11d-2b85-44f1-89c4-c73441619714.png)

**Comment by Eltarius** [comment]
@dennis071nl config/ui_lovelace_minimalist/custom_cards/custom_card_camera/custom_card_camera.yaml

**Comment by dennis071nl** [comment]
my custom_card_camera.yaml (in the right directory) looks like this: 

---
custom_card_camera:  #Display the camera in a picture-entity
  template:
    - "blue_no_state"
  show_name: false
  show_label: false
  show_icon: "[[[ return variables.ulm_custom_card_camera_title; ]]]" #Nonfunctional
  styles:
    card:
      - border-radius: "20px"
      - box-shadow: "var(--box-shadow)"
      - padding: "12px"
    img_cell:
      - border-radius: "50%"
      - place-self: "center"
      - width: "42px"
      - height: "42px"
    grid:
      - grid-template-areas: "'i item1' 'i item1' 'item2 item2'"
      - grid-template-columns: "min-content auto"
      - grid-template-rows: "min-content min-content min-content"
      - row-gap: |-
          [[[
            if(variables.ulm_custom_card_camera_title)
            {
              return "12px";
            }
            else
            {
              return "0px";
            }
          ]]]
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        show_name: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        show_label: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        show_icon: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        name: "[[[ return variables.ulm_custom_card_camera_name; ]]]"
        label: "[[[ return variables.ulm_custom_card_camera_label; ]]]"
        styles:
          card:
            - box-shadow: "none"
            - padding: "0"
          name:
            - align-self: "end"
            - justify-self: "start"
            - font-weight: "bold"
            - font-size: "14px"
            - margin-left: "12px"
            - filter: "opacity(100%)"
          label:
            - justify-self: "start"
            - align-self: "start"
            - font-weight: "bolder"
            - font-size: "12px"
            - filter: "opacity(40%)"
            - margin-left: "12px"
          grid:
            - grid-template-areas: "'n' 'l'"
            - grid-template-columns: "auto"
            - grid-template-rows: "min-content min-content"
    item2:
      card:
        camera_image: "[[[ return entity.entity_id ]]]"
        camera_view: "live"
        entity: "[[[ return entity.entity_id ]]]"
        show_name: false
        show_state: false
        type: "picture-entity"
  tap_action:
    action: "more-info"


  button_card_templates:
  camera_live:  #Display the camera in a picture-entity
    show_label: false
    show_icon: false
    show_name: false
    styles:
      grid:
        - grid-template-areas: '"item1"'
    custom_fields:
      item1:
        card:
          camera_image: '[[[ return entity.entity_id ]]]'
          camera_view: live
          entity: '[[[ return entity.entity_id ]]]'
          show_name: false
          show_state: false
          type: picture-entity
  tuile_neutre:
    tap_action:
      action: more-info
    show-name: false
    styles:
      card:
        - border-radius: 20px
        - box-shadow: var(--box-shadow)
        - padding: 12px

**Comment by NWalledge** [comment]
Managed to get it working thanks, Now is there anyway to get rid of the borders and have it like the standard picture glance card? and also is there a way to set it so the cameras are all the same size?

**Comment by Eltarius** [comment]
@dennis071nl Remove this in your custom_card_camera.yaml
```
  button_card_templates:
  camera_live:  #Display the camera in a picture-entity
    show_label: false
    show_icon: false
    show_name: false
    styles:
      grid:
        - grid-template-areas: '"item1"'
    custom_fields:
      item1:
        card:
          camera_image: '[[[ return entity.entity_id ]]]'
          camera_view: live
          entity: '[[[ return entity.entity_id ]]]'
          show_name: false
          show_state: false
          type: picture-entity
  tuile_neutre:
    tap_action:
      action: more-info
    show-name: false
    styles:
      card:
        - border-radius: 20px
        - box-shadow: var(--box-shadow)
        - padding: 12px
```

And in your ui-lovelace.yaml replace by this:
```
- type: "custom:button-card"
  entity: "camera.camera1"
  template: "custom_card_camera"
  show_icon: true #True if you set ulm_custom_card_camera_title: true
  variables:
    ulm_custom_card_camera_title: true
    ulm_custom_card_camera_name: "name"
    ulm_custom_card_camera_label: "label"
```

**Comment by Eltarius** [comment]
> Managed to get it working thanks, Now is there anyway to get rid of the borders and have it like the standard picture glance card? and also is there a way to set it so the cameras are all the same size?

In custom_card_camera.yaml at line 12, set padding to 0px

**Comment by dennis071nl** [comment]
Great, got it working, thanks for the support!

**Comment by dennis071nl** [comment]
too fast: 

![image](https://user-images.githubusercontent.com/19318433/169697996-77a44b2f-54ad-4136-b915-c528432c7cfc.png)

Should i install another custom_card for this??

**Comment by Eltarius** [comment]
No picture-entity is a native card:
https://www.home-assistant.io/dashboards/picture-entity/

Restart your HA & try

**Comment by dennis071nl** [comment]
after reboot still the same error:

![image](https://user-images.githubusercontent.com/19318433/169700029-1c75b2d3-f4ba-40d0-96a5-5f68f51701bb.png)

**Comment by Eltarius** [comment]
Paste your code please.
somewhere in your code there is "custom:picture-entity" instead of "picture-entity" (Picture entity isn't a custom card)

**Comment by dennis071nl** [comment]
lovelace-ui.yaml

```########################
########Security########
########################
  - title: ""
    icon: mdi:cctv
    path: security
    cards:
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            entity: "camera.camera1"
            template: "custom_card_camera"
            show_icon: true #True if you set ulm_custom_card_camera_title: true
            variables:
              ulm_custom_card_camera_title: true
              ulm_custom_card_camera_name: "Camera"
              ulm_custom_card_camera_label: "Poortdeur"
``` 

custom_card_camera.yaml:

```
---
custom_card_camera:  #Display the camera in a picture-entity
  template:
    - "blue_no_state"
  show_name: false
  show_label: false
  show_icon: "[[[ return variables.ulm_custom_card_camera_title; ]]]" #Nonfunctional
  styles:
    card:
      - border-radius: "20px"
      - box-shadow: "var(--box-shadow)"
      - padding: "12px"
    img_cell:
      - border-radius: "50%"
      - place-self: "center"
      - width: "42px"
      - height: "42px"
    grid:
      - grid-template-areas: "'i item1' 'i item1' 'item2 item2'"
      - grid-template-columns: "min-content auto"
      - grid-template-rows: "min-content min-content min-content"
      - row-gap: |-
          [[[
            if(variables.ulm_custom_card_camera_title)
            {
              return "12px";
            }
            else
            {
              return "0px";
            }
          ]]]
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        show_name: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        show_label: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        show_icon: "[[[ return variables.ulm_custom_card_camera_title; ]]]"
        name: "[[[ return variables.ulm_custom_card_camera_name; ]]]"
        label: "[[[ return variables.ulm_custom_card_camera_label; ]]]"
        styles:
          card:
            - box-shadow: "none"
            - padding: "0"
          name:
            - align-self: "end"
            - justify-self: "start"
            - font-weight: "bold"
            - font-size: "14px"
            - margin-left: "12px"
            - filter: "opacity(100%)"
          label:
            - justify-self: "start"
            - align-self: "start"
            - font-weight: "bolder"
            - font-size: "12px"
            - filter: "opacity(40%)"
            - margin-left: "12px"
          grid:
            - grid-template-areas: "'n' 'l'"
            - grid-template-columns: "auto"
            - grid-template-rows: "min-content min-content"
    item2:
      card:
        camera_image: "[[[ return entity.entity_id ]]]"
        camera_view: "live"
        entity: "[[[ return entity.entity_id ]]]"
        show_name: false
        show_state: false
        type: "picture-entity"
  tap_action:
    action: "more-info"

```

**Comment by Eltarius** [comment]
@dennis071nl I don't know why...

Try this, Replace **item2** (Line 64 to 71) in your custom_card_camera.yaml by this
```YAML
    item2:
      card:
        type: "picture-entity"
        camera_image: "[[[ return entity.entity_id ]]]"
        camera_view: "live"
        entity: "[[[ return entity.entity_id ]]]"
        show_name: false
        show_state: false
```

**Comment by basbruss** [comment]
@dennis071nl Do you have the button_card_templates reference in your ui-lovelace.yaml file?
```yaml 
button_card_templates: !include_dir_merge_named "../../custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"
```

> Try this, Replace item2 (Line 64 to 71) in your custom_card_camera.yaml by this
  ```yaml
    item2:
      card:
        type: "picture-entity"
        camera_image: "[[[ return entity.entity_id ]]]"
        camera_view: "live"
        entity: "[[[ return entity.entity_id ]]]"
        show_name: false
        show_state: false
  ```
This is the same as he already has. The only difference is it is sorted alphabetically 😉

**Comment by willyp713** [comment]
How would you get the `label` to return the `state` of the camera? For example, the following does not work (it just prints the actual text instead of running the code as a template):

```
- type: "custom:button-card"
            entity: "camera.doorbell"
            template: "custom_card_camera"
            show_icon: true #True if you set ulm_custom_card_camera_title: true
            variables:
              ulm_custom_card_camera_title: true
              ulm_custom_card_camera_name: "Front Door"
              ulm_custom_card_camera_label: >
                {{ states('camera.doorbell') }}
```

**Comment by basbruss** [comment]
@willyp713 You should use Javascript to template code in `custom:button-card`

So it would be something like this:
```yaml
type: "custom:button-card"
entity: "camera.doorbell"
template: "custom_card_camera"
show_icon: true #True if you set ulm_custom_card_camera_title: true
  variables:
     ulm_custom_card_camera_title: true
     ulm_custom_card_camera_name: "Front Door"
     ulm_custom_card_camera_label: "[[[ states['camera.doorbell].state ]]]"

**Comment by willyp713** [comment]
> 

That doesn't seem to be working :(

Using the following:
```
type: "custom:button-card"
entity: "camera.doorbell"
template: "custom_card_camera"
show_icon: true #True if you set ulm_custom_card_camera_title: true
    variables:
        ulm_custom_card_camera_title: true
        ulm_custom_card_camera_name: "Front Door"
        ulm_custom_card_camera_label: "[[[ states['camera.doorbell'].state ]]]"
```

It returns blank text (no text at all):
![03](https://user-images.githubusercontent.com/21319282/176328601-2d8f9348-57e0-4524-99c8-b63c3278d481.png)

But that entity most definitely _does_ have a state:
![04](https://user-images.githubusercontent.com/21319282/176328694-92f0aafb-fba8-444b-8b94-b81a3914cb94.png)
