### ISSUE TITLE
Room Card: Templates do not work on entity icons.

### ISSUE THREAD

**Issue by JoshSald** [UI-Lovelace-Minimalist/UI#682]
Despite setting up entities on a room card with templates, the smaller icons do not seem to adopt these templates making it harder to see at a glance whether or not a light, for example, is on or not unless there were other places that make it clear OR if that particular entity is also the main entity for the card.  

Here is an example of one of those entities:
```
entity_1:
  entity_id: light.bedroom_lamp
  template:
    - yellow_on
    - grey_no_state
  tap_action:
     action: toggle
```

When clicking on the icon, it should toggle the light on or off which it does. The icons, however, do not turn yellow when the lights are on as they should according to the template. Strangely enough, if the entity is also set as the main entity for the card, the templates will actually work on the entire card (if set as such), but not on the icons. 

To further clarify, below you can see that the media player lights up the main card as it is the main entity, but the icon remains gray even though it should be turning green as well. 

<img width="258" alt="Screenshot 2022-05-21 at 21 14 10" src="https://user-images.githubusercontent.com/42002468/169666189-d25092e9-9e92-4e54-939e-a4bd705fc4f5.png">

The YAML for the card:
```
- type: "custom:button-card"
   template:
     - card_room
     - custom_cards_media_playing
     - grey_no_state
   name: Kitchen 
   entity: media_player.sonos_kitchen
   icon: mdi:knife
   tap_action:
     action: navigate
     navigation_path: "/ui-lovelace-minimalist/room-kitchen"
   variables:
     label_use_temperature: false
     label_use_brightness: false
     entity_1:
       entity_id: media_player.sonos_kitchen
       template:
         - grey_no_state
         - custom_cards_media_playing
       tap_action:
         action: call-service
         service: media_player.media_play_pause
         service_data:
           entity_id: media_player.sonos_kitchen
```

**Comment by Eltarius** [comment]
Edit your code at line 17, templates with S at the end
```YAML
- type: "custom:button-card"
   template:
     - card_room
     - custom_cards_media_playing
     - grey_no_state
   name: Kitchen 
   entity: media_player.sonos_kitchen
   icon: mdi:knife
   tap_action:
     action: navigate
     navigation_path: "/ui-lovelace-minimalist/room-kitchen"
   variables:
     label_use_temperature: false
     label_use_brightness: false
     entity_1:
       entity_id: media_player.sonos_kitchen
       templates:
         - grey_no_state
         - custom_cards_media_playing
       tap_action:
         action: call-service
         service: media_player.media_play_pause
         service_data:
           entity_id: media_player.sonos_kitchen
```

**Comment by jrspowers** [comment]
@JoshSald hello may i ask what the custom cards media playing entail and could you share it plainly?

**Comment by JoshSald** [comment]
> Edit your code at line 17, templates with S at the end
> 
> ```yaml
> - type: "custom:button-card"
>    template:
>      - card_room
>      - custom_cards_media_playing
>      - grey_no_state
>    name: Kitchen 
>    entity: media_player.sonos_kitchen
>    icon: mdi:knife
>    tap_action:
>      action: navigate
>      navigation_path: "/ui-lovelace-minimalist/room-kitchen"
>    variables:
>      label_use_temperature: false
>      label_use_brightness: false
>      entity_1:
>        entity_id: media_player.sonos_kitchen
>        templates:
>          - grey_no_state
>          - custom_cards_media_playing
>        tap_action:
>          action: call-service
>          service: media_player.media_play_pause
>          service_data:
>            entity_id: media_player.sonos_kitchen
> ```

I am silly. This fixes it. Thank you.

**Comment by JoshSald** [comment]
> @JoshSald hello may i ask what the custom cards media playing entail and could you share it plainly?

It is essentially just a copy of the colour templates except it looks for a "playing" state instead. 

```
---
custom_cards_media_playing:
  state:
    - styles:
        icon:
          - color: "rgba(var(--color-green),1)"
        label:
          - color: "rgba(var(--color-green-text),1)"
        name:
          - color: "rgba(var(--color-green-text),1)"
        img_cell:
          - background-color: "rgba(var(--color-green), 0.2)"
        card:
          - background-color: "rgba(var(--color-background-green), var(--opacity-bg))"
      value: "playing"
      id: "media-playing"

# Legacy
green:
  template: "green_on"
```
