### ISSUE TITLE
Ripple effect on devices using safari is shown over the rounded borders.

### ISSUE THREAD

**Issue by digaus** [UI-Lovelace-Minimalist/UI#714]
**Describe the bug**

Ripple effect on devices using safari is shown over the rounded borders.

Related: https://stackoverflow.com/a/64885552

**To Reproduce**
Test button-card on safari and click on it.

**Expected behavior**
Ripple effect should be applied correctly

**Screenshots**

**Additional context**

We can fix this by adding `transform: translateZ(0)` to the `ha-card`

**Comment by BlackStar-95** [comment]
```
title: "Home"
path: "home"
cards:
  - type: "custom:button-card"
    template: "card_esh_welcome"
    triggers_update: "input_boolean.minimalist_dropdown"
    variables:
      ulm_card_esh_welcome_collapse: input_boolean.minimalist_dropdown
      ulm_weather: "weather.openweathermap"
      entity_1:
        nav: "house"
        icon: "mdi:home"
        name: "House"
        color: "blue"
      entity_2:
        nav: "lights"
        icon: "mdi:lightbulb"
        name: "Lights"
        color: "yellow"
      entity_3:
        nav: "security"
        icon: "mdi:shield"
        name: Secure
        color: "green"
      entity_4:
        nav: "network"
        icon: "mdi:nas"
        name: Lab
        color: "purple"
      entity_5:
        nav: "network"
        icon: "mdi:flask"
        name: Lab
        color: "red"

```
What should i do in my case?
how can i add transform: "translateZ(0)" ?
