### ISSUE TITLE
Scenes Card random colors despite fixed config

### ISSUE THREAD

**Issue by peetereczek** [UI-Lovelace-Minimalist/UI#729]
**Describe the bug**
Scenes Card is displayed random colors despite fixed config since release 0.0.9

**To Reproduce**

1. Configure scenes card
2. Open UI
3. See error

**Expected behavior**
Fixed colors will be used as configured

**Screenshots**
Screen 1
![image](https://user-images.githubusercontent.com/42431204/172156057-28264176-3f6d-44ac-9555-ef90bac00bd6.png)

Screen 2:
![image](https://user-images.githubusercontent.com/42431204/172156353-4ffabfe0-5d48-42f2-927b-d6700d90fe34.png)

**Additional context**
```yaml
        - type: custom:button-card
          template: edge
        - type: 'custom:button-card'
          template: card_title
          name: Sceny
        - type: "custom:button-card"
          template: card_scenes
          variables:
            entity_1:
              entity_id: "scene.praca"
              icon: "mdi:briefcase"
              icon_color: "green"
              name: "Praca"
              bg_color: "green"
            entity_2:
              entity_id: "scene.wieczor"
              icon: "mdi:weather-night"
              icon_color: "purple"
              name: "Wieczór"
              bg_color: "purple"
            entity_3:
              entity_id: "scene.movie"
              icon: "mdi:movie-filter-outline"
              icon_color: "red"
              name: "Film"
              bg_color: "red"
            entity_4:
              entity_id: "scene.game_on"
              icon: "mdi:sony-playstation"
              icon_color: "blue"
              name: "Granie"
              bg_color: "blue"
            entity_5:
              entity_id: "scene.spanie"
              icon: "mdi:bed"
              icon_color: "yellow"
              name: "Spanie"
              bg_color: "yellow"
        - type: custom:button-card
          template: edge
```
