### ISSUE TITLE
Card for button entity

### ISSUE THREAD

**Issue by KGS501** [UI-Lovelace-Minimalist/UI#743]
### Is your feature request related to a problem? Please describe.
Currently there is no easy way to use a `button.name` entity in UI-Lovelace_Minimalist.

<br>

### Describe the solution you'd like
A new card type that lets you just press a button to call the service `button.press`
```yaml
service: button.press
data: {}
target:
  entity_id: button.name
```
(working example from the HA developer settings)

<br>

### Describe alternatives you've considered
I tried to use the _**card_script**_ card and modify the called service to `service: button.press` like in the code example above but always got the error:

![image](https://user-images.githubusercontent.com/83352171/173248083-0d06153e-42e2-45a7-93eb-af731cf70e52.png)
"Error when calling service button/press. must contain at least one of entity_id, device_id, area_id."

Although an `entity_id:` was clearly defined. I tried different variations, with `data: entity_id:` without `target:` and so on, always with the same error. I could only create a working button when not using ui-lovelace-minimalist:

```yaml
type: button
entity: button.name
tap_action:
   action: toggle
```

When trying to use this in a ui-lovelace-minimalist card like

```yaml
- type: "custom:button-card"
template: card_script
entity: button.name
variables:
   ulm_card_script_title: Romantic lights
   ulm_card_script_icon: "mdi:candle"
tap_action:
   action: toggle
```

I got the following error:

![image](https://user-images.githubusercontent.com/83352171/173248618-a7bab463-02d9-4269-8ead-ed543098f53a.png)
"Error when calling service button/turn_off. Service not found."

All this to say I cant get a button to work which lets me call the service `button.press` in ui-lovelace-minimalist. So a button card that is plug-and-play for this use case would be pretty cool.

**Comment by Neekster** [comment]
This is what I use to record when I last mowed the lawn. Are you sure that you are using the correct service? I'm using the input_button.press service. You appear to be using the button.press service, which does not appear to exist.
```
- type: 'custom:button-card'
  template: card_vertical_button
  entity: input_button.record_mow
  show_last_changed: false
  name: Record Mow
```

**Comment by KGS501** [comment]
I also tried your approach now and it doesn't work aswell. I don't even get an error message. If I press the button just nothing happens.

```yaml
- type: "custom:button-card"
   template: card_vertical_button
   entity: button.examle_name
   show_last_changed: false
   name: Record Mow
```

**Comment by KGS501** [comment]
OH MY LORD

It does work now. In my testing I somehow missed the following variation:

```yaml
- type: "custom:button-card"
  template: card_script
     variables:
        ulm_card_script_title: Romantic lights
        ulm_card_script_icon: "mdi:candle"
      tap_action:
        action: call-service
        service: button.press
        service_data:
          entity_id: button.example_name
```

The important part is, that you have to use `service_data:` followed by `entity_id:`. I somehow only used the methods in the homeassistant documentation for call-service and button entity where `data:` and `target:` are used.

Thanks non the less for your help👍
