### ISSUE TITLE
Single tap not showing "more-info" popup after upgrading to v1.0.1

### ISSUE THREAD

**Issue by Ristou** [UI-Lovelace-Minimalist/UI#781]
**Describe the bug**
After upgrading to 1.0.1, single tap action does not trigger more-info popup.
I found out that double tap is showing "more info" popup instead.

**To Reproduce**

1. Go to any card that supposed to show "more-info" popup
2. Click on icon or label
4. Nothing happening

**Expected behavior**
Show "more-info" popup at single tap

**Comment by schumijo** [comment]
Have you tried customizing actions ? It is a new feature in v1.0.1
https://ui-lovelace-minimalist.github.io/UI/setup/custom_actions/

**Comment by Ristou** [comment]
Yes I've been looking at it, if I change it like below, it works
```` yaml
---
ulm_custom_actions:
  variables:
    ulm_card_tap_action: "toggle"
    ulm_card_hold_action: "more-info"
    ulm_card_double_tap_action: "adaptive"
    ulm_icon_tap_action: "more-info"
    ulm_icon_hold_action: "more-info"
    ulm_icon_double_tap_action: "adaptive"
    ulm_name_tap_action: "toggle"
    ulm_name_hold_action: "more-info"
    ulm_name_double_tap_action: "adaptive"
```
But then it has an impact on other like "light" where it is better to use toggle action

**Comment by schumijo** [comment]
Sadly, custom actions apply to all cards.

**Comment by basbruss** [comment]
There is a way around it by using templates. This is a bit hacky and advanced way of doing things.
But adapting this template to your liking can set click behaviors for all types of entities:
```yaml
    ulm_icon_tap_action: >
      [[[
        let domain = entity.entity_id.substr(0, entity.entity_id.indexOf("."));
        if(domain == "light"){return "toggle";}
        else {return "more-info"}
      ]]]
```

**Comment by Ristou** [comment]
Thanks @basbruss for the workaround. The template below meets my needs

``` yaml
---
ulm_custom_actions:
  variables:
    ulm_card_tap_action: >
      [[[
        let domain = entity.entity_id.substr(0, entity.entity_id.indexOf("."));
        let toggle_domain = ["light", "switch", "climate", "button", "input_boolean"];
        return (toggle_domain.includes(domain)) ? "toggle" : "more-info";
      ]]]
    ulm_card_hold_action: "more-info"
    ulm_card_double_tap_action: "adaptive"
    ulm_icon_tap_action: "more-info"
    ulm_icon_hold_action: "more-info"
    ulm_icon_double_tap_action: "adaptive"
    ulm_name_tap_action: >
      [[[
        let domain = entity.entity_id.substr(0, entity.entity_id.indexOf("."));
        let toggle_domain = ["light", "switch", "climate", "button", "input_boolean"];
        return (toggle_domain.includes(domain)) ? "toggle" : "more-info";
      ]]]
    ulm_name_hold_action: "more-info"
    ulm_name_double_tap_action: "adaptive"
```
