### ISSUE TITLE
Thermostat Card does not increase temperature value

### ISSUE THREAD

**Issue by schlop** [UI-Lovelace-Minimalist/UI#785]
**Describe the bug**
If the plus button of the thermostat card is clicked the temperature value of the climate entity does not change. The temperature value can be decreased with the minus button, but increasing it with the plus button does not work. The temperature value can be manipulated as expected with the standard home assistant thermostat card. This issue occurs with version 1.0.1.

**To Reproduce**

1. Add a thermostat card to the interface with the yaml code below
```
- type: "custom:button-card"
  template: card_thermostat
  entity: climate.living
  variables:
    ulm_card_thermostat_enable_controls: true
    ulm_card_thermostat_enable_display_temperature: true
```
3. Click on '+'
4. See error (temperature value is not increasing)

**Expected behavior**
The temperature value should increase if the plus button is pressed.

**Screenshots**
The card that I am using is relatively compact (see screenshot). However, the issue also occurs if the size of the card gets increased.

<img width="152" alt="Screen Shot 2022-06-24 at 23 24 08" src="https://user-images.githubusercontent.com/6044565/175545440-32812fca-83b1-4151-86e7-8572bc5df8ca.png">
