### ISSUE TITLE
Person Custom Card Errors - ulm_translation_engine

### ISSUE THREAD

**Issue by Zorbeen98** [UI-Lovelace-Minimalist/UI#786]
I've installed the custom card and receive the following error: 

ulm_translation_engine

```
type: custom:button-card
template: custom_card_imswel_person
variables:
  ulm_card_imswel_person_entity: person.user
  ulm_card_imswel_person_wifi_tracker: device_tracker.user_phone
  ulm_card_imswel_person_gps_tracker: device_tracker.user_phone
  ulm_card_imswel_person_findmy_script: script.find_my_user_phone
  ulm_card_imswel_person_use_entity_picture: true
  ulm_card_imswel_person_zones:
    - zone.home
    - zone.work
```

I have the following in place:

custom_cards/custom_card_imswel_person/custom_card_imswel_person.yaml
custom_cards/custom_card_imswel_person/languages/en.yaml

The WiFi, GPS and script trackers that are defined do not exist; not sure if this is the issue? 
I don't understand how to specify these or what to set them to? 
These are not required for the standard person card.

**Comment by basbruss** [comment]
Please upgrade to v1.0.1 this includes the translation engine. Also read the breaking changes part of the release notes to adapt the card config.

**Comment by Zorbeen98** [comment]
That seems to have broken all of my cards now. 

E.g. Button-card template 'chip_navigate' is missing. 

```
type: custom:button-card
template: chip_navigate
label: Shopping
variables:
  ulm_chip_navigate_path: /ui-lovelace-mobile/shopping
  ulm_chip_navigate_icon: mdi:shopping
```

I literally updated Home Assistant Core to the latest version via the UI and then updated Minimalist to v1.0.1. 
Is there something else key that I need to do? I'm not seeing anything in the updates or anything specific I need to do in the release notes.

**Comment by Zorbeen98** [comment]
Thank you. 

I've got it working but now nothing happens when I tap on the icon...

```
      - type: "custom:button-card"
        template: custom_card_imswel_person
        entity: person.user
        variables:
          ulm_card_imswel_person_entity: person.user
          ulm_card_imswel_person_wifi_tracker: device_tracker.user_phone
          ulm_card_imswel_person_gps_tracker: device_tracker.user_phone
          ulm_card_imswel_person_findmy_script: script.find_my_user_phone
          ulm_card_imswel_person_use_entity_picture: true
          ulm_card_imswel_person_zones:
            - zone.home
            - zone.work
```
