### ISSUE TITLE
Cover card does not support grouping of covers.

### ISSUE THREAD

**Issue by dennis-bell** [UI-Lovelace-Minimalist/UI#796]
The cover card is unable to handle grouped covers, like all covers on the west of the house.

1. create a group of multiple covers:
```
groups:
   zonnescherm_elize:
     name: Zonneschermen elize
     entities:
       - cover.elize_l
       - cover.elize_r
```
Then create a custom button card with template cover:
```
          - type: "custom:button-card"
            template: card_cover
            entity: group.zonnescherm_elize
            variables:
              ulm_card_cover_name: Zonnescherm Elize
              ulm_card_cover_enable_controls: true
              ulm_card_cover_enable_slider: false
```

Would assume the custom card button would be able to handle groups.

**Comment by basbruss** [comment]
Hi @dennis-bell 

Groups in HA generally do not provide the same options, information, and attributes as the devices' entities.
All the cards in Minimalist are built to function with their device' type of entity.

**Comment by dennis-bell** [comment]
@basbruss, I figured it out.
within the covers: you can create groups with the same functionality

Like this:
```
covers:
- platform: group
  name: Zonneschermen elize
  entities:
    - cover.elize_l
    - cover.elize_r 
```

This ticket is resolved!
