### ISSUE TITLE
No Navigation with Tap_action via card_binary_sensor_alert

### ISSUE THREAD

**Issue by M3m0rys** [UI-Lovelace-Minimalist/UI#798]
since the update und its introduction off Custom Actions it seems no longer possible to use the standart Tap_Action to navigate 

```
- type: 'custom:button-card'
   template: card_binary_sensor_alert
   variables:
       ulm_card_binary_sensor_alert: true
       ulm_show_last_changed: true
    entity: binary_sensor.haus_fenster
    show_state: false                
    tap_action:
         action: navigate  
         navigation_path: /ui-lovelace-minimalist/fenster
```
