### ISSUE TITLE
Update 1.0.2 breaking change language in graph card usage

### ISSUE THREAD

**Issue by DevTodd** [UI-Lovelace-Minimalist/UI#808]
The current code usage documentation for graph card is incorrect:

https://github.com/UI-Lovelace-Minimalist/UI/blob/main/docs/usage/cards/card_graph.md
https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_graph/#usage

It should include the now required entity and should be as below:

```yaml
- type: 'custom:button-card'
  template: card_graph
  entity: sensor.livingroom_temperature
  variables:
    ulm_card_graph_color: "var(--google-blue)"
    ulm_card_graph_name: Temperature Livingroom
    ulm_card_graph_entity: sensor.livingroom_temperature
    ulm_card_graph_color2: "var(--google-green)"
    ulm_card_graph_entity2: sensor.bedgroom_temperature
    ulm_card_graph_type: fill
    ulm_card_graph_hours: 24
```
