### ISSUE TITLE
card_generic - style based on state not working anymore

### ISSUE THREAD

**Issue by ShadyMCShadesen** [UI-Lovelace-Minimalist/UI#820]
### The Problem
Before v1.0.1 was released it was possible to set the "**style**" of the "**card_generic**" based on the "**state**". Unfortunately, this is no longer possible (for example, with "card_vertical_button" it still works fine).
It would be awesome if this feature would come back.

### This Doesn't Work Anymore
``` yaml
- type: 'custom:button-card'
  template: card_generic
  entity: sensor.mitteltor_zustand
  variables:
    ulm_card_generic_name: Zustand
    state:
      - value: 'Geschlossen'
        styles:
          icon:
            - color: rgba(var(--color-green), 0.8)
          img_cell:
            - background-color: "rgba(var(--color-green), 0.2)"
      - value: 'Offen'
        styles:
           icon:
             - color: rgba(var(--color-yellow), 0.8)
             - animation: blink 2s ease-in-out infinite
           img_cell:
             - background-color: "rgba(var(--color-yellow), 0.2)"
             - animation: blink 2s ease-in-out infinite
      - value: 'Fährt auf'
        styles:
           icon:
             - color: rgba(var(--color-red), 0.8)
             - animation: blink 1s ease-in-out infinite
           img_cell:
             - background-color: "rgba(var(--color-red), 0.2)"
             - animation: blink 1s ease-in-out infinite
      - value: 'Fährt zu'
        styles:
          icon:
            - color: rgba(var(--color-red), 0.8)
            - animation: blink 1s ease-in-out infinite
          img_cell:
            - background-color: "rgba(var(--color-red), 0.2)"
            - animation: blink 1s ease-in-out infinite
      - value: 'Nicht verfügbar'
        styles:
          icon:
            - color: rgba(var(--color-red), 0.8)
          img_cell:
            - background-color: "rgba(var(--color-red), 0.2)"
```

### This Does Still Work Fine
``` yaml
- type: 'custom:button-card'
  template: card_vertical_button
  entity: switch.mitteltor_stop
  name: Stop
  hold_action:
    action: more-info
  variables:
    ulm_card_vertical_button_state: 'on'
    ulm_card_vertical_button_color: yellow
  state:
    - value: 'off'
      styles:
        icon:
          - color: rgba(var(--color-red), 0.8)
        img_cell:
          - background-color: "rgba(var(--color-red), 0.2)"
```

**Comment by basbruss** [comment]
@ShadyMCShadesen This is still possible only you need to add the state changes to a deeper nested level.
```yaml
- type: 'custom:button-card'
  template: card_generic
  entity: sensor.mitteltor_zustand
  variables:
    ulm_card_generic_name: Zustand
  custom_fields:
    item1:
      card:
        type: "custom:button-card"
        template:
          - "icon_more_info"
        custom_fields:
          item1:
            card:
              type: "custom:button-card"
              entity: "[[[ return entity.entity_id ]]]"
              state:
                - value: 'Geschlossen'
                   styles:
                     icon:
                       - color: rgba(var(--color-green), 0.8)
                     img_cell:
                       - background-color: "rgba(var(--color-green), 0.2)"
                - value: 'Offen'
                   styles:
                     icon:
                       - color: rgba(var(--color-yellow), 0.8)
                       - animation: blink 2s ease-in-out infinite
                     img_cell:
                       - background-color: "rgba(var(--color-yellow), 0.2)"
                       - animation: blink 2s ease-in-out infinite
                - value: 'Fährt auf'
                   styles:
                     icon:
                       - color: rgba(var(--color-red), 0.8)
                       - animation: blink 1s ease-in-out infinite
                     img_cell:
                       - background-color: "rgba(var(--color-red), 0.2)"
                       - animation: blink 1s ease-in-out infinite
                - value: 'Fährt zu'
                   styles:
                     icon:
                       - color: rgba(var(--color-red), 0.8)
                       - animation: blink 1s ease-in-out infinite
                     img_cell:
                       - background-color: "rgba(var(--color-red), 0.2)"
                       - animation: blink 1s ease-in-out infinite
                - value: 'Nicht verfügbar'
                   styles:
                     icon:
                       - color: rgba(var(--color-red), 0.8)
                     img_cell:
                       - background-color: "rgba(var(--color-red), 0.2)"
```
