### ISSUE TITLE
Version 1.0.2 custom name for Binary Sensor Alert Card nit working

### ISSUE THREAD

**Issue by MGlants** [UI-Lovelace-Minimalist/UI#835]
**Describe the bug**
Since update naming on cards not working.
Now i have long names in all items.

**Additional context**
Code before
```
        - type: "custom:auto-entities"
          card:
            type: "grid"
            columns: 2
            square: false
            title: Окна/Двери
          card_param: "cards"
          filter:
            include:
              - entity_id: '*contact'
                options:
                  type: "custom:button-card"
                  template: "card_binary_sensor_alert"
                  entity: "this.entity_id"
                  name: |
                    [[[
                      return states['this.entity_id'].attributes.device.friendlyName;
                    ]]]
                  variables:
                    - ulm_card_binary_sensor_alert: true
```
Code after
```
        - type: "custom:auto-entities"
          card:
            type: "grid"
            columns: 2
            square: false
            title: Окна/Двери
          card_param: "cards"
          filter:
            include:
              - entity_id: '*contact'
                options:
                  type: "custom:button-card"
                  template: "card_binary_sensor_alert"
                  entity: "this.entity_id"
                  variables:
                    - ulm_card_binary_sensor_alert: true
                    - ulm_card_binary_sensor_alert_name: |
                        [[[
                          return states['this.entity_id'].attributes.device.friendlyName;
                        ]]]
```
