### ISSUE TITLE
vacuum card crashes the whole ui

### ISSUE THREAD

**Issue by dennis-bell** [UI-Lovelace-Minimalist/UI#836]
Took me a while to figure out where this problem was, I started to disable all cards in my ui.
And enable one by one and watch the chrome developer console for errors.

Finally I found that this piece of simple code crashes it:
```
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            template: "card_vacuum"
            entity: vacuum.roborock_vacuum_a15
            variables:
              ulm_card_vacuum_name: "Berta"
```
Disabled the above piece now, and now its works perfectly again

The below error gets raised thousands times and eventually the chrome browser becomes unresponsive.

**Screenshots**
![image](https://user-images.githubusercontent.com/16700894/177106097-94e28a71-8c18-4b34-b9ee-6ef2e7787851.png)

Minimalist UI version
v1.0.2, installed by hacs
