### ISSUE TITLE
Custom actions no longer working with button card templates

### ISSUE THREAD

**Issue by panhans** [UI-Lovelace-Minimalist/UI#840]
**Describe the bug**
Using a generic card with a custom action doesnt work. The template produces an error.

**To Reproduce**
```
# doesnt work anymore
- type: custom:button-card
  entity: scene.yourscene
  template:
    - card_generic_swap
  tap_action:
    action: call-service
    service: scene.turn_on
    service_data: 
      entity_id: scene.yourscene
  
# works without template
- type: custom:button-card
  tap_action:
    action: call-service
    service: scene.turn_on
    service_data: 
      entity_id: scene.yourscene
```

**Expected behavior**
When click the button the scene should be activated. With the template in button-card it results in an error.

**Comment by basbruss** [comment]
Hi @panhans 

This should still be possible. It will now only affect the outer layer of the card due to the more nested card framework introduced with the custom actions feature.

**Comment by panhans** [comment]
Yes, it should but since version 1.0.1 it runs in an error. Workaround is using the script template instead of generic.

**Comment by JSaterdalen** [comment]
> Hi @panhans
> 
> This should still be possible. It will now only affect the outer layer of the card due to the more nested card framework introduced with the custom actions feature.

It seems like it also prevents customizations to the icon and such from working. 

My card (below) will still trigger the script when the button edge is tapped, which is annoying enough, but does not respect my other customizations.

```
- type: "custom:button-card"
  template: card_generic
  entity: sensor.my_sensor
  icon: mdi:car
  styles:
    icon:
      - color: "rgba(var(--color-blue),0.7)"
    img_cell:
      - background-color: "rgba(var(--color-blue), 0.2)"
  tap_action:
    action: call-service
    service: script.turn_on
    service_data:
      entity_id: script.my_script
  hold_action:
    action: more-info
    entity: input_datetime.my_input
```

<img width="253" alt="image" src="https://user-images.githubusercontent.com/6761188/178406442-add720c4-5ce7-4772-bb43-3a28279b1b06.png">
