### ISSUE TITLE
Add haptic feedback

### ISSUE THREAD

**Issue by jeffconrad18** [UI-Lovelace-Minimalist/UI#850]
Hey, 
can we add [Haptics](https://companion.home-assistant.io/docs/integrations/haptics/) to all of the cards? 
It would look like this: 

```yaml
tap_action:
  haptic: light
```
Or maybe optionally with a variable!?
That would be very useful, so that you don't accidentally switch things on and off.

**Comment by mdb17** [comment]
Has this been solved with the 1.1.0 update? I am not getting haptic with my button presses.

**Comment by matrixx567** [comment]
Hi @mdb17,

It's already available in the current release.
See https://ui-lovelace-minimalist.github.io/UI/setup/custom_actions/ for more information.

**Comment by mdb17** [comment]
I have added the haptic actions to my `ulm_custom_actions.yaml` file and some button are providing haptic while others are not. Should all be working?

**Comment by matrixx567** [comment]
@mdb17 

Which cards aren't working?
Most of the internal cards should already work.

**Comment by mdb17** [comment]
The stock cards that I am not getting haptics with are: `card_person`, `card_script', and `card_vertical_button`. Is there something else i need to configure to get it all working?

I am also not getting haptics on `custom_card_esh_room` or `custom_card_esh_welcom` though I suspect something has to be done to those cards to enable it.

**Comment by matrixx567** [comment]
@mdb17 

These cards don't support the custom actions yet.

You can simply add the haptic support to your cards: Overwrite the tap action within your configuration for the specific cards.
```
tap_action:
  haptic: "medium"
```

**Comment by mdb17** [comment]
I currently have this on several cards but am not getting any haptics, do I have to reload or reboot or something?

```
          - type: "custom:button-card"
            template: card_vertical_button
            entity: input_select.primary_bedroom_scenes
            tap_action:
              haptic: "selection"
            name: All Lights
            icon: mdi:lamps
            variables:
              ulm_card_vertical_button_state: "All Lights"
              ulm_card_vertical_button_color: blue
```
