### ISSUE TITLE
problems with button card and variables for thermostat card

### ISSUE THREAD

**Issue by httpedo13** [UI-Lovelace-Minimalist/UI#88]
Hi, i have a problem with variables in button card. 

So, i want to take the temperature of climate entity (passed with variables) and increase by 0.5 degrees.
This is for button minus and plus in a thermostat card.

But, i receive this error: undefined is not an object (evaluating variables.entity.attributes.temperature)

This is my code:

```
card:
              type: "custom:button-card"
              template: widget_icon
              tap_action:
                action: call-service
                service: climate.set_temperature
                service_data:
                  temperature: " [[[ return (variables.entity.attributes.temperature + 0.5) ]]]"
                  entity_id: "[[[ return variables.entity ]]]"
              icon: "mdi:plus"
```

And, In the same page, this code from @tpx01 works great:

```
widget_temperature:
  tap_action:
    action: toggle
  color: var(--google-grey-500)
  show_icon: false
  show_name: false
  show_label: true
  size: 20px
  label: |-
    [[[
        var temperature = entity.attributes.temperature;
        if (temperature == null) {
          var temperature = '-';
        }
        return temperature + '°C'
    ]]]
  styles:
    label:
      - color: "rgb(var(--color-theme),0.9)"
    grid:
      - grid-template-areas: '"l"'
    card:
      - box-shadow: none
      - padding: 0px
      - background-color: "rgba(var(--couleur-theme),0)"
      - border-radius: 14px
      - place-self: center
      - height: 42px
 ```
