### ISSUE TITLE
On unavailability of entity, alert icon is duplicated in `card_graph`

### ISSUE THREAD

**Issue by mpeterson** [UI-Lovelace-Minimalist/UI#880]
**Describe the bug**
Whenever there is an unavailable entity the framework adds an alert icon. But starting with 1.0.3 this alert icon gets repeated twice, at least for `card_graph`

**To Reproduce**
Create a `card_graph` with an unavailable entity. 

As taken from the docs, just make sure that the sensor is `unavailable` (vs a non-existant one):

```
  - type: 'custom:button-card'
    template: card_graph
    entity: sensor.livingroom_temperature
    variables:
      ulm_card_graph_color: "var(--google-blue)"
      ulm_card_graph_name: Temperature Livingroom
      ulm_card_graph_entity: sensor.livingroom_temperature
```

**Expected behavior**
One alert icon instead of two.

**Screenshots**
<img width="533" alt="image" src="https://user-images.githubusercontent.com/11870/180615074-503b4977-98f7-4a92-a0f4-25b01c21fca7.png">

**Additional context**
