### ISSUE TITLE
Custom Actions overwrite on single card won't work for name and icon.

### ISSUE THREAD

**Issue by matrixx567** [UI-Lovelace-Minimalist/UI#884]
**Describe the bug**
The specific overwrite for the custom actions on a card won't work on the name and the icon fields. For the card the custom overwrite of the action works as expected.

**To Reproduce**

Configuration to open a popup on tap action for a sprecific card
```yaml
      - type: 'custom:button-card'
        template: 
          - card_generic
        entity: sensor.tempsensor_office_1_temperature
        variables:
          ulm_card_generic_name: "Temperatur"
          ulm_card_tap_action: "adaptive"
          ulm_name_tap_action: "adaptive"
```

**Expected behavior**
The popup should be opened if I tap on the name

**Additional context**
I think the variable overwrites must be redirected  to the custom fields in the `icon_more_info_new.yaml` and in the 'card_generic.yaml`.
