### ISSUE TITLE
Card room - Icons and font issues

### ISSUE THREAD

**Issue by alexmussor** [UI-Lovelace-Minimalist/UI#885]
**Describe the bug**
Hi! with the new update to UI Minimalist 1.0.3, new changes to the Card Room are shown in the Changelog, with a better distribution of the subicons. However, after the update, the title got bigger and the subicons (i.e. 3) are not being redistributed to fill the vertical column. Compared to the screenshots shown in the documentation (https://ui-lovelace-minimalist.github.io/UI/usage/cards/card_room/), this is not how it's supposed to look like.

**To Reproduce**
Create a card-room with the required parameters. In my case, I'm using three cards:
```
- type: 'custom:button-card'
  template:
    - card_room
    - blue_on
  label: ""
  name: "Bar"
  entity: light.bar_luces
  icon: mdi:glass-wine
  tap_action:
    action: navigate
    navigation_path: 'bar'
  variables:
    label_use_temperature: false
    label_use_brightness: false
    entity_1:
      entity_id: light.bar_luces
      templates:
        - yellow_on
      tap_action:
        action: toggle
      hold_action:
        action: more-info
- type: 'custom:button-card'
  template:
    - card_room
    - blue_on
  label: ""
  name: "Terraza"
  entity: light.terraza_luces
  icon: mdi:grill
  tap_action:
    action: navigate
    navigation_path: 'terraza'
  variables:
    label_use_temperature: false
    label_use_brightness: false
    entity_1:
      entity_id: light.terraza_luces
      templates:
        - yellow_on
      tap_action:
        action: toggle
      hold_action:
        action: more-info
    entity_2:
      entity_id: media_player.terraza
      templates:
        - blue_playing
        - blue_idle
        - blue_on
      tap_action:
        action: more-info
- type: 'custom:button-card'
  template:
    - card_room
    - blue_on
  label: ""
  name: "Baño 1er Piso"
  entity: light.bano_primer_piso_luces
  icon: mdi:toilet
  tap_action:
    action: navigate
    navigation_path: 'bano-primer-piso'
  variables:
    label_use_temperature: false
    label_use_brightness: false
    entity_1:
      entity_id: light.bano_primer_piso_luces
      templates:
        - yellow_on
      tap_action:
        action: toggle
      hold_action:
        action: more-info
```
**Expected behavior**
Subicons should re-size, redistribute and fill the column space considering 3 blocks.

**Screenshots**
This is an example of how the cards look after the update (title got bigger, and subicons kept the same size as if there were 4 in the same column):
![Screen Shot 2022-07-24 at 22 44 57](https://user-images.githubusercontent.com/12568960/180683101-51df5abd-11ad-409d-89fc-380f98291c55.png)

And this is a reference of how they should look according to the documentation:
![Screen Shot 2022-07-24 at 22 45 49](https://user-images.githubusercontent.com/12568960/180683517-668052d3-c319-4a1e-a14b-342d8080c5c9.png)

**Additional context**
None.
