### ISSUE TITLE
ulm_name_tap_action not working on card_binary_sensor

### ISSUE THREAD

**Issue by bokub** [UI-Lovelace-Minimalist/UI#886]
**Describe the bug**
The "name" tap action cannot be customized on "binary sensor" card.

**To Reproduce**

1. Create a new [input boolean](https://www.home-assistant.io/integrations/input_boolean/)
2. Create a new card with the following YAML code:
```yaml
    - type: "custom:button-card"
      template: card_binary_sensor
      variables:
        ulm_card_tap_action: more-info
        ulm_name_tap_action: more-info
        ulm_icon_tap_action: more-info
      entity: input_boolean.my_new_input_boolean
```

4. Click on the name of the input in the new card

**Expected behavior**
It should open the "more-info" popup. Instead it toggles the input.

**Additional context**

**N.B**: The `ulm_card_tap_action` and the `ulm_icon_tap_action` work well, only the `ulm_name_tap_action` is broken.
