### ISSUE TITLE
ulm_name_tap_action: navigate doesn't work

### ISSUE THREAD

**Issue by mdb17** [UI-Lovelace-Minimalist/UI#896]
**Describe the bug**
When using `ulm_name_tap_action: navigate` or `ulm_icon_tap_action: navigate`

**To Reproduce**
When using the following nothing happens
```
- type: "custom:button-card"
  template: card_light
  entity: light.closet_light
  variables:
    ulm_name_tap_action: navigate
    ulm_name_tap_navigate_path: "roku_remote"
    ulm_icon_tap_action: navigate
    ulm_icon_tap_navigate_path: "roku_remote"
```
Changing to the following will open the more info popup
```
- type: "custom:button-card"
  template: card_light
  entity: light.closet_light
  variables:
    ulm_name_tap_action: more-info
    ulm_icon_tap_action: more-info
```

**Expected behavior**
navigate to a the roku_remote page
