### ISSUE TITLE
No Colors are used => custom_card_esh_welcome

### ISSUE THREAD

**Issue by nicedevil007** [UI-Lovelace-Minimalist/UI#917]
**Describe the bug**
I installed everything with the stock template for getting started of this custom card but it is not showing the colors blue, yellow, red...

**To Reproduce**

1. install Minimalist (followed the guide from here => https://www.youtube.com/watch?v=A0fMt8IRKoI&t=446)
2. Click on the Minimalist Dashboard
3. See the welcome title without colors :(

**Expected behavior**
Colors will be taken as written in the template

**Screenshots**
![image](https://user-images.githubusercontent.com/17103076/182014040-5f57d9a7-64f9-41dd-81f3-411517872a17.png)

**Additional Information**

my view yaml file
```
title: "Home"
path: "home"
cards:
  - type: "custom:button-card"
    template: "card_esh_welcome"
    triggers_update: "input_boolean.minimalist_dropdown"
    variables:
      ulm_card_esh_welcome_collapse: input_boolean.minimalist_dropdown
      ulm_weather: "weather.skynet"
      entity_1:
        nav: "house"
        icon: "mdi:home"
        name: "House"
        color: "blue"
      entity_2:
        nav: "lights"
        icon: "mdi:lightbulb"
        name: "Lights"
        color: "yellow"
      entity_3:
        nav: "security"
        icon: "mdi:shield"
        name: Secure
        color: "green"
      entity_4:
        nav: "network"
        icon: "mdi:nas"
        name: Lab
        color: "purple"
      entity_5:
        nav: "network"
        icon: "mdi:flask"
        name: Lab
        color: "red"
```
