### ISSUE TITLE
Adaptive popup not working

### ISSUE THREAD

**Issue by Drealine** [UI-Lovelace-Minimalist/UI#927]
**Describe the bug**
When I wan't to click on the card, light or media_player, the action keep default (turn on, off or play/off)

**To Reproduce**

N/A

**Expected behavior**
Installing Lovelace UI via HACS

**Screenshots**
N/A

**Additional context**
Runing v1.1.0 and state-switch of course in v1.9.3

**Comment by matrixx567** [comment]
Hi @Drealine

can you share your configuration. Have you set the ulm_custom_actions?

**Comment by Drealine** [comment]
I follow all lines in the GitHub page of Adaptive page.
It work with the version 1.0.1 which is the first vision of this feature

**Comment by matrixx567** [comment]
There could also be another problem.

In the last release the popups have been refactored. For your popup configuration use an entity entry under your card config  instead the ulm_popup_light_entity variable

**Comment by matrixx567** [comment]
I did some tests and the adaptive dashboard works fine:

Use the following configuration on the card:
```yaml
  - view_layout:
      grid-area: "card1"
    type: "custom:button-card"
    template: "card_light"
    entity: light.light_bedroom_1
    variables:
      ulm_name_tap_action: "adaptive"
      ulm_input_select_option: light1
      ulm_input_select: input_select.minimalist_ui
```
For the popup configuration:
```yaml
states:
  #  Devices
  ##  Lights
  light1:
    type: "custom:button-card"
    template: "popup_light_brightness"
    entity: light.light_bedroom_1
```

**Comment by jnsfrg** [comment]
Hi @matrixx567,

I just stumbled across this issue as well. For me the problem was, that in the docs and in the samples provided in the popup.yaml it still shows this:

```yaml
states:
  ## Lights
  light 1:
    type: "custom:button-card"
    template: "popup_light_brightness"
    variables: # <--
      ulm_popup_light_entity: "<your_entity>" # <--
```

while it only works for me using your sample:
```yaml
states:
  ## Lights
  light 1:
    type: "custom:button-card"
    template: "popup_light_brightness"
    entity: "<your_entity>" # <-- 
```

Using the `ulm_popup_light_entity` there is a `ButtonCardJSTemplateError` showing up in the adaptive popup area.
