### ISSUE TITLE
Weather Popup doesn't work on Weather Card

### ISSUE THREAD

**Issue by tropics1999** [UI-Lovelace-Minimalist/UI#937]
**Describe the bug**
When adding the weather popup via ulm_custom_popup to the weather card behaviour is not changed - ie the card will still show the weather entity details instead of the popup when clicked.

**To Reproduce**
Added the below to my yaml file, the card displays and works correctly except for the popup.
```
- type: "custom:button-card"
   template: card_weather
     entity: weather.hackham
     variables:
       ulm_card_weather_name: " "
       ulm_card_weather_enable_popup: true
       ulm_card_tap_action: "popup"  
       ulm_custom_popup:
         template: "popup_weather_forecast"
         popup_variables:
           ulm_popup_weather_entity: weather.hackham
```

**Additional context**
I successfully added the popup to the Temperature Chip (chip_temperature template), and it worked as expected - so the issue appears isolated to the weather card.
I also tried overriding every action using the ulm_xxx_xxx_action variables I found on [this page of the wiki](https://ui-lovelace-minimalist.github.io/UI/setup/custom_actions/) to "popup".

Thanks in advance for your help and sorry if I am doing something wrong or missed a part of the documentation.

**Comment by Nicxe** [comment]
I have also tried to add it to [Custom Card "Welcome Navigation"](https://ui-lovelace-minimalist.github.io/UI/usage/custom_cards/custom_card_esh_welcome/?h=welcom) and got the same issue.

**Comment by matrixx567** [comment]
Hi,

Try the entity variable within the ulm_custom_popup instead of the ulm_popup_weather_entity.

**Comment by tropics1999** [comment]
I tested on a generic card using the below code, and it worked as expected;
```
- type: 'custom:button-card'
  template: card_generic
  entity: weather.hackham
  variables:
    ulm_card_tap_action: "popup" 
    ulm_custom_popup:
      template: "popup_weather_forecast"
```
I tried both with and without the ulm_popup_weather_entity flag, it didn't make any difference (ie it still worked on the generic card and didn't on the weather card) so I will remove it.

**Comment by matrixx567** [comment]
Hi @tropics1999,

I've done some testing with the weather card. I've found a way to enable custom actions for this card.  I will provide a pull request within the next days.

**Comment by tropics1999** [comment]
Thank you @matrixx567 - I'll be very keen to see it work 😄

**Comment by matrixx567** [comment]
My configuration to call the popup

```yaml
  - type: "custom:button-card"
    template: card_weather
    entity: weather.home
    variables:
      ulm_card_weather_name: " "
      ulm_card_weather_primary_info:
        - wind_speed
        - precipitation_probability
      ulm_card_weather_backdrop:
        fade: true
      ulm_card_tap_action: adaptive
      ulm_custom_popup:
        template: "popup_weather_forecast"
```

**Comment by Nicxe** [comment]
> My configuration to call the popup

I cant get that to work for me 😞

**Comment by matrixx567** [comment]
@Nicxe 

Have you included the files from the pull request?

**Comment by SgtRootCanal** [comment]
@Nicxe thanks for your work on this! Is there a way to add the overlay to a chip card without applying the overlay to all chips? 

For example, I am trying to add the weather pop up to the chip_weather_date card. The yaml for that points back to the chips.yaml template. I don't want to apply an overlay for all chips, but I still want the functionality while retaining some of the config info from the chips.yaml file. Is the easiest way for this to copy the chips.yaml config options needed into the chip_weather_date.yaml, then changing the template in that same file to ulm_actions_card_overlay?

**Comment by matrixx567** [comment]
@SgtRootCanal 

I havn't tested it, but try this configuration:

```yaml
- type: custom:button-card
  template:
    - "chip_weather_date"
    - "ulm_actions_card_overlay"
```
