### ISSUE TITLE
Media Player idle state blank

### ISSUE THREAD

**Issue by sildehoop** [UI-Lovelace-Minimalist/UI#94]
When Media Player Card entry has idle state card_media_player_with_control turns completely blank and the cards partly

<img width="493" alt="Schermafbeelding 2021-12-17 om 08 44 40" src="https://user-images.githubusercontent.com/34340385/146508204-b20456a5-be68-453c-8a76-3748eb070d7a.png">

yaml code:
```yaml
          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template: edge
              - type: "custom:button-card"
                template: card_media_player
                entity: media_player.living_room_speaker_1
                name: Living room Speaker
              - type: "custom:button-card"
                template: edge

          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template: edge
              - type: "custom:button-card"
                template: card_media_player_with_control
                entity: media_player.living_room_speaker_1
                name: Living room Speaker
              - type: "custom:button-card"
                template: edge

          - type: horizontal-stack
            cards:
              - type: "custom:button-card"
                template: edge
              - type: "custom:button-card"
                template:
                  - card_media_player_with_controls
                variables:
                  ulm_card_media_player_with_controls_name: "Living room Speaker"
                  ulm_card_media_player_with_controls_entity: media_player.living_room_speaker_1
              - type: "custom:button-card"
                template: edge
```
