### ISSUE TITLE
Custom Waste Collection card not working at all

### ISSUE THREAD

**Issue by AndLindemann** [UI-Lovelace-Minimalist/UI#940]
**Describe the bug**
Tried to add the custom paddy_waste_collection card, but it doesn't work at all, throws JS errors in console.

**To Reproduce**
```
          - type: "custom:button-card"
            template:
              - custom_card_paddy_waste_collection
            entity: sensor.abfall
            variables:
              ulm_custom_card_paddy_waste_collection_name: paper
              ulm_custom_card_paddy_waste_collection_icon: mdi:trash-can
```

```
[Error] anonymous@
_evalTemplate@https://..../ui_lovelace_minimalist/cards/button-card/button-card.js:425:73268
@https://..../ui_lovelace_minimalist/cards/button-card/button-card.js:425:73761
forEach@[native code]
_getTemplateOrValue@https://..../ui_lovelace_minimalist/cards/button-card/button-card.js:425:73726
render@https://..../ui_lovelace_minimalist/cards/button-card/button-card.js:425:70749
update@https://..../ui_lovelace_minimalist/cards/button-card/button-card.js:1:19902
performUpdate@https://..../ui_lovelace_minimalist/cards/button-card/button-card.js:1:16788
@https://..../ui_lovelace_minimalist/cards/button-card/button-card.js:1:16447
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
	render (button-card.js:425:70844)
	update (button-card.js:1:19903)
	performUpdate (button-card.js:1:16789)
	(anonyme Funktion) (button-card.js:1:16448)
	asyncFunctionResume
	(anonyme Funktion)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

**Expected behavior**
Waste collection card displayed

**Screenshots**
<img width="605" alt="sensor data" src="https://user-images.githubusercontent.com/4157845/184109013-056f76d8-8194-4e74-bc64-9810c48bf4a7.png">

**Additional context**
n/a

**Comment by AndLindemann** [comment]
Somehow it seems the card cannot access the variables:

<img width="349" alt="Bildschirmfoto 2022-08-25 um 16 06 21" src="https://user-images.githubusercontent.com/4157845/186687099-e66769d0-2948-4ae8-a7f4-0470fac79a64.png">

Dashboard code:
```
      - type: custom:button-card
        template: custom_card_paddy_waste_collection
        entity: sensor.abfall
        variables:
          ulm_custom_card_paddy_waste_collection_icon: "mdi:delete"
          ulm_custom_card_paddy_waste_collection_name: "Papier"
```

Card template code:
```
---
custom_card_paddy_waste_collection:
  template:
    - "card_generic_swap"
  variables:
    ulm_card_generic_swap_name: "[[[ return variables.ulm_custom_card_paddy_waste_collection_name; ]]]"
    ulm_card_generic_swap_icon: "[[[ return variables.ulm_custom_card_paddy_waste_collection_icon; ]]]"
  state:
    - operator: "template"
```

Now if I just replace the 
 ```
   ulm_card_generic_swap_name: "[[[ return variables.ulm_custom_card_paddy_waste_collection_name; ]]]"
    ulm_card_generic_swap_icon: "[[[ return variables.ulm_custom_card_paddy_waste_collection_icon; ]]]"
```
in the template card with fixed strings, the card works. It can't be too difficult to get the card to properly access the variables, but I wasn't able to figure it out. Any hints?

**Comment by SgtRootCanal** [comment]
I am having the same issue. Can you share what you changed for the two variables above? I tried adding a string but it is still not showing up.

**Comment by rust84** [comment]
Seems to be related to https://github.com/UI-Lovelace-Minimalist/UI/pull/783

Slightly different workaround which retains variables:

Card template:
```
custom_card_paddy_waste_collection:
  template:
    - "card_generic_swap"
  variables:
    ulm_card_generic_swap_name: "[[[ return variables.ulm_card_generic_swap_name ]]]"
    ulm_card_generic_swap_icon: "[[[ return variables.ulm_card_generic_swap_icon ]]]"
```

Card:

```
    type: "custom:button-card"
    template: custom_card_paddy_waste_collection
    entity: sensor.waste_collection_household
    variables:
      ulm_card_generic_swap_icon: mdi:delete
      ulm_card_generic_swap_name: Household
```
