### ISSUE TITLE
Custom_esh_room popup doesn't work

### ISSUE THREAD

**Issue by frantathefranta** [UI-Lovelace-Minimalist/UI#949]
**Describe the bug**
Using card_esh_room doesn't work with custom popups, holding the light or climate icon only gets me to basic popup. Testing with a barebones light card and custom popup there works. I'm not sure what I'm missing.

**To Reproduce**
My card config looks like this
```
- type: "custom:button-card"
  template:
    - card_esh_room
    - yellow_on
  name: Living Room
  entity: light.lights
  icon: mdi:sofa
  tap_action:
    action: navigate
    navigation_path: "livingroom"
  variables:
    ulm_custom_card_esh_room_light_entity: light.lights
    ulm_card_light_enable_popup: true
    ulm_custom_card_esh_room_climate_entity: climate.thermostat
    ulm_card_thermostat_enable_popup: true
  label: '[[[ return states["sensor.thermostat_air_temperature"].state + "°F" ]]]'
```

**Expected behavior**
Holding the climate or light button on the custom room card should get me to a custom popup, but it only shows the basic Home Assistant popup.

**Screenshots**
[Holding the light button on this card](https://imgur.com/QslsGrx) only gets me [here](https://imgur.com/A9Z5BHj)

**Additional context**
browser_mod is installed and I have updated the custom_esh_room cards and UI minimalist itself to the latest version.
