### ISSUE TITLE
Custom cards won't hide in Adaptive Dashboard

### ISSUE THREAD

**Issue by voicubabiciu** [UI-Lovelace-Minimalist/UI#965]
Hello everyone!
I am trying to implement a simple adaptive dashboard using some custom cards and I want some cards to be displayed only on the mobile screen and others on the desktop version. Well, the problem is that some of the cards are still displaying on the dashboard even if I don't use their grid area in the layout. Bellow I attached a part of my code and some screenshots.
``` yaml
---
type: "custom:layout-card"
layout_type: "custom:grid-layout"
layout:
  # Tablet portrait
  grid-template-columns: "1fr 1fr 1fr 1fr 1fr 1fr"
  grid-template-areas: |
    "welcome welcome welcome welcome welcome welcome"
    ". . . hdd-1-temp-chart hdd-1-temp-chart hdd-1-temp-chart"
    ". . . hdd-2-temp-chart hdd-2-temp-chart hdd-2-temp-chart"
    ". . . hdd-3-temp-chart hdd-3-temp-chart hdd-3-temp-chart"
    ". . . hdd-4-temp-chart hdd-4-temp-chart hdd-4-temp-chart"
    ". . . hdd-5-temp-chart hdd-5-temp-chart hdd-5-temp-chart"
  mediaquery:
    # Mobile
    "(max-width: 800px)":
      grid-template-columns: "1fr 1fr"
      grid-template-areas: |
        "welcome welcome"
        "hdd-1-temp-summary hdd-2-temp-summary"
        "hdd-3-temp-summary hdd-4-temp-summary"
        "hdd-5-temp-summary hdd-5-temp-summary"   

view_layout:
  grid-area: "main"
cards:
  - view_layout:
      grid-area: "welcome"
    type: "custom:button-card"
    template: "card_title"
    name: "Hello Sir!"

  - view_layout:
      grid-area: "hdd-1-temp-summary"
    type: "custom:button-card"
    template: card_generic_swap
    entity: sensor.truenas_da1

  - view_layout:
      grid-area: "hdd-1-temp-chart"
    type: 'custom:button-card'
    template: card_graph
    entity: sensor.truenas_da1
    variables:
      ulm_card_graph_color: "var(--google-yellow)"
      ulm_card_graph_name: HDD da1 Temperature
      ulm_card_graph_entity: sensor.truenas_da1
      ulm_card_graph_type: fill 

```
### Desktop:
![image](https://user-images.githubusercontent.com/22860378/187023813-03207ea3-fe73-4cb6-b0ae-a33cdb7cd88b.png)

### Mobile:
![image](https://user-images.githubusercontent.com/22860378/187023843-573fc644-c202-4c9c-a4a3-9dc0be1c6376.png)
