### ISSUE TITLE
Media Player card art "overlapping" into other cards on Safari

### ISSUE THREAD

**Issue by AndLindemann** [UI-Lovelace-Minimalist/UI#970]
**Describe the bug**
When more than one media player card is being displayed, and one of the media player cards refreshes it's "art" image, it causes some overlap on adjacent media player cards.

**To Reproduce**

1. Have 2 media player cards below each other with "ulm_card_media_player_enable_art: true"
2. Have the media player card at the bottom refresh it's art image
3. Observe that sometimes the image overlaps/influences  the media player card above. 

This is the code used for the cards:
```
      - type: "custom:button-card"
        template: card_media_player
        entity: media_player.ymh_wohnzimmer
        variables:
          ulm_card_media_player_name: "Yamaha Receiver"
          ulm_card_media_player_enable_popup: true
          ulm_card_media_player_enable_art: true
          ulm_card_media_player_more_info: true
          ulm_card_media_player_enable_controls: true
          ulm_card_media_player_collapsible: true
      - type: "custom:button-card"
        template: card_media_player
        entity: media_player.enigma2_media_player
        variables:
          ulm_card_media_player_name: "Sat Receiver"
          ulm_card_media_player_enable_popup: true
          ulm_card_media_player_enable_art: true
          ulm_card_media_player_more_info: true
          ulm_card_media_player_enable_controls: true
          ulm_card_media_player_collapsible: true
```

**Expected behavior**
Media player art display/refresh should not cause any impact on adjacent media player cards

**Screenshots**
In below image you can see that when the media player playing back "Vox HD" refreshed it's art image, it caused the visible black overlay on the media player card "Yamaha Receiver" above it to appear, blocking out half of the card.

<img width="632" alt="Bildschirmfoto 2022-09-01 um 17 54 28" src="https://user-images.githubusercontent.com/4157845/187959494-02a51fd6-f00e-4663-aa5d-2bbc953c50a6.png">

Below image is the same dashboard shown on the iOS Home Assistant app, exhibiting a similar issue. Here the art refresh directly blacked out 2 media player cards, the "Vox HD" playing card was the refreshing card and the Yamaha Receiver card was affected by it.

![PNG-Bild](https://user-images.githubusercontent.com/4157845/187960590-db108cd9-1cc7-48c7-a477-49013e0915d1.png)

**Additional context**
This is observed on MacOS Safari and iOS Safari (also iOS Home Assistant App). Could not reproduce on Firefox, so may be a browser related issue.
